Update reverse-proxy.mdx
Fallenbagel/jellyseerr pull request #1052
Opened 2024-10-23 17:08 UTC by C4J3

Fix posters not showing up when using sub-folder (at least with NPM)

#### Description

Fixes title card images not appearing if using subfolders.
#### Screenshot (if UI-related)

Before:
![image](https://github.com/user-attachments/assets/9c3ba543-6d56-43bc-bdf5-190ed88ebf90)

After:
![image](https://github.com/user-attachments/assets/92a8cf38-2791-4be3-acec-5e4b4cbcef3a)

#### Aditional Notes

I know this is not officially supported but I figured this was a byproduct of the recent update and it just wasn't thought about. Small change but for idiots like me it'll save 10-100~ mins of trying to troubleshoot 😅.

2024-10-23 17:34 UTC, gauthier-th requested changes

2024-10-23 17:34 UTC, gauthier-th commented on docs/extending-jellyseerr/reverse-proxy.mdx
> +    sub_filter '/imageproxy/' '/$app/imageproxy/';
You should also add `avatarproxy` which was added in v2.
```suggestion
    sub_filter '/imageproxy/' '/$app/imageproxy/';
    sub_filter '/avatarproxy/' '/$app/avatarproxy/';
```

2024-10-23 18:02 UTC, C4J3 commented
Possibly unrelated to this. Is the subpath not meant to be maintained for actual jellyseerr subpaths? So if I have mydomain.tld/jellyseer I go to the discovery page but if I click movies I go to mydomain.tld/discover/movies. Don't remeber if I had this behaviour previously because I mostly used requestrr and didn't use external address when connecting to Jellyseerr itself.

2024-10-24 01:02 UTC, Fallenbagel commented
> Possibly unrelated to this. Is the subpath not meant to be maintained for actual jellyseerr subpaths? So if I have mydomain.tld/jellyseer I go to the discovery page but if I click movies I go to mydomain.tld/discover/movies. Don't remeber if I had this behaviour previously because I mostly used requestrr and didn't use external address when connecting to Jellyseerr itself.

Subpath is not supported officially.

2024-10-24 01:10 UTC, Fallenbagel commented
Also the commit message has to start from `docs: .....` or this won't be reflected on the docs after merge

2024-11-13 02:53 UTC, Fallenbagel approved these changes

2024-11-13 02:54 UTC, merged

2024-12-16 13:11 UTC, gauthier-th commented
@all-contributors please add @C4J3 for doc

2024-12-16 13:59 UTC, Fallenbagel commented
@all-contributors please add @C4J3 for doc

2024-12-29 22:57 UTC, Fallenbagel commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- `v2.2.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: