feat(language): update czech language
Fallenbagel/jellyseerr pull request #150
Opened 2022-06-19 19:04 UTC by Smexhy

#### Description

updates the czech language from overseer weblate and add jellyseer specifics

2022-06-20 13:27 UTC, Fallenbagel requested changes
~From 1014 - 1045 you (i did not add comment) but all the {} ones should not be changed~
Ignore this.

2022-06-20 13:27 UTC, Fallenbagel commented on src/i18n/locale/cs.json
> +  "components.Layout.VersionStatus.commitsbehind": "{commitsBehind} {commitsBehind, plural, one {commit} other {commitů}} za",
Why is the {{commits}} changed?

2022-06-20 13:27 UTC, Fallenbagel commented on src/i18n/locale/cs.json
> +  "components.IssueList.IssueItem.episodes": "{episodeCount, plural, zero {Epizod} one {Epizoda} other {Epizody}}",
Here too {} ones should remain as they were

2022-06-20 13:27 UTC, fallenbagel commented on src/i18n/locale/cs.json
> +  "components.IssueList.IssueItem.seasons": "{seasonCount, plural, zero {Sezón} one {Sezóna} other {Sezóny}}",
this one too

2022-06-20 19:11 UTC, Smexhy commented on src/i18n/locale/cs.json
> +  "components.IssueList.IssueItem.seasons": "{seasonCount, plural, zero {Sezón} one {Sezóna} other {Sezóny}}",
I have used the following syntax https://formatjs.io/docs/core-concepts/icu-syntax#plural-format translating multiple forms of plurals. The strings inside mentioned brackets need to be translated as well. For example it was translated that way in german localisation file as well: https://github.com/Fallenbagel/jellyseerr/blob/883b9377be209de534db0a7bc9e56a125e3df39a/src/i18n/locale/de.json#L997

2022-06-21 06:49 UTC, Fallenbagel commented on src/i18n/locale/cs.json
> +  "components.IssueList.IssueItem.seasons": "{seasonCount, plural, zero {Sezón} one {Sezóna} other {Sezóny}}",
Ah sorry. I am not familiar with that. Sorry for taking your time

2022-06-21 06:51 UTC, Fallenbagel approved these changes

2022-06-24 00:30 UTC, merged

2022-10-12 15:36 UTC, Fallenbagel commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- `v1.2.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-07 22:26 UTC, Fallenbagel commented
@all-contributors please add @Smexhy for translation