feat: support OIDC authentication
Fallenbagel/jellyseerr pull request #184
Opened 2022-07-11 23:27 UTC by michaelhthomas

#### Description

Adds support for logging in using an OIDC Identity Provider (Auth0, Authentik, Keycloak, etc.).

Refactors Plex OAuth login to be in its own component, like the other identity providers.

#### Screenshot (if UI-related)

![Login Page](https://user-images.githubusercontent.com/18223295/178186279-5a276b0c-258d-42fc-a025-8e03f0f3eea3.png)

![Settings Page](https://user-images.githubusercontent.com/18223295/178374945-a16ba5f6-b754-4109-a191-ffcb53766029.png)

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #183
- Fixes #86

2022-07-15 07:17 UTC, Fallenbagel commented
Ah I see that you resolved the merge conflicts. Was going to ask. Thanks

2022-07-22 12:28 UTC, Fallenbagel commented
@michaelhthomas Hi. I tried to test this PR, however, during first setup in the library step, I get this error and I am not able to continue it setup
![image](https://user-images.githubusercontent.com/98979876/180438824-9d9e3daf-463c-4592-916e-8f17c4f0c7d7.png)

2022-07-22 12:30 UTC, michaelhthomas commented
Uh oh... I'm pretty sure that means you made it to the second page but aren't logged in with Plex or Jellyfin, which probably means the login failed and I need to add some better error handling. Which one were you testing?

2022-07-22 12:32 UTC, Fallenbagel commented
> Which one were you testing?

Jellyfin. That is from the libraries setup page right after logging in

2022-07-22 13:27 UTC, michaelhthomas commented
@Fallenbagel Any errors in the console?

2022-07-23 17:58 UTC, michaelhthomas commented
@Fallenbagel Found the bug and am working on a fix. Got a question...right now there's a value for `MediaServerType.EMBY` that's essentially unused, since emby is actually treated as `MediaServerType.JELLYFIN` with `JELLYFIN_TYPE` set to "emby". Would you be ok with removing `MediaServerType.EMBY` to avoid confusion, or would you rather everything use `MediaServerType.EMBY` instead of `JELLYFIN_TYPE` for consistency?

2022-07-23 19:56 UTC, Fallenbagel commented
We need the `MediaServerType=Emby` as the current emby implementation is temporary. We are going to be implementing emby without the env variable through api which would also allow us to have simultaneous server support. So we need it

2022-07-23 19:59 UTC, michaelhthomas commented
Ok sweet. I'll test Emby with my current implementation to make sure everything works as expected, and when it's implemented properly there will probably be some changes that need to be made to the login window / setup wizard.

2022-08-06 13:46 UTC, Fallenbagel commented
> Ok sweet. I'll test Emby with my current implementation to make sure everything works as expected, and when it's implemented properly there will probably be some changes that need to be made to the login window / setup wizard.

I have not tested yet but if it works for emby it should work for jellyfin. Will test tonight

2022-08-18 09:24 UTC, Fallenbagel commented
I tested the setup and it indeed worked. However, as I have no way of testing OIDC, I will deploy this as a preview tag for testing for now

2022-09-18 22:45 UTC, michaelhthomas commented
@Fallenbagel resolved the merge conflicts. OIDC is working great for me (using authentik) but would love to have some others test with different OIDC providers.

2022-09-18 23:16 UTC, Fallenbagel commented
> @Fallenbagel resolved the merge conflicts. OIDC is working great for me (using authentik) but would love to have some others test with different OIDC providers.

Is LDAP possible with this?

2022-09-19 00:43 UTC, michaelhthomas commented
> > @Fallenbagel resolved the merge conflicts. OIDC is working great for me (using authentik) but would love to have some others test with different OIDC providers.
> 
> Is LDAP possible with this? (I don't really know OIDCs and stuff so)

Not directly. A number of oauth2 / OIDC providers do integrate with LDAP (including authentik) for authentication, but oauth2 is much higher level. Where LDAP acts more like an external users database, an OIDC/oauth provider handles all the sign in and authentication logic. Plex SSO actually uses oauth2 afaik, it just doesn't conform to the OIDC standard.

2022-09-22 05:07 UTC, BoBeR182 commented
I can test with Keycloak, just learning how to compile and run this build still.

2022-09-22 12:03 UTC, Fallenbagel commented
> I can test with Keycloak, just learning how to compile and run this build still.

If you want to compile it natively to test instead of the deployed docker snapshot, pull this PR and try it

2022-09-23 19:46 UTC, atropos112 commented
Howdy,

I am excited to see this MR, its certainly something that is missing in my setup and hence i (somewhat selfishly) want to help.

---
My relevant setup:
I am running Sonarr, Radarr, Jellyfin. I am also running Authelia which I currently use as my OpenID solution for ArgoCD, WikiJs, Grafana, Harbor and Gitlab.
---

I have never implemented open id login mechanism but I have set it up for few applications (as outlined above), I am happy to test and provide feedback. I have ran your branch locally and have few questions.


A typical config in Authelia looks something like this 
```
- id: <user-picked-id-here>
  pre_configured_consent_duration: '365d'
  description: idk
  secret: <SECRETHERE>
  public: false
  authorization_policy: one_factor
  audience: []
  scopes:
    - openid
    - email
    - profile
  redirect_uris:
    - <CALLBACKURL>
   response_modes:
        - form_post 
```
(I believe data needed to setup is somewhat similar for KeyCloak +- some small details)

In particular both Authelia and the app (Jellyseerr in this case) need to have id and the secret, both of which are chosen by the client.. In addition authelia (keycloak also) needs the callback url and the required scopes. In your implementation I see place for id but not the secret, is there a way of adding this ? I also do not know (maybe i am missing something obvious) what the callback url is and what scopes are required.

2022-09-23 20:58 UTC, michaelhthomas commented
> Howdy,
> 
> I am excited to see this MR, its certainly something that is missing in my setup and hence i (somewhat selfishly) want to help.
> 
> My relevant setup: I am running Sonarr, Radarr, Jellyfin and of course Jellyseerr. I am also running Authelia which I currently use as my OpenID solution for ArgoCD, WikiJs, Grafana, Harbor and Gitlab.
> 
> I have never implemented open id login mechanism but I have connected few applications to OpenID that Authelia provides (as outlined above), I am happy to test and provide feedback. I have ran your branch locally and have few questions.
> 
> A typical config in Authelia looks something like this
> 
> ```
> - id: <user-picked-id-here>
>   pre_configured_consent_duration: '365d'
>   description: idk
>   secret: <SECRETHERE>
>   public: false
>   authorization_policy: one_factor
>   audience: []
>   scopes:
>     - openid
>     - email
>     - profile
>   redirect_uris:
>     - <CALLBACKURL>
>    response_modes:
>         - form_post 
> ```
> 
> (I believe data needed to setup is somewhat similar for KeyCloak +- some small details)
> 
> In particular both Authelia and the app (Jellyseerr in this case) need to have id and the secret, both of which are chosen by the client.. In addition authelia (keycloak also) needs the callback url and the required scopes. In your implementation I see place for id but not the secret, is there a way of adding this ? I also do not know (maybe i am missing something obvious) what the callback url is and what scopes are required.

Because Jellyseerr is a SPA (single page app), it uses the OAuth PKCE authorization flow instead of the traditional authorization flow. Since all of the login and (most of) the validation logic occurs on the client when using this flow, the client secret is not used. This is a "public" authorization flow, so the configuration will look a little bit different from apps using the traditional authorization flow. [This looks to be the relevant configuration option for Authelia](https://www.authelia.com/configuration/identity-providers/open-id-connect/#public), and other providers should have similar options. In order to maintain security with this mechanism, be sure that the redirect URLs are limited only to your Jellyseerr instance (`https://your-jellyseerr-instance.xyz/login`). Also, the `openid`, `profile`, and `email` scopes are all used so that Jellyseer can view users' names and email addresses. Thanks for being open to testing this out!

2022-09-24 13:23 UTC, atropos112 commented
That makes a lot of sense! I take it then I need something like this 
```
      - id: jellyseerr
        public: true
        authorization_policy: one_factor
        audience: []
        scopes:
        - openid
        - email
        - profile
        redirect_uris:
        - https://jellyserrr-instance.xyz/login
        userinfo_signing_algorithm: none
        response_modes:
        - form_post 
```
I am building the docker image now, will shortly deploy and update.

2022-09-24 13:50 UTC, Fallenbagel commented
> That makes a lot of sense! I take it then I need something like this 
> ```
>       - id: jellyseerr
>         public: true
>         authorization_policy: two_factor
>         audience: []
>         scopes:
>         - openid
>         - email
>         - profile
>         redirect_uris:
>         - https://jellyserrr-instance.xyz/login
>         userinfo_signing_algorithm: none
>         response_modes:
>         - form_post 
> ```
> I am building the docker image now, will shortly deploy and update.

Docker image is already built tho. Can be access through `preview-prxxx` where xxx is this PRs number

2022-09-24 14:40 UTC, atropos112 commented
I wanted to test it further so I ran 

```
docker build -t oicd-jellyseerr -f Dockerfile .
docker tag oidc-jellyseerr:latest myharbor.xyz/testing/oidc-jellyseerr:develop
docker push myharbor.xyz/testing/oidc-jellyseerr:develop
```

but when i run a pod with the above image I get
![image](https://user-images.githubusercontent.com/33070637/192103815-fde19d63-85fc-48d9-8240-000e3a410291.png)

this is strange, I tried running on the normal develop branch to see if its something with your changes (which I doubted) but I get the same issue. Data seems to need to be reloaded but even if i start on fresh pvc i still get this. Is there some variable I am missing ?

2022-09-24 15:56 UTC, michaelhthomas commented
> I wanted to test it further so I ran 
> 
> ```
> docker build -t oicd-jellyseerr -f Dockerfile .
> docker tag oidc-jellyseerr:latest myharbor.xyz/testing/oidc-jellyseerr:develop
> docker push myharbor.xyz/testing/oidc-jellyseerr:develop
> ```
> 
> but when i run a pod with the above image I get
> ![image](https://user-images.githubusercontent.com/33070637/192103815-fde19d63-85fc-48d9-8240-000e3a410291.png)
> (pressing reload refreshes the page and this pop-up appears again)
> this is strange, I tried running on the normal develop branch to see if its something with your changes (which I doubted) but I get the same issue. Data seems to need to be reloaded but even if i start on fresh pvc i still get this. Is there some variable I am missing ?

What happens when you press the reload button? That just looks like your browser still has the old version of the web interface cached

2022-09-24 16:37 UTC, atropos112 commented
I thought it had it cached so I used Incognito as well as different browser, I observed the same behavior. When I press reload it refreshes the page and the same message appears. 

I normally run stable, it said in the corner "Develop" and "Out of date" :/ I am certain its not to do with your changes but it does mean I can't test it until I figure this out, apologies.

2022-09-24 16:53 UTC, michaelhthomas commented
> I thought it had it cached so I used Incognito as well as different browser, I observed the same behavior. When I press reload it refreshes the page and the same message appears. 
> 
> I normally run stable, it said in the corner "Develop" and "Out of date" :/ I am certain its not to do with your changes but it does mean I can't test it until I figure this out, apologies.

Weird. Have you tried with the `fallenbagel/jellyseerr:preview-pr184` image?

2022-09-24 17:22 UTC, atropos112 commented
This works! I still have that in the corner but, no popup so can do the testing.
![Uploading image.png…]()

For below examples https://myauthelia.xyz is my authelia link and https://myjellyseerr.xyz is my jellyseerr link.

From authelias side I have
```
      - id: jellyseerr
        public: true
        authorization_policy: two_factor
        audience: []
        scopes:
        - openid
        - email
        - profile
        redirect_uris:
        - https://myjellyserr.xyz/login
        userinfo_signing_algorithm: none
        response_modes:
        - form_post 
```

from Jellyseerr side the settings are as follows:

```
Enable OIDC Sign-In: On
OIDC Issuer URL: https://myauthelia.xyz
OIDC Provider Name: Authelia
OIDC Client ID: jellyseerr
```

During login I now see option for Authelia but when I click on it I get 
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."}
```

I suspect `redirect_uri: https://myjellyserr.xyz/login` is not the correct one here

2022-09-24 17:47 UTC, michaelhthomas commented
> This works! I still have that in the corner but, no popup so can do the testing.
> ![Uploading image.png…]()
> 
> For below examples https://myauthelia.xyz is my authelia link and https://myjellyseerr.xyz is my jellyseerr link.
> 
> From authelias side I have
> ```
>       - id: jellyseerr
>         public: true
>         authorization_policy: two_factor
>         audience: []
>         scopes:
>         - openid
>         - email
>         - profile
>         redirect_uris:
>         - https://myjellyserr.xyz/login
>         userinfo_signing_algorithm: none
>         response_modes:
>         - form_post 
> ```
> 
> from Jellyseerr side the settings are as follows:
> 
> ```
> Enable OIDC Sign-In: On
> OIDC Issuer URL: https://myauthelia.xyz
> OIDC Provider Name: Authelia
> OIDC Client ID: jellyseerr
> ```
> 
> During login I now see option for Authelia but when I click on it I get 
> ```
> {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."}
> ```
> 
> I suspect `redirect_uri: https://myjellyserr.xyz/login` is not the correct one here ( I also tried `https://myjellyseerr.xyz/oauth2/callback` hoping for silly luck but no dice)
> 
> 

Check and make sure your "application URL" on the main settings page is set correctly.

2022-09-24 17:52 UTC, atropos112 commented
That was definitely an issue, I had it empty. After setting it to https://myjellyseerr.xyz i logged out and tried again this time I didn't get a failure as before, the page "refreshed". I have noticed however that the link changed to
```
https://myjellyseerr.xyz/login?error=unsupported_response_mode&error_description=The+authorization+server+does+not+support+obtaining+a+response+using+this+response+mode.+The+client+is+not+allowed+to+request+response_mode+%27query%27.&state=128992d58caa4f2da5de06719fe7bae1
```

2022-09-24 18:01 UTC, atropos112 commented
I have now figured out that i simply needed to add "query" as one response modes in authelia config. After doing so it does go to authelia after I log in it goes back to JellySeerr but has does not log me in :/

2022-09-24 19:09 UTC, Fallenbagel commented
> but when i run a pod with the above image I get
> ![image](https://user-images.githubusercontent.com/33070637/192103815-fde19d63-85fc-48d9-8240-000e3a410291.png)
> (pressing reload refreshes the page and this pop-up appears again)
> this is strange, I tried running on the normal develop branch to see if its something with your changes (which I doubted) but I get the same issue. Data seems to need to be reloaded but even if i start on fresh pvc i still get this. Is there some variable I am missing ?

This happens because you have to add in the commit hash as an argument when you build

2022-09-25 12:58 UTC, BoBeR182 commented
Update on Keycloak OIDC as a provider.

Managed to run the docker-compose with the preview-pr183

Configured Jellyseerr application with Jellyfin running on host outside of docker. (scans work) skipping Radarr and Sonarr for simplicity.
Set Application URL to `http://127.0.0.1:5055` could not set it to `http://localhost:5055`
Added a new OIDC.
Issuer URL had to be without the .well-known portion.
Client ID had to match what was set in keycloak.

Keycloak settings are as follows:
![image](https://user-images.githubusercontent.com/525433/192144447-ef3fcdda-1a07-4bf3-9244-2cada9452bef.png)

One user added with role "overseerr"

Upon login via SSO, Jellyseerr gets stuck in a loop of requests.

![image](https://user-images.githubusercontent.com/525433/192144577-b1f16e53-1f5d-46dd-b35a-aed1588b7f7e.png)

The GET request for the oidc endpoint returns:
`jwt issuer invalid. expected: https://keycloak.domain.tld/realms/realm/`

The token seems corrupted when base64 is decoded.
![image](https://user-images.githubusercontent.com/525433/192144276-a963d0ba-c59d-42c6-b496-a6b1d07b628d.png)

2022-09-25 14:50 UTC, michaelhthomas commented
> Update on Keycloak OIDC as a provider.
> 
> Managed to run the docker-compose with the preview-pr183
> 
> Configured Jellyseerr application with Jellyfin running on host outside of docker. (scans work) skipping Radarr and Sonarr for simplicity. Set Application URL to `http://127.0.0.1:5055` could not set it to `http://localhost:5055` Added a new OIDC. Issuer URL had to be without the .well-known portion. Client ID had to match what was set in keycloak.
> 
> Keycloak settings are as follows: ![image](https://user-images.githubusercontent.com/525433/192144447-ef3fcdda-1a07-4bf3-9244-2cada9452bef.png)
> 
> One user added with role "overseerr"
> 
> Upon login via SSO, Jellyseerr gets stuck in a loop of requests.
> 
> ![image](https://user-images.githubusercontent.com/525433/192144577-b1f16e53-1f5d-46dd-b35a-aed1588b7f7e.png)
> 
> The GET request for the oidc endpoint returns: `jwt issuer invalid. expected: https://keycloak.domain.tld/realms/realm/`
> 
> The token seems corrupted when base64 is decoded. ![image](https://user-images.githubusercontent.com/525433/192144276-a963d0ba-c59d-42c6-b496-a6b1d07b628d.png)

That token definitely looks corrupted. Make sure you copied the whole token (I just made that mistake while testing 😊), the valid payload should be much longer. Also, it looks like there might some sort of trailing slash discrepancy between the expected and actual issuers, which is weird. I was able to get it working with Keycloak locally, which indicates there's probably something going on with your instance.

Also, I might try and add some throttling for OIDC login requests since it gets pretty crazy if there are any errors with the setup.

2022-09-25 16:13 UTC, BoBeR182 commented
> Does the issuer in the payload ("https://keycloak.domain.tld/...") match your keycloak instance uri?

Yes, maybe off by a trailing slash, but when I change that in the settings, it gets 404 error messages, and returns error 500 code.
![image](https://user-images.githubusercontent.com/525433/192153786-43d37e05-d4b3-4612-a880-4c6c9b91e1eb.png)

Can you share your Keycloak config?

2022-09-25 16:25 UTC, michaelhthomas commented
> > Does the issuer in the payload ("https://keycloak.domain.tld/...") match your keycloak instance uri?
> 
> Yes, maybe off by a trailing slash, but when I change that in the settings, it gets 404 error messages, and returns error 500 code. ![image](https://user-images.githubusercontent.com/525433/192153786-43d37e05-d4b3-4612-a880-4c6c9b91e1eb.png)
> 
> Can you share your Keycloak config?

I believe I figured out what's wrong. Try restarting Jellyseerr and see if it works after a restart.

I believe the issue is that the express middleware doesn't update when the "OIDC Issuer" setting is changed, which means the issuer set on the client and the issuer set on the server become mismatched.

2022-09-25 18:15 UTC, BoBeR182 commented
![image](https://user-images.githubusercontent.com/525433/192158754-f0b27af3-18ab-44e6-b858-773544821630.png)
These are my settings. I will rebuild image and report back with the new patches.

2022-09-25 18:19 UTC, BoBeR182 commented
Can someone push an update to docker hub? https://hub.docker.com/layers/fallenbagel/jellyseerr/preview-pr184/images/sha256-7dda1bf1de3e2df5cb66a7205e0501aaac725c01b2cf160c4bd60ef3c6bb9c78?context=explore

2022-09-25 20:24 UTC, Fallenbagel commented
> Can someone push an update to docker hub? https://hub.docker.com/layers/fallenbagel/jellyseerr/preview-pr184/images/sha256-7dda1bf1de3e2df5cb66a7205e0501aaac725c01b2cf160c4bd60ef3c6bb9c78?context=explore 

Hi will do it tonight in a while c:

2022-09-27 02:09 UTC, w4itey commented
I have a working setup with Keycloak

2022-09-27 16:54 UTC, BoBeR182 commented
Confirming working with Keycloak and Jellyfin to login and authenticate.
Jellyseer users must match keycloak user email, did not test any implementation of RBAC with groups. 
That is fine, since it can be done on Jellyseerr's side.

https://github.com/Fallenbagel/jellyseerr/pull/184/commits/88dfb99a8da5060d6d49f193155599394c3dc8db fixed my bug.

Thank you everyone for the support in testing this.
While I am not a official reviewer, LGTM regardless.

2022-09-27 20:54 UTC, atropos112 commented
I am still having issues with it :/ After pressing the button i get sent to authelias page to "accept" after which i am redirected back to the page and not being logged in. The request headers look like this 
```
GET /api/v1/auth/me HTTP/3
Host: myjellyseerr.xyz
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Referer: https://myjellyseerr.xyz/login?code=RE171kyZahmPqYsqT09Is3_wF0izzs0aO-6e6x4-zoQ.v-I8jCMcBnhVPEFqIVRQYjMSTSTukekk0NKESuKOCFQ&scope=openid+profile+email&state=e299cab2c0314fa5aad20c3e969e35cd
Alt-Used: myjellyseerr.xyz
Connection: keep-alive
Cookie: authelia_cookie=******************; connect.sid=s%3Av8oist9VbnsfS3WrkqOfBfT7xRCMgh9c.U0oy2jjhDtRdzy1AE4MSFWyD6bMmUTkTDCQdhr%2B8fMY
TE: trailers
```
the response is not so satisfactory however :( 

{"status":403,"error":"You do not have permission to access this endpoint"}

2022-10-01 00:10 UTC, Fallenbagel commented
> Not directly. A number of oauth2 / OIDC providers do integrate with LDAP (including authentik) for authentication, but oauth2 is much higher level. Where LDAP acts more like an external users database, an OIDC/oauth provider handles all the sign in and authentication logic. Plex SSO actually uses oauth2 afaik, it just doesn't conform to the OIDC standard. 

How about jellyfin/emby LDAP? Would that work?

2022-10-02 12:52 UTC, ankarhem commented
I closed my original PR, as you might have seen, to implement this in upstream. But I made an updated one which I recently rebased yesterday. You might want to check it out.

https://github.com/sct/overseerr/pull/2792

2022-10-08 20:48 UTC, Fallenbagel commented
> I closed my original PR, as you might have seen, to implement this in upstream. But I made an updated one which I recently rebased yesterday. You might want to check it out.
> 
> https://github.com/sct/overseerr/pull/2792

How would that work with jellyseerr? Would this PR and that PR conflict much? (I'd like to keep feature parity as much as possible with overseerr so)

2022-10-11 18:00 UTC, obsidiangroup commented
> @Fallenbagel resolved the merge conflicts. OIDC is working great for me (using authentik) but would love to have some others test with different OIDC providers.

@michaelhthomas In authentik, did you set the redirect url to http://[host]/login ?

I'm attempting to get this working in Overseerr via @ankarhem's fork, and I'm assuming the code base is similar.

2022-10-11 18:03 UTC, michaelhthomas commented
> > @Fallenbagel resolved the merge conflicts. OIDC is working great for me (using authentik) but would love to have some others test with different OIDC providers.
> 
> @michaelhthomas In authentik, did you set the redirect url to http://[host]/login ?
> 
> I'm attempting to get this working in Overseerr via @ankarhem's fork, and I'm assuming the code base is similar.
> 

Yep, that should work. All the authorization logic happens on the login page after the redirect.

2022-10-12 17:04 UTC, obsidiangroup commented
> Yep, that should work. All the authorization logic happens on the login page after the redirect.

We figured it out -- there was another issue that has been resolved as well.

Since I dont use Jellyseerr, I am not sure how this works here.
If a user has already authenticated, and they then go to jellyseerr, does jellyseerr automatically log them in, or do they have to re-authenticate from within Jellyseerr as well?

How are Logoff's handled?  Do they just log out of jellyseerr, or do they logout there AND from the whatever idp they use?

2022-10-12 17:14 UTC, obsidiangroup commented
> I normally run stable, it said in the corner "Develop" and "Out of date" :/ I am certain its not to do with your changes but it does mean I can't test it until I figure this out, apologies.

If this is like Overseerr, the issue when building locally and deploying is the COMMIT_TAG in the Dockerfile should be set to local.
```
ARG COMMIT_TAG
ENV COMMIT_TAG=${COMMIT_TAG}

RUN yarn build

# remove development dependencies
RUN yarn install --production --ignore-scripts --prefer-offline

RUN rm -rf src server .next/cache

RUN touch config/DOCKER

RUN echo "{\"commitTag\": \"${COMMIT_TAG}\"}" > committag.json
```

After setting COMMIT_TAG=local and rebuilding, this problem was resolved.  Thanks to @ankarhem for that.  There are places in the code that checks the tag and causes that loop.

2022-10-13 04:07 UTC, kassarole commented
![image](https://user-images.githubusercontent.com/19984564/195496739-3a078b4a-2ffb-4b1b-8be6-b8719116886f.png)
I'm testing this with Authentik. I think the above error with the OIDC check is why my auth is failing but I don't see any way to either fix the cert or disable cert verification. Is there something I'm missing?

2022-10-24 04:39 UTC, xan-m commented
Has anyone been able to get this working with Authelia? I'm consistently getting `message: "jwt malformed"` in the response from `/api/v1/auth/oidc` when using Authelia and I can't tell if I messed up the configuration or it's something in the OIDC flow that's causing the issue. If someone's got it running I'd love to take a peek at their Authelia config!

I've taken the `Authentication: Bearer <token>` header after authenticating to Authelia and queried the Authelia `/api/oidc/userinfo` endpoint directly, and I get a JWT back. Plugging that JWT into [https://jwt.io/](https://jwt.io/) shows a good JWT with `name` and `email` in the payload (among many others) and a valid signature. 

If I'm understanding [this code](https://github.com/Fallenbagel/jellyseerr/blob/88ac5af4ec53d020b44f77bf87dee7f4060500e1/server/routes/auth.ts#L529-L534) correctly, that's more or less the same workflow that this PR uses: grab the auth bearer token, grab the `userinfo` endpoint URI from the issuer's `.well-known/openid-configuration`, and then send a GET request to the `userinfo` endpoint using the auth bearer token, and then parse the email and name of the user from the response.

Side note: I haven't been able to get Authentik to work either because Authentik's issuer URI is `https://auth.domain.tld/application/o/<application>/`, and from what I can tell the most recent commit removes the trailing slash from the URI and causes Jellyseerr to look for an issuer of `https://auth.domain.tld/application/o/<application>`, which fails to validate with `message: "jwt issuer invalid. expected: https://domain.tld/application/o/jellyseerr"`

Let me know if there's anything I can help with!

2022-10-25 18:05 UTC, michaelhthomas commented
@xan-m just noticed the trailing slash thing is *still* an issue, I'll see if I can push a fix later today. As for Authelia I'm not really sure as I haven't used it personally, but I'll see if I can do some testing and find out what's up. Thanks for the feedback!

2022-10-25 19:25 UTC, xan-m commented
@michaelhthomas awesome, thank you so much for the speedy reply! Lmk if there’s anything I can provide to help troubleshoot — HAR, logs, etc.

2022-10-26 02:18 UTC, Fallenbagel commented
> @xan-m just noticed the trailing slash thing is *still* an issue, I'll see if I can push a fix later today. As for Authelia I'm not really sure as I haven't used it personally, but I'll see if I can do some testing and find out what's up. Thanks for the feedback!

So the fix that was implemented where the trailing slash was being removed, that's messing up OIDC and thus PR? 

Might need to rethink the trailing slash issue then (or maybe for now revert to the old method of no checks for trailing slash) 🤔

2022-10-26 02:26 UTC, michaelhthomas commented
> So the fix that was implemented where the trailing slash was being removed, that's messing up OIDC and thus PR?
> 
> Might need to rethink the trailing slash issue then as currently if theres any trailing slash, its being removed (@xan-m was this what you mentioned?)

Correct, I just switched it to add trailing slashes if they are not present instead. Hopefully this is a consistent thing (all providers have trailing slashes), since the jwt issuer url has to match exactly with the one provided or verification will fail.

2022-10-26 02:31 UTC, Fallenbagel commented
> Correct, I just switched it to add trailing slashes if they are not present instead. Hopefully this is a consistent thing (all providers have trailing slashes), since the jwt issuer url has to match exactly with the one provided or verification will fail.

Ah. Thanks for the quick fix! I'll update the docker tag as soon as the checks finishes

2022-10-26 02:34 UTC, michaelhthomas commented
@Fallenbagel, just tested again with Keycloak and realized it does not use trailing slashes, so I'm gonna have to do something a bit more creative 😞

2022-10-26 02:37 UTC, Fallenbagel commented
> @Fallenbagel, just tested again with Keycloak and realized it does not use trailing slashes, so I'm gonna have to do something a bit more creative 😞 

As in authelia, authentik etc uses trailing slash but keycloak doesn't?

Also meanwhile, could you also merge in the latest commits from develop? So I can test the non-OIDC aspect of this pr

2022-10-26 02:42 UTC, Fallenbagel commented
> Correct. I can either require that the issuer url that is entered into the settings is exactly correct (has or does not have a trailing slash depending on the provider), or I can require a server restart to change the OIDC issuer, and ask the issuer for the correct url when the server starts. Not a huge fan of either option, so let me know which you'd prefer.

I think the first option would be the least annoying method for the users, don't you think? Because latter would require them to restart server which could become cumbersome

2022-10-26 02:48 UTC, xan-m commented
> As in authelia, authentik etc uses trailing slash but keycloak doesn't?

FWIW I think Authentik is the only one that forces a trailing slash. Authelia does not appear to based on the JWT token I'm looking at right now from my Authelia server

2022-10-26 02:51 UTC, michaelhthomas commented
> FWIW I think Authentik is the only one that forces a trailing slash. Authelia does not appear to based on the JWT token I'm looking at right now from my Authelia server

Gotcha, Authentik can be a bit quirky at times. 

Would you mind sending me your Authelia config (important info redacted) so I have a good starting point to test with?

2022-10-26 03:22 UTC, xan-m commented
For sure!
```
  identity_providers:
    oidc:
      access_token_lifespan: 4h
      authorize_code_lifespan: 1m
      clients:
        - authorization_policy: two_factor
          description: My request server
          id: kellyseer
          pre_configured_consent_duration: 2w
          public: true
          redirect_uris:
            - https://*REDACTED*/login
          scopes:
            - profile
            - email
          userinfo_signing_algorithm: RS256
      cors:
        allowed_origins: ''
        allowed_origins_from_client_redirect_uris: true
        endpoints: []
      enable_client_debug_messages: true
      enable_pkce_plain_challenge: false
      enabled: true
      enforce_pkce: public_clients_only
      id_token_lifespan: 6h
      issuer_certificate_chain: *REDACTED*
      minimum_parameter_entropy: 8
      refresh_token_lifespan: 90m
```
My Authelia is deployed in k8s so some of these settings may not be relevant for a non-k8s deployment (like "enabled"). Let me know if you need anything else!

2022-10-26 04:05 UTC, BoBeR182 commented
In Keycloak navigating to https://keycloak.domain.tld/realms/realm/.well-known/openid-configuration shows that the issuer is expected to not have a trailing slash. 

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata states URL using the https scheme with no query or fragment component that the OP asserts as its Issuer Identifier. 
https://datatracker.ietf.org/doc/html/rfc2396#section-3.3 status that a path can be empty in the case of a issuer with a trailing slash the path is actually == null, while without the slash the path is "realm"

2022-10-26 04:48 UTC, xan-m commented
I'm definitely not an OIDC pro, and I've never touched react/typescript, so I'm definitely out of my league here. Since this PR is only checking authentication, can't we just use the `id_token` to validate that rather than grabbing the `access_token` and using that to query the userinfo endpoint? From what I can tell in the [official OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth), using the `id_token` to confirm authentication should be sufficient.

Another thing I noticed, (again total novice with react so forgive my ignorance here), is that it looks like [here](https://github.com/Fallenbagel/jellyseerr/blob/1c8829aaa12bc8701f14de8cdebc4a70223e6800/src/components/Login/OidcLogin.tsx#L40-L44) the login page is grabbing the `access_token`, and then [passing it to the oidc endpoint here](https://github.com/Fallenbagel/jellyseerr/blob/1c8829aaa12bc8701f14de8cdebc4a70223e6800/server/routes/auth.ts#L522). Does that `checkJwt` function check JWT formatting in the `access_token` value? This would work fine for Authentik, as the `access_token` is valid JWT (and in fact is almost identical to the `id_token` in payload), but for Authelia, the `access_token` value is totally different, and does not pass as valid JWT. Here's an example `access_token` from Authelia: 
![Screenshot_20221025_214246](https://user-images.githubusercontent.com/88455615/197936637-1aa7f482-2f96-45dc-b0ed-41dba969c841.png)
I can use this `access_token` in the `Authorization: Bearer <token>` header of a GET request to the userinfo endpoint and get the actual JWT value for the user, but it won't validate as JWT on its own. Perhaps this is the source of the `Malformed jwt` error message?

2022-10-30 19:02 UTC, michaelhthomas commented
> I'm definitely not an OIDC pro, and I've never touched react/typescript, so I'm definitely out of my league here. Since this PR is only checking authentication, can't we just use the `id_token` to validate that rather than grabbing the `access_token` and using that to query the userinfo endpoint? From what I can tell in the [official OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth), using the `id_token` to confirm authentication should be sufficient.

Unfortunately, the OIDC spec does not require that the `id_token` payload contains any of the scopes (email, preferred name, etc.), so I think the server will still have to query the `userinfo` endpoint for consistency's sake. It can definitely be used to ensure that the user is logged in though, and is actually guaranteed to be formatted as a jwt.

> Another thing I noticed, (again total novice with react so forgive my ignorance here), is that it looks like [here](https://github.com/Fallenbagel/jellyseerr/blob/1c8829aaa12bc8701f14de8cdebc4a70223e6800/src/components/Login/OidcLogin.tsx#L40-L44) the login page is grabbing the `access_token`, and then [passing it to the oidc endpoint here](https://github.com/Fallenbagel/jellyseerr/blob/1c8829aaa12bc8701f14de8cdebc4a70223e6800/server/routes/auth.ts#L522). Does that `checkJwt` function check JWT formatting in the `access_token` value? This would work fine for Authentik, as the `access_token` is valid JWT (and in fact is almost identical to the `id_token` in payload), but for Authelia, the `access_token` value is totally different, and does not pass as valid JWT. Here's an example `access_token` from Authelia: ![Screenshot_20221025_214246](https://user-images.githubusercontent.com/88455615/197936637-1aa7f482-2f96-45dc-b0ed-41dba969c841.png) I can use this `access_token` in the `Authorization: Bearer <token>` header of a GET request to the userinfo endpoint and get the actual JWT value for the user, but it won't validate as JWT on its own. Perhaps this is the source of the `Malformed jwt` error message?

That's almost certainly the case. A lot of the code this PR is based on is Auth0-specific, so that's just something I didn't catch since Authentik and Keycloak both work the same way (non-standard). 

I just pushed some changes which should remove jwt parsing of the `access_token` and only parse the `id_token1, so let me know if you're able to get it working with Authelia now!

2022-10-30 20:48 UTC, xan-m commented
You nailed it! Authelia works great now and Authentik is back up and running with this latest push. Thank you so much for the quick patch, and for taking this task on in the first place!

Note for Authelia users -- if the login flow appears to work but you get a 500 error with `something went wrong`, check that the [userinfo_signing_algorithm](https://www.authelia.com/configuration/identity-providers/open-id-connect/#userinfo_signing_algorithm) setting is set to `none`. If it's set to `RS256` the data at the `userinfo` endpoint is in JWT format instead of JSON.

I think as long as this didn't break Keycloak, we're in good shape! Any chance we can get this pushed out to the `preview-pr184` dockerhub image so I can throw it into prod for a bit and confirm stability?

2022-10-30 22:16 UTC, Fallenbagel commented
> I think as long as this didn't break Keycloak, we're in good shape! Any chance we can get this pushed out to the `preview-pr184` dockerhub image so I can throw it into prod for a bit and confirm stability?

Oh yeah I've been meaning to do it, got a bit busy. Today I'll push it

2022-11-03 15:16 UTC, kassarole commented
Has a new build been pushed to dockerhub yet? Would love to test this more

2022-11-04 17:18 UTC, Fallenbagel commented
> Has a new build been pushed to dockerhub yet? Would love to test this more

New build will be built in about an hour or two depending on github actions

2022-11-04 19:01 UTC, Fallenbagel commented
It's up!

2022-11-04 19:13 UTC, kassarole commented
> ![image](https://user-images.githubusercontent.com/19984564/195496739-3a078b4a-2ffb-4b1b-8be6-b8719116886f.png) I'm testing this with Authentik. I think the above error with the OIDC check is why my auth is failing but I don't see any way to either fix the cert or disable cert verification. Is there something I'm missing?

Still seeing this same error with the new version. Is there anything I'm missing around the cert?

2022-11-04 19:19 UTC, Fallenbagel commented
> > ![image](https://user-images.githubusercontent.com/19984564/195496739-3a078b4a-2ffb-4b1b-8be6-b8719116886f.png) I'm testing this with Authentik. I think the above error with the OIDC check is why my auth is failing but I don't see any way to either fix the cert or disable cert verification. Is there something I'm missing?
> 
> Still seeing this same error with the new version. Is there anything I'm missing around the cert?

@michaelhthomas

2022-11-04 21:17 UTC, BoBeR182 commented
> > ![image](https://user-images.githubusercontent.com/19984564/195496739-3a078b4a-2ffb-4b1b-8be6-b8719116886f.png) I'm testing this with Authentik. I think the above error with the OIDC check is why my auth is failing but I don't see any way to either fix the cert or disable cert verification. Is there something I'm missing?
> 
> Still seeing this same error with the new version. Is there anything I'm missing around the cert?

I don't thing any efforts were made to fix this, as no other troubleshooting information was provided, does your Authentik setup have a TLS cert deployed? Is it signed by let's encrypt or another trusted provider? Is jellyseerr running over TLS? does it have a valid cert?

2022-11-04 22:00 UTC, kassarole commented
> > > ![image](https://user-images.githubusercontent.com/19984564/195496739-3a078b4a-2ffb-4b1b-8be6-b8719116886f.png) I'm testing this with Authentik. I think the above error with the OIDC check is why my auth is failing but I don't see any way to either fix the cert or disable cert verification. Is there something I'm missing?
> > 
> > 
> > Still seeing this same error with the new version. Is there anything I'm missing around the cert?
> 
> I don't thing any efforts were made to fix this, as no other troubleshooting information was provided, does your Authentik setup have a TLS cert deployed? Is it signed by let's encrypt or another trusted provider? Is jellyseerr running over TLS? does it have a valid cert?

Let's Encrypt Certs for both jellyseerr and authentik are currently being provided by my nginx proxy. Can confirm these certs are valid and I am able to use the Authentik setup for OAuth/OIDC on other services on my network

2022-11-05 23:46 UTC, michaelhthomas commented
> > > ![image](https://user-images.githubusercontent.com/19984564/195496739-3a078b4a-2ffb-4b1b-8be6-b8719116886f.png) I'm testing this with Authentik. I think the above error with the OIDC check is why my auth is failing but I don't see any way to either fix the cert or disable cert verification. Is there something I'm missing?
> > 
> > Still seeing this same error with the new version. Is there anything I'm missing around the cert?
> 
> @michaelhthomas 

I'll take a look into this, but authentik is working for me so there's a decent chance it's a configuration issue.

2022-11-05 23:48 UTC, kassarole commented
Entirely fair I'm just not sure why just this service is failing and don't know where to look

2022-11-05 23:51 UTC, xan-m commented
Could have to do with the signing certificate? Authentik worked fine for me too before I decided to go with authelia. 

https://goauthentik.io/docs/core/certificates

2022-11-06 00:59 UTC, kassarole commented
It was cert related. I moved from a wildcard cert to a specific cert and it is working now. Thanks for the help all!

2022-11-08 18:03 UTC, BoBeR182 commented
Has every auth framework been rechecked as working is this needing anything else to merge?

2022-11-09 04:21 UTC, Killerherts commented
This worked great for me thanks for the work guys!

2022-11-14 01:08 UTC, Fallenbagel commented
> Edit:
> One thing that might be nice is a button to hide the tradition email/password login leaving only the oidc button

Isnt this already possible when you untick the local login?

2022-11-14 01:11 UTC, kassarole commented
> > Edit:
> > One thing that might be nice is a button to hide the tradition email/password login leaving only the oidc button
> 
> Isnt this already possible when you untick the local login?

Even if you do that yous till have the Jellyfin/emby login as the default option before you can click your OIDC

![image](https://user-images.githubusercontent.com/19984564/201555553-b787dfee-53e1-418d-97da-c9923d98b0f6.png)

2022-11-14 02:58 UTC, Fallenbagel commented
> Even if you do that you still have the Jellyfin/emby login as the default option before you can click your OIDC
> 
> ![image](https://user-images.githubusercontent.com/19984564/201555553-b787dfee-53e1-418d-97da-c9923d98b0f6.png)

edit: IM SO SORRY I ACCIDENTALLY EDITTED YOUR COMMENT trying to reply to it.

What happens when you turn off `enable new Jellyfin   sign-in`? That was introduced for the sole purpose of disabling the jellyfin/emby login fields when local accounts were turned on. And it does work for that I'm not sure how it does on OIDC so I'm curious

2022-11-14 03:05 UTC, kassarole commented
> > Even if you do that you still have the Jellyfin/emby login as the default option before you can click your OIDC
> > ![image](https://user-images.githubusercontent.com/19984564/201555553-b787dfee-53e1-418d-97da-c9923d98b0f6.png)
> 
> What happens when you turn off `enable new Jellyfin sign-in`? That was introduced for the sole purpose of disabling the jellyfin/emby login fields when local accounts were turned on. And it does work for that (as in when i turn that off and keep local on i only see local sign in) i'm not sure how it does on this OIDC version so I'm genuinely curious
> 
> ![Screenshot_20221114_075925_Chrome](https://user-images.githubusercontent.com/98979876/201566130-22ba3821-19c3-47a6-99af-af83a078d25b.jpg)
> 
> edit: IM SO SORRY I ACCIDENTALLY EDITTED YOUR COMMENT trying to reply to it and deleted some parts accidentally (on mobile) but I have rebuilt the comment from what I remember

No worries at all lol. I have that setting disabled too and the signin is still there
![image](https://user-images.githubusercontent.com/19984564/201566374-86a3ed6e-eeba-4768-98f5-99889b7696b6.png)

2022-11-14 04:04 UTC, Fallenbagel commented
> No worries at all lol. I have that setting disabled too and the signin is still there
> ![image](https://user-images.githubusercontent.com/19984564/201566374-86a3ed6e-eeba-4768-98f5-99889b7696b6.png)

Hmm. That shouldn't be the behavior as this could mean that somewhere along this PR, that feature went through a regression? Like people who don't use OIDC and don't want their users to authenticate through jellyfin and only use local accounts, does that still work for them like it should originally?

@michaelhthomas did you ever test it? If not I'll test tonight

2022-11-14 04:09 UTC, michaelhthomas commented
> > No worries at all lol. I have that setting disabled too and the signin is still there
> > ![image](https://user-images.githubusercontent.com/19984564/201566374-86a3ed6e-eeba-4768-98f5-99889b7696b6.png)
> 
> Hmm. That shouldn't be the behavior as this could mean that somewhere along this PR, that feature went through a regression? Like people who don't use OIDC and don't want their users to authenticate through jellyfin and only use local accounts, does that still work for them like it should originally?
> 
> @michaelhthomas did you ever test it? If not I'll test tonight

I'll check it out right now and see if there's something wrong with how it's implemented.

2022-11-14 22:10 UTC, michaelhthomas commented
@kassarole that should fix it!

2022-11-15 00:54 UTC, Fallenbagel commented
> @kassarole that should fix it!

Nice! I'll update the tag and test it myself for normal accounts and @kassarole would love it if you could test for OIDC. If everything works smoothly it's time for the big merge!

2022-11-15 00:55 UTC, kassarole commented
> > @kassarole that should fix it!
> 
> Nice! I'll update the tag and test it myself for normal accounts and @kassarole would love it if you could test for OIDC. If everything works smoothly it's time for the big merge!

Will do

2022-11-15 01:03 UTC, michaelhthomas commented
The only issue still standing that I can think of is that it is technically possible to disable all forms of authentication by just unchecking app three boxes, but there wasn't any pre-established way that I could find to validate multiple settings like that.

2022-11-15 01:05 UTC, kassarole commented
Even if the user did that they should be able to reenable the auth from the settings.json tho right?

2022-11-15 01:19 UTC, Killerherts commented
> Even if the user did that they should be able to reenable the auth from the settings.json tho right?

It looks like you're correct. ill try it when the tag goes live

2022-11-15 01:21 UTC, Fallenbagel commented
> Even if the user did that they should be able to reenable the auth from the settings.json tho right?

Yeah they should. 

I just tested it by disabling all of them on develop tag. It seems the last enabled form remains. And now that i take a look at it, it seems that option is mostly for new jellyfin users as in if ever imported, they should be able to login even if that option was disabled (not really a jellyfin form hide thing). Wonder if this could affect some users or not.

Should we seperate the field option? Or should we make it so that only when OIDC is turned on can all other forms get hidden?
Or should we just add a small validation later to have atleast one of them enabled if if ends up being a problem?

2022-11-15 01:23 UTC, kassarole commented
I think the best option is just to have validation that you have at least one auth method selected

2022-11-15 03:23 UTC, michaelhthomas commented
> And now that i took a close look at it, it seems that option is mostly for new jellyfin user authentication. Which means if ever imported, they should be able to login even if that option was disabled (not really a jellyfin form hide thing). Wonder if this could affect some users or not.

Yeah I wasn't really clear on what the intended behavior of that setting was. I think for clarity's sake it would be smart to add an option to hide the Jellyfin/Plex login fields, and keep the existing one and clarity that it allows sign-ins just only for those users which have already been imported from Jellyfin/Plex.

> I think the best option is just to have validation that you have at least one auth method selected

Agreed, just not sure if that's something I should try implementing server side or not.

2022-11-15 03:48 UTC, Fallenbagel commented
> Yeah I wasn't really clear on what the intended behavior of that setting was. I think for clarity's sake it would be smart to add an option to hide the Jellyfin/Plex login fields, and keep the existing one and clarity that it allows sign-ins just only for those users which have already been imported from Jellyfin/Plex.

I think this would be the best way. Because I can think of several reasons why someone would still want jellyfin login form yet do not want new users to be able to login unless imported (esp if they wanna set permissions beforehand) so we should probably leave the `new jellyfin sign in` as it was before and add a new option under OIDC for hiding.
 Like you know how request perms has two options? Series or movies? Like that sub option to hide jellyfin form

2022-11-15 04:42 UTC, michaelhthomas commented
![SCR-20221114-wwi](https://user-images.githubusercontent.com/18223295/201828039-2f567f8b-511e-452e-8ec9-ca85d1e3ed59.png)
@Fallenbagel How's this look?

2022-11-15 04:46 UTC, Fallenbagel commented
> ![SCR-20221114-wwi](https://user-images.githubusercontent.com/18223295/201828039-2f567f8b-511e-452e-8ec9-ca85d1e3ed59.png)
> @Fallenbagel How's this look?

Perfect! Much better than what I initially imagined.

Although maybe move the `new jellyfin user` option to right below login methods as majority will use jellyfin auth instead of OIDC so that option is easier for them to see

2022-11-15 05:01 UTC, michaelhthomas commented
> Although maybe move the `new jellyfin sign in` option to right below login methods which is right above `oidc issuer url` as majority will use jellyfin auth instead of OIDC so that option is easier for them to see OR we could let the oidc fields appear when oidc sign in is enabled?

The OIDC fields do currently only show when oidc sign in is enabled, so i'm not sure whether to keep `new jellyfin sign in` where it is or move it up above the other OIDC fields.

2022-11-15 05:02 UTC, michaelhthomas commented
![SCR-20221115-1i](https://user-images.githubusercontent.com/18223295/201830607-6298c536-4629-43e0-839a-d5352274ac32.png)
Here's how it looks the other way.

2022-11-15 06:30 UTC, Fallenbagel commented
> > Although maybe move the `new jellyfin sign in` option to right below login methods which is right above `oidc issuer url` as majority will use jellyfin auth instead of OIDC so that option is easier for them to see OR we could let the oidc fields appear when oidc sign in is enabled?
> 
> The OIDC fields do currently only show when oidc sign in is enabled, so i'm not sure whether to keep `new jellyfin sign in` where it is or move it up above the other OIDC fields.
> 
> ![SCR-20221115-1i](https://user-images.githubusercontent.com/18223295/201830607-6298c536-4629-43e0-839a-d5352274ac32.png) Here's how it looks the other way.

Oh then keep as it was. Without moving. It looks odd when it's moved up. Sorry I forgot I remember OIDC fields appearing after I turned them on when I was testing 2 months ago

2022-11-16 05:53 UTC, Fallenbagel commented
Seems it fails to build

2022-11-16 19:10 UTC, w4itey commented
@michaelhthomas getting an error "Jellyseerr has been updated! Please click the button below to reload the page." pops up every time i reload

2022-11-16 19:48 UTC, michaelhthomas commented
> @michaelhthomas getting an error "Jellyseerr has been updated! Please click the button below to reload the page." pops up every time i reload

Try clearing your browser cache

2022-11-18 00:31 UTC, Fallenbagel commented
> @michaelhthomas getting an error "Jellyseerr has been updated! Please click the button below to reload the page." pops up every time i reload

Preview tag has been updated. Try re-pulling the image and see if it works

2022-11-18 00:35 UTC, kassarole commented
Just pulled the new version and auth looks great. Only have the one option for my OIDC now

2022-11-18 01:12 UTC, Fallenbagel commented
> Just pulled the new version and auth looks great. Only have the one option for my OIDC now

Thanks for the tests! I'll hopefully merge this pr this coming weekend c:

2022-11-18 14:47 UTC, Killerherts commented
> Hey, really interested by this PR!
> 
> I'm trying to get it working with Authentik but I am getting the following error after being redirected to Jellyserr: "Something went wrong while trying to sign in."
> 
> I also get a 401 error for `/api/v1/auth/oidc` with the following message
> ```json
> {"message":"secret or public key must be provided"}
> ```
> And some 403 errors for `/api/v1/auth/me `
> 
> Any ideas why?

Need to a be a public end point it's not set up for confidential. So you must fill out the authorized redirect otherwise they can auth from anywhere

2022-11-18 15:11 UTC, michaelhthomas commented
> > I closed my original PR, as you might have seen, to implement this in upstream. But I made an updated one which I recently rebased yesterday. You might want to check it out.
> > [sct/overseerr#2792](https://github.com/sct/overseerr/pull/2792)
> 
> How would that work with jellyseerr? Would this PR and that PR conflict much? (I'd like to keep feature parity as much as possible with overseerr so)

@Fallenbagel i just took a look at this PR and it seems pretty similar and is done a little bit more properly than this IMO. Do you think it would be worth trying to bring this PR closer to that one upstream for feature parity / ease of merging purposes?

2022-11-18 20:14 UTC, Fallenbagel commented
> @Fallenbagel i just took a look at this PR and it seems pretty similar and is done a little bit more properly than this IMO. Do you think it would be worth trying to bring this PR closer to that one upstream for feature parity / ease of merging purposes? It's pretty late to make such a change, but I know it could be potentially very frustrating to try and manage the changes between this PR and the upstream one. 

Yeah down the line it's gonna be very frustrating if this PR and that PR conflicts. I would like to keep feature parity with upstream so if you could, that would be much more appreciated

2022-11-18 21:10 UTC, deltabweb commented
> Need to a be a public end point it's not set up for confidential. So you must fill out the authorized redirect otherwise they can auth from anywhere

This is my Authentik config, anything looks wrong to you?

![image](https://user-images.githubusercontent.com/20023887/202802894-c33d2236-d31e-4a4c-9f7b-abbfb1a5e016.png)

2022-11-18 21:49 UTC, Killerherts commented
> > Need to a be a public end point it's not set up for confidential. So you must fill out the authorized redirect otherwise they can auth from anywhere
> 
> This is my Authentik config, anything looks wrong to you?
> 
> ![image](https://user-images.githubusercontent.com/20023887/202802894-c33d2236-d31e-4a4c-9f7b-abbfb1a5e016.png)
> 
> EDIT: OK nervermind, I had to pick a value for `Signing key`, it's working now, thanks
> 

If I remember or someone has time a screenshot of both a authentik and authelia settings might go a long way for people.

2022-11-19 01:42 UTC, deltabweb commented
@Killerherts here are some screenshots of my working config, feel free to use them for documentation purposes

Provider in Authentik:
![image](https://user-images.githubusercontent.com/20023887/202828024-282b081e-1f62-4db5-a825-c628c9c44998.png)

Application in Authentik:
![image](https://user-images.githubusercontent.com/20023887/202828064-d07c6850-aee2-48f0-ac41-3ac779c473a8.png)

Configuration in Jellyseerr:
![image](https://user-images.githubusercontent.com/20023887/202828137-a8621ac2-e4f6-4dda-a9a1-7d73d486d5da.png)

2022-11-26 03:50 UTC, Fallenbagel commented
> @Fallenbagel i just took a look at this PR and it seems pretty similar and is done a little bit more properly than this IMO. Do you think it would be worth trying to bring this PR closer to that one upstream for feature parity / ease of merging purposes? It's pretty late to make such a change, but I know it could be potentially very frustrating to try and manage the changes between this PR and the upstream one. 

Was wondering whether we should hold on from merging until this PR is closer to upstream one just so as to not create any issues down the line. What so you think? @michaelhthomas

2022-11-27 04:56 UTC, ados8 commented
Sadly I have attempted about 20 different combinations for Jellyseerr + Authentik including above and cannot it working.
Usually the path for `OIDC Issuer URL` would be `https://auth.domain.com/application/o/jellyseerr/.well-known/openid-configuration` but that causes the button to do nothing.
Using `https://auth.domain.com/application/o/jellyseerr/` results in redirect error
![image](https://user-images.githubusercontent.com/49982433/204119886-24ff11a4-1d6f-4302-bcbd-1e1852744096.png)
I have other services using OpenID to Authentik without issue.

2022-11-27 06:15 UTC, deltabweb commented
I reckon `https://auth.domain.com/application/o/jellyseerr/` is the one you want, the well-known path should be added by the code.

What value do you have for the Redirect URIs field in Authentik? (first screenshot I posted)
It needs to point to your Jellyseerr instance. Also I think Authentik has changed some of the regex logic in the latest version so could be related to that.

2022-11-27 19:26 UTC, michaelhthomas commented
> Sadly I have attempted about 20 different combinations for Jellyseerr + Authentik including above and cannot it working.
> Usually the path for `OIDC Issuer URL` would be `https://auth.domain.com/application/o/jellyseerr/.well-known/openid-configuration` but that causes the button to do nothing.
> Using `https://auth.domain.com/application/o/jellyseerr/` results in redirect error
> ![image](https://user-images.githubusercontent.com/49982433/204119886-24ff11a4-1d6f-4302-bcbd-1e1852744096.png)
> I have other services using OpenID to Authentik without issue.

Make sure your "Application URL" is set in the general settings.

2022-11-28 02:51 UTC, ados8 commented
> > Sadly I have attempted about 20 different combinations for Jellyseerr + Authentik including above and cannot it working.
> > Usually the path for `OIDC Issuer URL` would be `https://auth.domain.com/application/o/jellyseerr/.well-known/openid-configuration` but that causes the button to do nothing.
> > Using `https://auth.domain.com/application/o/jellyseerr/` results in redirect error
> > ![image](https://user-images.githubusercontent.com/49982433/204119886-24ff11a4-1d6f-4302-bcbd-1e1852744096.png)
> > I have other services using OpenID to Authentik without issue.
> 
> Make sure your "Application URL" is set in the general settings.

Thank you, in one of my many setting tweaks I had left this empty again.
Setting this does now put me back to where I have been before, around we go again 😋
![image](https://user-images.githubusercontent.com/49982433/204180605-d98c21bb-5c2a-48af-9576-41cd1eb6362d.png)
Log show that each time I try to sign in its the same log in Jellyseerr
![image](https://user-images.githubusercontent.com/49982433/204180740-e0f8aeab-7466-4f9a-9cfa-12a6ca85b237.png)
The Authentik logs show its making the connection, I'm at a loss

2022-11-29 20:44 UTC, michaelhthomas commented
Just updated this PR to use the same server-side logic and endpoints and the upstream one. If everyone who has already tested would test again and provide feedback that would be great!

2022-11-29 22:37 UTC, enticedwanderer commented
I can confirm that the latest image works great with Authentik!

For my domain `home.lan`, on `authentik` side I had:

* Confidential app/OIDC provider with following callbacks allowed:
  * https://jellyseerr.home.lan/login
  * https://jellyseerr.home.lan/api/v1/auth/oidc-callback
* On Jellyseerr side, enabled OIDC with issuer URL: `https://authentik.home.lan/application/o/jellyseerr/`

Note that this works also with a locally issued root CA via ACME in traefik, after patching the container to trust the root CA and thus the authentik endpoint.

I've confirmed it works for the following use cases:

1. OIDC login via account that doesn't exist (it is created as a regular user)
2. OIDC login for an existing account (correctly recognized)
3. Fallback login via jellyfin account already imported (working)
4. Fallback login via internal jellyseerr account (also working)

The only thing of minor note is that, for me, pre-existing local users were created with usernames (and not actual emails, i.e. no @home.lan) while Authentik provided actual email entries in the OIDC claim. So I had to edit users to match the email field to what OIDC provided in order to not get a new user created.

Thank you for iterating on this, its a great addition!

2022-11-30 03:38 UTC, Killerherts commented
> > > @Fallenbagel Please update the preview image whenever you have a chance, thanks!
> > 
> > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> 
> This may be related to the formatting issue but I am not able to log in via authentik with the new version. I also had to reconfigure my oidc settings. Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page

Ditto this also broke my install my odic button just redirects to about blank now

2022-11-30 03:45 UTC, kassarole commented
> > > > @Fallenbagel Please update the preview image whenever you have a chance, thanks!
> > > 
> > > 
> > > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> > 
> > 
> > This may be related to the formatting issue but I am not able to log in via authentik with the new version. I also had to reconfigure my oidc settings. Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> 
> Ditto this also broke my install my odic button just redirects to about blank now

Yeah I was getting a blank screen at first. Luckily I had a logged in session to be able to reconfigure my oidc settings/enable local auth again. You hsould be able to edit the config file and see if you're having the same issue

2022-11-30 03:51 UTC, michaelhthomas commented
> > > > @Fallenbagel Please update the preview image whenever you have a chance, thanks!
> > > 
> > > 
> > > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> > 
> > 
> > This may be related to the formatting issue but I am not able to log in via authentik with the new version. I also had to reconfigure my oidc settings. Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> 
> Ditto this also broke my install my odic button just redirects to about blank now

You may need to clear your browser cache, is about:blank opening in a popup or replacing the same page?

2022-11-30 03:55 UTC, michaelhthomas commented
> I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?

@Fallenbagel prettier runs fine on my machine, and it looks like it errored on `README.md` for some reason... would you mind running that check again just to make sure it wasn't a weird fluke?

2022-11-30 04:16 UTC, Killerherts commented
> > > > > @Fallenbagel Please update the preview image whenever you have a chance, thanks!
> > > > 
> > > > 
> > > > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> > > 
> > > 
> > > This may be related to the formatting issue but I am not able to log in via authentik with the new version. I also had to reconfigure my oidc settings. Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> > 
> > 
> > Ditto this also broke my install my odic button just redirects to about blank now
> 
> You may need to clear your browser cache, is about:blank opening in a popup or replacing the same page?

I had already cleared browser history as I thought the same. The about:blank is a pop-up I also lost the label for the odic button I am on mobile so I haven't tore into the config per kass's instructions

2022-11-30 04:17 UTC, Fallenbagel commented
> > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> 
> @Fallenbagel prettier runs fine on my machine, and it looks like it errored on `README.md` in CI for some reason... would you mind running that check again just to make sure it wasn't a weird fluke?

Ran it about 4 times. Formatting check fails

2022-11-30 04:17 UTC, kassarole commented
> > > > > > @Fallenbagel Please update the preview image whenever you have a chance, thanks!
> > > > > 
> > > > > 
> > > > > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> > > > 
> > > > 
> > > > This may be related to the formatting issue but I am not able to log in via authentik with the new version. I also had to reconfigure my oidc settings. Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> > > 
> > > 
> > > Ditto this also broke my install my odic button just redirects to about blank now
> > 
> > 
> > You may need to clear your browser cache, is about:blank opening in a popup or replacing the same page?
> 
> I had already cleared browser history as I thought the same. The about:blank is a pop-up I also lost the label for the odic button I am on mobile so I haven't tore into the config per kass's instructions

Yeah it sounds like you're in the same spot I was where the oidc config got dropped. I also had the custom label drop off

2022-11-30 05:09 UTC, michaelhthomas commented
> > > I have updated the preview image and its live now but it seems there is a formatting issue. Could you fix that whenever you have the chance?
> > 
> > 
> > @Fallenbagel prettier runs fine on my machine, and it looks like it errored on `README.md` in CI for some reason... would you mind running that check again just to make sure it wasn't a weird fluke?
> 
> Ran it about 4 times. Formatting check fails

Ok weird yeah I've got no clue why. I'll check to see if there's any reason why it could be failing on the README

2022-11-30 05:11 UTC, Fallenbagel commented
> Ok weird yeah I've got no clue why. I'll check to see if there's any reason why it could be failing on the README

Okay thanks. I remember fixing an issue like this previously too, but I cant check before 4th december (uni)

2022-11-30 05:12 UTC, michaelhthomas commented
> > You may need to clear your browser cache, is about:blank opening in a popup or replacing the same page?
> 
> I had already cleared browser history as I thought the same. The about:blank is a pop-up I also lost the label for the odic button I am on mobile so I haven't tore into the config per kass's instructions

The setting for the button label changed names, so you'll have to reconfigure that. Have you been able to log in and change your OIDC settings / add the client secret, or have you not changed the settings yet?

2022-11-30 05:14 UTC, kassarole commented
> Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page

I have the settings fixed on my end but I just get a login loop now

2022-11-30 05:31 UTC, Killerherts commented
> > Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> 
> I have the settings fixed on my end but I just get a login loop now

I was in the same spot mine turned out to be the issuer url before i just had the base domain like ```https://jelly.domain.xyz```
i changed it to "https://jellydomain.xyz/application/o/APPLICATIONNAME/"

2022-11-30 05:38 UTC, kassarole commented
> > > Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> > 
> > 
> > I have the settings fixed on my end but I just get a login loop now
> 
> I was in the same spot mine turned out to be the issuer url before i just had the base domain like `https://jelly.domain.xyz` i changed it to "https://jellydomain.xyz/application/o/APPLICATIONNAME/"
> 
> Is there a uri we can use as the launch url so it will just automatically sign them in directly if they click the link on authentik's application page? It would be nice just to drop them into the main page without needing them to click the button

Just checked and my oidc config looks fine but I'm still getting redirected back to the jellyseer sign in instead of being logged in. I tried clearing cache as well with no change

2022-11-30 05:40 UTC, Killerherts commented
> > > > Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> > > 
> > > 
> > > I have the settings fixed on my end but I just get a login loop now
> > 
> > 
> > I was in the same spot mine turned out to be the issuer url before i just had the base domain like `https://jelly.domain.xyz` i changed it to "https://jellydomain.xyz/application/o/APPLICATIONNAME/"
> > Is there a uri we can use as the launch url so it will just automatically sign them in directly if they click the link on authentik's application page? It would be nice just to drop them into the main page without needing them to click the button
> 
> Just checked and my oidc config looks fine but I'm still getting redirected back to the jellyseer sign in instead of being logged in. I tried clearing cache as well with no change

I also had to change my Redirect URIs for my provider to https://jellyseer.domain.xyz/api/v1/auth/oidc-callback

2022-11-30 05:41 UTC, kassarole commented
> > > > > Currently when I try to log in I get the popup as expected and am able to log into my authentik server but then instead of redirecting that auth and signing me in I am redirected back to the main jellyseer login page
> > > > 
> > > > 
> > > > I have the settings fixed on my end but I just get a login loop now
> > > 
> > > 
> > > I was in the same spot mine turned out to be the issuer url before i just had the base domain like `https://jelly.domain.xyz` i changed it to "https://jellydomain.xyz/application/o/APPLICATIONNAME/"
> > > Is there a uri we can use as the launch url so it will just automatically sign them in directly if they click the link on authentik's application page? It would be nice just to drop them into the main page without needing them to click the button
> > 
> > 
> > Just checked and my oidc config looks fine but I'm still getting redirected back to the jellyseer sign in instead of being logged in. I tried clearing cache as well with no change
> 
> I also had to change my Redirect URIs for my provider to https://jellyseer.domain.xyz/api/v1/auth/oidc-callback

Yup that's updated too

2022-11-30 05:45 UTC, Killerherts commented
> Yup that's updated too
ok last one I can think of that I changed was 
```  "oidcIssuer": "",
  "oidcProviderName": ""```
before I had
```  "oidcIssuer": "https://domain.xyz/application/o/jellyseerr/",
  "oidcProviderName": "Authentik"

2022-11-30 05:51 UTC, enticedwanderer commented
My (working) config has:

```json
{
  ...,
  "localLogin": false,
  "mediaServerLogin": false,
  "newPlexLogin": true,
  "oidcLogin": true,
  "oidcName": "Authentik",
  "oidcClientId": "...",
  "oidcClientSecret": "...",
  "oidcDomain": "https://authentik.home.lan/application/o/jellyseerr/",
  ...
}
```

Notice the change on key naming.
You may also want to just remove all the keys related to OIDC, and reset them from within the app after turning on `localLogin` on.

2022-11-30 05:51 UTC, kassarole commented
> > Yup that's updated too
> 
> ok last one I can think of that I changed was ` "oidcIssuer": "",` ` "oidcProviderName": ""`
> 
> before I had
> 
> ` "oidcIssuer": "https://domain.xyz/application/o/jellyseerr/",` ` "oidcProviderName": "Authentik"`
> 
> I believe these vars he changed to match the upstream so they are extra in our config as they are a legacy from the old version

![image](https://user-images.githubusercontent.com/19984564/204717896-c8ae0f64-8e9d-406e-a3ad-b738e4744b5e.png)
![image](https://user-images.githubusercontent.com/19984564/204718138-8d624476-7228-4ef0-8c72-1369011fcf02.png)

This is what I currently have for settings

2022-11-30 05:53 UTC, Killerherts commented
> > > Yup that's updated too
> > 
> > 
> > ok last one I can think of that I changed was ` "oidcIssuer": "",` ` "oidcProviderName": ""`
> > before I had
> > ` "oidcIssuer": "https://domain.xyz/application/o/jellyseerr/",` ` "oidcProviderName": "Authentik"`
> > I believe these vars he changed to match the upstream so they are extra in our config as they are a legacy from the old version
> 
> ![image](https://user-images.githubusercontent.com/19984564/204717896-c8ae0f64-8e9d-406e-a3ad-b738e4744b5e.png) ![image](https://user-images.githubusercontent.com/19984564/204718138-8d624476-7228-4ef0-8c72-1369011fcf02.png)
> 
> This is what I currently have for settings

They won't show in the settings panel as the labels changed you have got to remove the old odic label through the text editor as they are not reverence in the new update.

2022-11-30 06:05 UTC, kassarole commented
Okay I took a deeper look into logs around my sign in. Looks like I'm getting an invalid jwt error when I try to use oidc after the update

2022-11-30 08:22 UTC, ados8 commented
Very much appreciate the update, works immediately with Authentik.
I believe the OpenID public method was causing some issues and either way it's now more secure.

Regarding the OpenID scopes mapped to Jellyseer can we either keep username mapping or give users the option to map via another scope; I see some want to use email.
However, for people like myself using LDAP as Authentik backend I would like to continue mapping against the user account.

2022-12-02 16:18 UTC, kassarole commented
> > > Yup that's updated too
> > 
> > 
> > ok last one I can think of that I changed was ` "oidcIssuer": "",` ` "oidcProviderName": ""`
> > before I had
> > ` "oidcIssuer": "https://domain.xyz/application/o/jellyseerr/",` ` "oidcProviderName": "Authentik"`
> > I believe these vars he changed to match the upstream so they are extra in our config as they are a legacy from the old version
> 
> ![image](https://user-images.githubusercontent.com/19984564/204717896-c8ae0f64-8e9d-406e-a3ad-b738e4744b5e.png) ![image](https://user-images.githubusercontent.com/19984564/204718138-8d624476-7228-4ef0-8c72-1369011fcf02.png)
> 
> This is what I currently have for settings

Does anyone have this working with authentik where I can compare settings? As it stands it looks like Jellyseer can communicate properly to my authentik instance but when the auth is passed back I am getting an invalid jwt error and am returned to the login screen. Not sure what would have changed to make my jwt invalid since it was working without issue previously

2022-12-02 22:05 UTC, ados8 commented
> > > > Yup that's updated too
> > > 
> > > 
> > > ok last one I can think of that I changed was ` "oidcIssuer": "",` ` "oidcProviderName": ""`
> > > before I had
> > > ` "oidcIssuer": "https://domain.xyz/application/o/jellyseerr/",` ` "oidcProviderName": "Authentik"`
> > > I believe these vars he changed to match the upstream so they are extra in our config as they are a legacy from the old version
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19984564/204717896-c8ae0f64-8e9d-406e-a3ad-b738e4744b5e.png) ![image](https://user-images.githubusercontent.com/19984564/204718138-8d624476-7228-4ef0-8c72-1369011fcf02.png)
> > This is what I currently have for settings
> 
> Does anyone have this working with authentik where I can compare settings? As it stands it looks like Jellyseer can communicate properly to my authentik instance but when the auth is passed back I am getting an invalid jwt error and am returned to the login screen. Not sure what would have changed to make my jwt invalid since it was working without issue previously

Since the information is fragmented above and users are struggling with Authentik, here are the settings.
`Jellyseerr:`
Application URL - https://app.domain.com (you cannot use subfolders, i.e. https://domain.com/app)
Enable Proxy Support - ticked (without this you cannot login if the user doesn't exist, OpenID makes new users local)
Enable Emby Sign-In
Enable OIDC Sign-In - ticked
OIDC Issuer URL - https://auth.domain.com/application/o/jellyseerr/
OIDC Provider Name - whatever you want
OIDC Client ID - from Authentik
OIDC Client Secret - from Authentik

`Authentik:`
Client type - confidential
Client ID - auto generated
Client Secret - auto generated
Redirect URIs/Origins (RegEx) - https://app.domain.com/api/v1/auth/oidc-callback
Signing Key - no set (this is for no proxy users or in cases of client type set public)
*you can adjust the subject mode which binds the login identifier to a value i.e. username but it's not working for me

`NMP/NGINX:`
Users using proxy will need to ensure their settings are slightly modified from the Authentik default for sub domain
In the sub-domain config change location `/` to location `/login`
Without that change, Authentik will loop as Jellyseer lands on https://app.domain.com/login but once authenticated its redirect page is https://app.domain.com/ and will trigger another auth from Authentik, the double pass breaks the login.
Changing the root level location won't cause issues at least from my testing and everything works.

Hope this helps. 😎

2022-12-03 11:35 UTC, Fallenbagel commented
> Ok weird yeah I've got no clue why. I'll check to see if there's any reason why it could be failing on the README

It was a missing new line. I have pushed the fix (hope you don't mind)

2022-12-06 06:12 UTC, Fallenbagel commented
Any issues/fixes needed for this pr? I'm preparing to merge this in asap

2022-12-06 13:41 UTC, kassarole commented
> Any issues/fixes needed for this pr? I'm preparing to merge this in asap

I'm still having the same login issues I reported before. Unlike the NPM stuff that ados mentioned I am not looping the authentik part of the sign in. After I sign into authentik my auth is passed back to jellyseer but instead of getting signed in I am just getting the jellyseer login page again. Checking the logs gives me an invalid jwt error but I don't know what would have changed with this latest update to now make the jwt invalid when it previously worked great

2022-12-06 21:27 UTC, ados8 commented
> Any issues/fixes needed for this pr? I'm preparing to merge this in asap

Can we please have the aforementioned sign in binding fixed? I'm using LDAP and really need Jellyseerr to pass the correct login binding. Currently everything results in email address as the username which then doesn't match across my services.



> > Any issues/fixes needed for this pr? I'm preparing to merge this in asap
> 
> I'm still having the same login issues I reported before. Unlike the NPM stuff that ados mentioned I am not looping the authentik part of the sign in. After I sign into authentik my auth is passed back to jellyseer but instead of getting signed in I am just getting the jellyseer login page again. Checking the logs gives me an invalid jwt error but I don't know what would have changed with this latest update to now make the jwt invalid when it previously worked great

Please run through your settings and check against the verified settings I have to see if it resolves your issue.

2022-12-07 02:56 UTC, kassarole commented
> 
> Please run through your settings and check against the verified settings I have to see if it resolves your issue.

I did check this and I posted my own settings here. They appear to match what you specify in your post

2022-12-07 16:43 UTC, michaelhthomas commented
> Any issues/fixes needed for this pr? I'm preparing to merge this in asap

If someone could test and make sure all the setup and things are still working with Plex that would be excellent.

2022-12-07 18:47 UTC, kassarole commented
> > > Please run through your settings and check against the verified settings I have to see if it resolves your issue.
> > 
> > 
> > I did check this and I posted my own settings here. They appear to match what you specify in your post
> 
> I would recommend bypassing any proxy you have. Point the sub domain direct to your instance for testing. If your using NGINX I can assist but outside of that I have no expertise.

No change. I still log in fine with authentik and am then redirected back to the Jellyseer sign in page with the logs saying jwt error. Did something change with how JWT's are validated in the latest patch?

2022-12-08 16:03 UTC, Killerherts commented
> > > > Please run through your settings and check against the verified settings I have to see if it resolves your issue.
> > > 
> > > 
> > > I did check this and I posted my own settings here. They appear to match what you specify in your post
> > 
> > 
> > I would recommend bypassing any proxy you have. Point the sub domain direct to your instance for testing. If your using NGINX I can assist but outside of that I have no expertise.
> 
> No change. I still log in fine with authentik and am then redirected back to the Jellyseer sign in page with the logs saying jwt error. Did something change with how JWT's are validated in the latest patch?

Doesn't look like anything changed, it has something to do with your config I have successfully rolled it on 4 VMS with authentik

2022-12-10 06:38 UTC, BoBeR182 commented
Has anyone confirmed the other providers Keycloak or Authelia?

2022-12-11 00:48 UTC, xan-m commented
Just tried with Authelia, and it's so close to working... Authelia offers a "scope" query parameter in its callback to jellyseerr, which is causing the following error when the auth flow is handed back to the jellyseerr side: 
`{"message":"Unknown query parameter 'scope'","errors":[{"path":".query.scope","message":"Unknown query parameter 'scope'"}]}`
Looks like editing the request to delete the scope query parameter works and returns a 200, but I can't actually edit the URL in the pop-up window, so I think auth is broken for me now.

2022-12-11 01:01 UTC, ados8 commented
> Just tried with Authelia, and it's so close to working... Authelia offers a "scope" query parameter in its callback to jellyseerr, which is causing the following error when the auth flow is handed back to the jellyseerr side: `{"message":"Unknown query parameter 'scope'","errors":[{"path":".query.scope","message":"Unknown query parameter 'scope'"}]}` Looks like editing the request to delete the scope query parameter works and returns a 200, but I can't actually edit the URL in the pop-up window, so I think auth is broken for me now.
> 
> edit: here's the callback queries after authenticating with Authelia: `?code=authelia_ac_<redacted>&scope=openid+profile+email&state=<redacted>`

Sounds like you need to tweak the scope value.
This is the issue I'm having with Authentik whereby Jellyseerr doesn't interpret any scope except email.
Authelia might not be authenticating when Jellyseerr is using the email binding. Ideally username needs to be default with the ability to have a different scope binding.

2022-12-13 02:37 UTC, michaelhthomas commented
> Just tried with Authelia, and it's so close to working... Authelia offers a "scope" query parameter in its callback to jellyseerr, which is causing the following error when the auth flow is handed back to the jellyseerr side: `{"message":"Unknown query parameter 'scope'","errors":[{"path":".query.scope","message":"Unknown query parameter 'scope'"}]}` Looks like editing the request to delete the scope query parameter works and returns a 200, but I can't actually edit the URL in the pop-up window, so I think auth is broken for me now.
> 
> edit: here's the callback queries after authenticating with Authelia: `?code=authelia_ac_<redacted>&scope=openid+profile+email&state=<redacted>`

About to push fixes for this and several other issues, this is also an issue for Keycloak which includes a session_state value for some reason.

2022-12-13 15:32 UTC, michaelhthomas commented
Just pushed a number of fixes to make this more reliable and a bit more user friendly in the case of errors. @Fallenbagel if you could get a new image built that would be great!

For those who are testing, the correct redirect URL has changed (again) and is now `/login/oidc/callback`. Let me know if you have any issues or feedback!

@ankarhem I've made some fixes on the server side in 4c4168c6ca8dc7e978490449cbccc425c2d5c21d and 48041f80ac4669f08cf007792e75e76c89788287 that should probably be replicated in the PR upstream. I'll try to justify some of the changes I made here so we're on the same page. 4c4168c6ca8dc7e978490449cbccc425c2d5c21d fixes issues with Keycloak and Authelia where additional parameters apart from `state` and `code` are sent to the OIDC callback endpoint, and `express-openapi-validator` automatically blocks these requests since they have unknown parameters. 48041f80ac4669f08cf007792e75e76c89788287 merges data from the `userinfo` endpoint into the ID token data to ensure all claims are present (a best practice since [claims are not guaranteed to be included in the ID token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)), uses the user's preferred name as their display name rather than their email, and also makes the OIDC callback endpoint return proper REST responses with error messages (see be7efa33294e786e943191560de602eb21221236 for how this is used on the client side). Please let me know if you'd be willing to replicate some of these changes upstream as well as if you have any suggestions for changes, I'd like to avoid server-side code/functionality differences between these two PRs as much as we can!

2022-12-13 17:56 UTC, Fallenbagel commented
> Just pushed a number of fixes to make this more reliable and a bit more user friendly in the case of errors. @Fallenbagel if you could get a new image built that would be great!

The tags been updated

2022-12-13 18:53 UTC, kassarole commented
Thanks @michaelhthomas for the updated error handling I was finally able to track down what was going on. The recent update required that user emails be valid. I resolved this on my end and I have SSO working again

2022-12-14 00:06 UTC, xan-m commented
I'm getting a different error now -- 
```
Validation failed: aud must be a `string` type, but the final value was: `[ "\"<redacted>\"", "\"<redacted>\"" ]`..
```
The final value appearing in quotes is the correct client ID value, but there seems to be quotes added in somewhere along the way. Neither my Authelia nor my Jellyseerr configs have quotes around the client ID setting (which I'm assuming maps to "aud" in this case based on the error).

Unfortunately, now that auth is pushed to a pop-up window that automatically closes, it's difficult to capture the HTTPS traffic for further analysis. LMK if the error is enough to work with, and if not I'll keep trying to capture the traffic.

2022-12-14 03:24 UTC, michaelhthomas commented
> I'm getting a different error now --
> 
> ```
> Validation failed: aud must be a `string` type, but the final value was: `[ "\"<redacted>\"", "\"<redacted>\"" ]`..
> ```
> 
> The final value appearing in quotes is the correct client ID value, but there seems to be quotes added in somewhere along the way. Neither my Authelia nor my Jellyseerr configs have quotes around the client ID setting (which I'm assuming maps to "aud" in this case based on the error).
> 
> Unfortunately, now that auth is pushed to a pop-up window that automatically closes, it's difficult to capture the HTTPS traffic for further analysis. LMK if the error is enough to work with, and if not I'll keep trying to capture the traffic.

@xan-m Check the logs, there should be a line containing the error message "Invalid jwt or missing claims" and a copy of the ID token associated with the request. Validate [here](https://jwt.io/) but I think there's a good chance that your `aud` claim is actually an array with the client ID and something else. This is a totally normal case for OIDC so it's definitely just a bug in this implementation's validation.

2022-12-14 14:15 UTC, xan-m commented
@michaelhthomas yep, that’s it! The “aud” value in the jwt is an array with a single value.

2022-12-15 08:53 UTC, ados8 commented
Tested the new build with Authentik using new redirect `/login/oidc/callback`.
Everything continues to work except the subject mode via scope values.
When signing in using OpenID the username is FQDN, i.e. email address as local user.
This means that the user account primary identifier doesn't match LDAP or Emby.
This also means that if the user logs in with Emby the have 2 accounts in the system and double their request limit.
We need the default scope binding to username to match LDAP and/or Emby and have the ability to change for admins require it.

2022-12-16 02:35 UTC, michaelhthomas commented
> Tested the new build with Authentik using new redirect `/login/oidc/callback`. Everything continues to work except the subject mode via scope values. When signing in using OpenID the username is FQDN, i.e. email address as local user. This means that the user account primary identifier doesn't match LDAP or Emby. This also means that if the user logs in with Emby the have 2 accounts in the system and double their request limit. We need the default scope binding to username to match LDAP and/or Emby and have the ability to change for admins require it.

Just to be clear, the username (which confusingly is actually called "Display Name" in the user settings) is now set to the user's "name" provided by OIDC, meaning the display name matches between Jellyseer and the auth provider. However, the user matching code only looks up accounts by email address, since that's pretty much the only universal identifier for users in jellyfin. Sounds like you'd like the code to also check the user's `preferred_username` OIDC claim and compare that to Plex/Jellyfin usernames, is that what you're looking for?

2022-12-16 11:00 UTC, ados8 commented
> > Tested the new build with Authentik using new redirect `/login/oidc/callback`. Everything continues to work except the subject mode via scope values. When signing in using OpenID the username is FQDN, i.e. email address as local user. This means that the user account primary identifier doesn't match LDAP or Emby. This also means that if the user logs in with Emby the have 2 accounts in the system and double their request limit. We need the default scope binding to username to match LDAP and/or Emby and have the ability to change for admins require it.
> 
> Just to be clear, the username (which confusingly is actually called "Display Name" in the user settings) is now set to the user's "name" provided by OIDC, meaning the display name matches between Jellyseer and the auth provider. However, the user matching code only looks up accounts by email address, since that's pretty much the only universal identifier for users in jellyfin. Sounds like you'd like the code to also check the user's `preferred_username` OIDC claim and compare that to Plex/Jellyfin usernames, is that what you're looking for?

Ok will clarify as I explained it poorly.
User example, Bob Smith, if they login having never done so in Jellyseerr there are two outcomes.

1. Login via OpenID and local account created with username/display name matching their respective account name. Their email is their email address.
2. They login via Emby, an Emby account is created and the username/display name matches their actual username. Their email is also their username.

In this case the user has 2 simultaneous accounts, essentially impersonating themselves.
I think we need to have the following:

- Display name equals the OpenID or LDAP account display name
- Email equals the account email address
- A new username field for their samaccount/UID/username (for Authentik its username)
- Emby and OpenID accounts linked so that regardless of the sign in type there is only 1 account per user

If it helps, my admin account works regardless if I sign in via Authentik or Emby, it never makes a local account and instead piggybacks of the Emby account. I think this due to the initial setup as my display name and email are my email addresses.
This would be the most desirable outcome, OpenID and Emby accounts are one in the same.

Let me know if you need me to test anything.

2022-12-24 20:41 UTC, michaelhthomas commented
@ados8 Just pushed some changes to provide the option to match usernames to Plex/Emby/Jellyfin accounts, preventing the double account problem in most cases. There are some caveats, like if a user logs in with OIDC first and then Jellyfin, but it's a compromise until some overhauling of user handling is done. 

Unfortunately, it's not possible to automatically redirect to the OIDC login page with the current implementation, since it uses popup windows which must be user-triggered. However, you can change the label of the button and remove the other login options, which should hopefully be intuitive enough for most users.

2022-12-26 03:06 UTC, ados8 commented
@michaelhthomas Thank you for implementing these idea changes 😊.
I have tested and it works as described, with the need for Emby login first or it will make a local account first.
This is an easy workaround for now to be incorporated into the process.

I again explained the SSO login redirect poorly.
It doesn't need to redirect to OpenID auth on landing, I'm looking to have the options to choose a default sign in.
At the moment, Emby is the default, then Jellyseerr and then OpenID.
Users having 3 decisions is complicated when they are not tech users.
You can simplify the process by removing the sign in options altogether but there are drawbacks:

- Remove Emby: now the double user account is an issue (unless you turned it on and then off once account was made)
- Remove Jellyseer: now my local superadmin account is unusable should Emby or Authentik be up in flames

If we could have an option so OpenID is presented to the user be default like below that will at least direct them to make the ideal login choice, example below.
![image](https://user-images.githubusercontent.com/49982433/209493966-9d44e3b8-a01a-47ff-a5d5-99547d0c1bdd.png)

The goal in future be to have a type `SSO` which matches Emby/Jellyfin/OpenID regardless of the first login; I see that appears to be a future direction.
The feedback and implementation has been excellent and I look forward to Jellyseer future. 🤩

2022-12-26 09:49 UTC, Fallenbagel commented
> At the moment, Emby is the default, then Jellyseerr and then OpenID.
> Users having 3 decisions is complicated when they are not tech users.
> You can simplify the process by removing the sign in options altogether but there are drawbacks:
> 
> - Remove Emby: now the double user account is an issue (unless you turned it on and then off once account was made)
> - Remove Jellyseer: now my local superadmin account is unusable should Emby or Authentik be up in flames
> 
> If we could have an option so OpenID is presented to the user by default like below that will at least direct them to make the ideal login choice.

Can't you already remove the emby login, and jellyseerr login options? Removing jellyseerr login options has always been a feature of jellyseerr and earlier on this pr I thought the emby/jellyfin login option was also made toggle-able

2022-12-26 15:01 UTC, Killerherts commented
> > At the moment, Emby is the default, then Jellyseerr and then OpenID.
> > Users having 3 decisions is complicated when they are not tech users.
> > You can simplify the process by removing the sign in options altogether but there are drawbacks:
> > 
> > * Remove Emby: now the double user account is an issue (unless you turned it on and then off once account was made)
> > * Remove Jellyseer: now my local superadmin account is unusable should Emby or Authentik be up in flames
> > 
> > If we could have an option so OpenID is presented to the user by default like below that will at least direct them to make the ideal login choice.
> 
> Can't you already remove the emby login, and jellyseerr login options? Removing jellyseerr login options has always been a feature of jellyseerr and earlier on this pr I thought the emby/jellyfin login option was also made toggle-able

I can toggle all these options. I also don't have the double account issues when only using authentik to login to jellyseerr

2022-12-26 15:02 UTC, kassarole commented
Yeah I don't have a double account issue since all my users sign into jellyfin with SSO already

2022-12-26 15:08 UTC, Killerherts commented
Maybe a solution could be just importing all the users into jellyfin as they are created or with a script based on time maybe?

2022-12-26 15:16 UTC, michaelhthomas commented
> Can't you already remove the emby login, and jellyseerr login options? Removing jellyseerr login options has always been a feature of jellyseerr and earlier on this pr I thought the emby/jellyfin login option was also made toggle-able

Yes, you can. I think what @ados8 was looking for is the ability to rearrange the login options so that OIDC is the first option. That's definitely something I could implement, but it might be a good thing to consider in the login page rework.

2023-01-18 14:28 UTC, Killerherts commented
Do we have more testing on this?

2023-01-22 02:04 UTC, kassarole commented
I've been running the current build with my users for about a month without issue. As far as I can tell this should be ready for a merge

2023-01-22 13:41 UTC, Fallenbagel commented
> I've been running the current build with my users for about a month without issue. As far as I can tell this should be ready for a merge

Sounds good. If there are no problems we can get this merged this week or so

2023-01-22 20:41 UTC, BoBeR182 commented
Can everyone who has a working setup please comment with what authentication providers are working for them.
Like this we can push it assuming every combination has been tested, I have not tested most recent changes, but keycloak was working me me and several other users in the thread.

2023-01-22 20:52 UTC, kassarole commented
> Can everyone who has a working setup please comment with what authentication providers are working for them. Like this we can push it assuming every combination has been tested, I have not tested most recent changes, but keycloak was working me me and several other users in the thread.

I run without issues with Authentik

2023-01-22 23:23 UTC, Fallenbagel commented
Any authelia users?

2023-01-24 07:53 UTC, Zegorax commented
I just installed this preview tag (using Docker) and OIDC is working flawlessly in combination with Authentik. Great work!

2023-01-24 12:01 UTC, Uruknara commented
Check it with Dashlane and it’s working well

Le mar. 24 janv. 2023 à 08:53, Zegorax ***@***.***> a écrit :

> I just installed this preview tag (using Docker) and OIDC is working
> flawlessly in combination with Authentik. Great work!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Fallenbagel/jellyseerr/pull/184#issuecomment-1401511162>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQHN6EXWTQGF2LN4UKNYBNTWT6DBDANCNFSM53JEHS7Q>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-01-25 01:14 UTC, xan-m commented
@Fallenbagel Authelia is confirmed working!

2023-01-28 00:27 UTC, xan-m commented
@Fallenbagel Authelia is confirmed working!

2023-01-28 01:36 UTC, ados8 commented
Regretting having Authentik on auto update but its set so for security.
A recent update as of a few days ago seems to have made large changes and OIDC is not working.
Users that were already authenticated and had their tokens didn't notice so it was only just identified.
Troubleshooting to see where the solution is.
Source: https://goauthentik.io/docs/releases/2023.1#fixed-in-202312

2023-01-28 02:10 UTC, Killerherts commented
> Regretting having Authentik on auto update but its set so for security. A recent update as of a few days ago seems to have made large changes and OIDC is not working. Users that were already authenticated and had their tokens didn't notice so it was only just identified. Troubleshooting to see where the solution is. Source: https://goauthentik.io/docs/releases/2023.1#fixed-in-202312

I just made about 5 users and don't have any issues. I am on the most current version of authentik

2023-01-28 02:12 UTC, kassarole commented
I'm also on the latest version of authentik without issue

2023-01-28 04:15 UTC, ados8 commented
For some apps I'm getting an error, for Jellyseerr it times out.
Failed OIDC login attempt {"cause":"Failed to fetch OIDC redirect url","ip":"::ffff:<NGINX IP>","errorMessage":"connect ETIMEDOUT <public IP>:443"}
Spent a few hours and given up for now 😫

2023-01-28 04:59 UTC, Killerherts commented
> For some apps I'm getting an error, for Jellyseerr it times out. Failed OIDC login attempt {"cause":"Failed to fetch OIDC redirect url","ip":"::ffff:NGINX IP","errorMessage":"connect ETIMEDOUT public IP:443"} Spent a few hours and given up for now 😫

That's a configuration error at your reverse proxy to me. But it would not be related to this pull request if it is also effecting other  apps as well.

I think we can probably close this PR as we have quite a few people who have tested both with authentik and authentic. @Fallenbagel

2023-01-28 05:01 UTC, Fallenbagel commented
> I think we can probably close this PR as we have quite a few people who have tested both with authentik and authentic. @Fallenbagel

Once the conflicts are resolved, its about time this goes live 😄

2023-01-28 05:37 UTC, Killerherts commented
> Once the conflicts are resolved, its about time this goes live 😄


Wow sorry I am a bonehead don't mind me. Thanks for you work and being nice lol. I would have gotten flammed for that on some other repos

2023-01-28 05:59 UTC, Fallenbagel commented
> Wow sorry I am a bonehead don't mind me.

It's okay no need to apologise c:

> I would have gotten flammed for that on some other repos

I dont understand why tho

2023-01-29 09:42 UTC, ados8 commented
Could anyone be kind enough to post their redacted Authentik configuration for Jellyseerr.
I had it working until the recent update with Authentik and have made no changes.
I've spent 6+ hours troubleshooting, rebuilding NGINX, Redit, Authentik and Jellyseer to have the same issues.
The spinning wheel.
![image](https://user-images.githubusercontent.com/49982433/215318066-0dba19e1-139e-4543-bb85-fd9fdd2f6413.png)

2023-01-29 14:23 UTC, michaelhthomas commented
> Could anyone be kind enough to post their redacted Authentik configuration for Jellyseerr.
> I had it working until the recent update with Authentik and have made no changes.
> I've spent 6+ hours troubleshooting, rebuilding NGINX, Redis, Postgress, Authentik and Jellyseer to have the same issues.
> The spinning wheel.
> ![image](https://user-images.githubusercontent.com/49982433/215318066-0dba19e1-139e-4543-bb85-fd9fdd2f6413.png)
> 

I'd check the jellyseerr server logs to see if there are any clues there, it should give pretty specific errors if anything OIDC related is going wrong.

2023-02-07 15:05 UTC, michaelhthomas commented on server/utils/oidc.ts
> +  formData.append('code', code);
Not sure if this is actually possible to exploit, but I'll add some extra validation just in case.

2023-02-07 17:05 UTC, michaelhthomas commented on server/utils/oidc.ts
> +  formData.append('code', code);
There doesn't appear to be any way to validate the code parameter (can contain any characters), but it should be safe to pass through directly to the OIDC server and should be validated there.

2023-02-07 18:01 UTC, Fallenbagel commented on server/utils/oidc.ts
> +  formData.append('code', code);
I think it should be fine 🤔

2023-02-07 22:06 UTC, Uruknara commented on server/utils/oidc.ts
> +  formData.append('code', code);
> I think it should be fine 🤔

you can merge now ?

2023-02-10 23:15 UTC, marouamghar commented
I am not able to login with OIDC, the logs says : 
2023-02-10T23:10:49.428Z [info]: Failed OIDC login attempt {"cause":"Failed to fetch OIDC redirect url","ip":"10.0.0.2","errorMessage":"unable to get local issuer certificate"}
I am pretty sure it's because I use Athentik with a self-signed certificate. For other services, I was able to kinda make them trust the signing entity by adding the root cert into one of their folders. Can a similar folder be exposed in Jellyseerr?

2023-02-10 23:20 UTC, michaelhthomas commented
> I am not able to login with OIDC, the logs says : 
> `2023-02-10T23:10:49.428Z [info]: Failed OIDC login attempt {"cause":"Failed to fetch OIDC redirect url","ip":"10.0.0.2","errorMessage":"unable to get local issuer certificate"}`
> I am pretty sure it's because I use Athentik with a self-signed certificate. For other services, I was able to kinda make them trust the signing entity by adding the root cert into one of their folders. Can a similar folder be exposed in Jellyseerr?

If you're running on Linux / docker you should be able to either use the `--use-openssl-ca` flag to tell node to use the system CA, or set the `NODE_EXTRA_CA_CERTS` environment variable to the path of the certificate on your filesystem.

2023-02-11 00:23 UTC, marouamghar commented
> > I am not able to login with OIDC, the logs says :
> > `2023-02-10T23:10:49.428Z [info]: Failed OIDC login attempt {"cause":"Failed to fetch OIDC redirect url","ip":"10.0.0.2","errorMessage":"unable to get local issuer certificate"}`
> > I am pretty sure it's because I use Athentik with a self-signed certificate. For other services, I was able to kinda make them trust the signing entity by adding the root cert into one of their folders. Can a similar folder be exposed in Jellyseerr?
> 
> If you're running on Linux / docker you should be able to either use the `--use-openssl-ca` flag to tell node to use the system CA, or set the `NODE_EXTRA_CA_CERTS` environment variable to the path of the certificate on your filesystem.

Thanks for the hint. With that env variable set (pointing to caddy's certs), OIDC works for both internal and external connections with caddy and authentik

2023-02-15 20:06 UTC, marouamghar commented
If I may, I did some more tests, and it seems to use the name field from the jwt for the username. If the name is not setup in the OIDC provider, the login fails, even if the user had a username. Should we try the 2 fields? Or specify which scopes we want to use?

2023-02-18 07:40 UTC, ados8 commented
> > Could anyone be kind enough to post their redacted Authentik configuration for Jellyseerr.
> > I had it working until the recent update with Authentik and have made no changes.
> > I've spent 6+ hours troubleshooting, rebuilding NGINX, Redis, Postgress, Authentik and Jellyseer to have the same issues.
> > The spinning wheel.
> > ![image](https://user-images.githubusercontent.com/49982433/215318066-0dba19e1-139e-4543-bb85-fd9fdd2f6413.png)
> 
> I'd check the jellyseerr server logs to see if there are any clues there, it should give pretty specific errors if anything OIDC related is going wrong.



> > Could anyone be kind enough to post their redacted Authentik configuration for Jellyseerr.
> > I had it working until the recent update with Authentik and have made no changes.
> > I've spent 6+ hours troubleshooting, rebuilding NGINX, Redis, Postgress, Authentik and Jellyseer to have the same issues.
> > The spinning wheel.
> > ![image](https://user-images.githubusercontent.com/49982433/215318066-0dba19e1-139e-4543-bb85-fd9fdd2f6413.png)
> 
> I'd check the jellyseerr server logs to see if there are any clues there, it should give pretty specific errors if anything OIDC related is going wrong.

I did but even with logs set to debug it shows nothing.
I have tried what I had previously in Redirect URIs/Origins (RegEx) for Authentik and about 10 other variations including suggestions. Anything placed in there now gives redirect error.
![image](https://user-images.githubusercontent.com/49982433/219848055-b67ede8e-9122-436e-a54a-56c7e7a157b8.png)
If I leave it blank it proceeds to infinitely show authenticate in progress.
Intrestingly when checking Authentik after leaving it blank and it applies its suggested URL its my internal address i.e. http://IP:5055/login/oidc/callback.
I have the application URL set to https://jellyseerr.domain.com
Just can no longer get it to work, maybe I just use Emby logins 🙁

2023-02-18 18:46 UTC, swesner411 commented
I was able to get this working with Authentik without too much trouble. I'm using the docker container with my URI set to "https://jellyseerr.domain.com/login/oidc/callback". I was hoping navigating to "https://jellyseerr.domain.com/api/v1/auth/oidc-login" would cause the login process to automate, but sadly it does not. It spits back a valid callback link but I have to refresh to "make it go". So close to my needs!

2023-02-21 16:48 UTC, michaelhthomas commented
> I was able to get this working with Authentik + NPM without too much trouble. I'm using the docker container with my URI set to "https://jellyseerr.domain.com/login/oidc/callback". I was hoping navigating to "https://jellyseerr.domain.com/api/v1/auth/oidc-login" would cause the login process to automate, but sadly it does not. It spits back a valid callback address but I have to refresh to "make it go". So close to my needs!

That is definitely a valid use case, this should be fixed now.

2023-02-28 20:33 UTC, Zegorax commented
Before this PR gets merged, would it be possible to add the possibility of multiple OIDC providers ?

2023-02-28 21:17 UTC, michaelhthomas commented
> Before this PR gets merged, would it be possible to add the possibility of multiple OIDC providers ?

That's probably outside the scope of this PR, if this is something you need I'd recommend looking into Authentik or another OIDC provider which [supports using external OAuth-based IdPs for enrollment](https://goauthentik.io/integrations/sources/oauth/).

2023-02-28 21:53 UTC, Zegorax commented
That's exactly my use case and I'm already using Authentik in my production system. The problem is that Authentik does not allow (yet, an issue is opened) to use a different Authentification flow than the different one for a specific application. 

That's the reason why I asked

2023-03-01 00:19 UTC, michaelhthomas commented
> That's exactly my use case and I'm already using Authentik in my production system. The problem is that Authentik does not allow (yet, an issue is opened) to use a different Authentification flow than the different one for a specific application.
> 
> That's the reason why I asked

Ah, yeah that stinks. That seems like a really unnecessary limitation, hopefully they get a fix out soon.

2023-03-02 14:27 UTC, marouamghar commented
could you create a tag to test logging without a popup window?

2023-03-02 14:33 UTC, Fallenbagel commented
> could you create a tag to test logging without a popup window?

I'll update it tonight

2023-03-17 18:58 UTC, inglemr commented
This works well for me so far but I did need to make one minor change which you can see here https://github.com/michaelhthomas/jellyseerr/commit/57fc9bb01bd79be5177ad94f72da3dcf6b120440. Essentially I am running jellyseer behind a reverse proxy in Kubernetes and by using the request host header it redirects the user to an inaccessible URL. Using the application URL solves this and redirects the user to the correct place.

2023-03-17 19:39 UTC, inglemr commented
> 

Sorry for the double post but after some additional testing, this is not necessarily required in my case so it may be fine as it is. I noticed that my reverse proxy was not preserving the host header which resulted in the behavior I was seeing.

2023-03-30 17:02 UTC, marouamghar commented
@Fallenbagel any news on this?

2023-04-01 16:16 UTC, marouamghar commented on server/routes/auth.ts
> +        username: fullUserInfo.name,
shouldn't you be using `fullUserInfo.preferred_username`? All systems involved in this process use the username field (similar to lign 823/824).

2023-04-04 14:38 UTC, michaelhthomas commented on server/routes/auth.ts
> +        username: fullUserInfo.name,
yep probably so. I'll update this

2023-04-20 05:37 UTC, kassarole commented
Any traction on merging this? With 1.5 launching I'd love to move back to the main release

2023-04-20 07:25 UTC, Fallenbagel commented
> Any traction on merging this? With 1.5 launching I'd love to move back to the main release

There's a few translation errors that this PR introduces that I want to get fixed before we think about merging 😔

2023-04-20 12:45 UTC, michaelhthomas commented
> There's a few translation errors that this PR introduces that I want to get fixed before we think about merging 😔

Lmk if there's anything I can do to help, and have a great graduation!

2023-04-20 12:52 UTC, Fallenbagel commented
> Lmk if there's anything I can do to help, and have a great graduation!

Thanks! I'll take a look at the strings and note down which parts. So we both can work on it so it'd be faster

2023-05-31 04:41 UTC, FirbyKirby commented
FYI - I pulled this preview today and set it up with Authentik as the OIDC auth provider. Worked like a charm. Really looking forward to this PR getting merged.

2023-06-05 06:46 UTC, ados8 commented
Running the preview build of preview-pr184 and cannot resolve this OIDC issue
Anyone able to assist?
![image](https://github.com/Fallenbagel/jellyseerr/assets/49982433/e1704d30-9ba6-426b-894c-4e790701530d)

I have tried 40+ variations and reviewed all the information from the github page but nothing works
Jellyseerr Settings
OIDC Issuer URL: `https.jellyseerr.domain.com/application/o/jellyseerr-oidc/`
Application Title: `https.jellyseerr.domain.com`

Authentik Settings
Redirect URL: `https.jellyseerr.domain.com/login`

I've also tried 20+ variations of the redirect URL and the OIDC URL but same issue 😫😭

2023-06-05 12:42 UTC, Killerherts commented
> Running the preview build of preview-pr184 and cannot resolve this OIDC issue Anyone able to assist? ![image](https://user-images.githubusercontent.com/49982433/243272528-e1704d30-9ba6-426b-894c-4e790701530d.png)
> 
> I have tried 40+ variations and reviewed all the information from the github page but nothing works Jellyseerr Settings OIDC Issuer URL: `https.jellyseerr.domain.com/application/o/jellyseerr-oidc/` Application Title: `https.jellyseerr.domain.com`
> 
> Authentik Settings Redirect URL: `https.jellyseerr.domain.com/login`
> 
> I've also tried 20+ variations of the redirect URL and the OIDC URL but same issue 😫😭
I hope you used
Https://jellyseer.domain.tld
Not
Https.jellyseer.domain.tld
As only the first is valid

2023-06-05 22:05 UTC, ados8 commented
@Killerherts oops that is typo, I have fixed my post. 
There are no issues with my URLs, I have OIDC in the name just for reference but it's part of Authentik app name.

2023-06-05 23:22 UTC, ados8 commented
I've done that and lots more ☺️.
Same error.

2023-06-07 02:24 UTC, curtainman commented
Would it at all be possible to remove the requirement for the email_verified claim for the JWT? I am trying to test this PR with my Azure AD tenant using OIDC and can't get it working since its missing this claim, and supposedly Azure AD doesn't provide this. Login flow is working but is getting stuck at this claim requirement. I haven't been able to test with Keycloak or Authentik yet. Maybe add an "emails verified" option so Jellyseerr can assume that all emails coming in are already verified?

2023-06-08 10:01 UTC, marcofaggian commented
> Running the preview build of preview-pr184 and cannot resolve this OIDC issue Anyone able to assist? ![image](https://user-images.githubusercontent.com/49982433/243272528-e1704d30-9ba6-426b-894c-4e790701530d.png)
> 
> I have tried 40+ variations and reviewed all the information from the github page but nothing works Jellyseerr Settings OIDC Issuer URL: `https://jellyseerr.domain.com/application/o/jellyseerr-oidc/` Application Title: `https://jellyseerr.domain.com`
> 
> Authentik Settings Redirect URL: `https://jellyseerr.domain.com/login`
> 
> I've also tried 20+ variations of the redirect URL and the OIDC URL but same issue 😫😭

The redirect url should point to the OIDC callback path: `https://jellyseerr.domain.tld/login/oidc/callback`, tested with Authentik, it works.

2023-06-08 11:17 UTC, ados8 commented
Hmm now a 504 timeout.
Anyone able to paste a their redacted config.
Is there something I need to tweak at the NGINX proxy level (I use NPM).

2023-06-09 03:06 UTC, ados8 commented
Further progress but not working as intended.
I moved the docker out into its own network instead of bridged it within Unraid which stopped the timing out.

However I cannot get it to work without removing the Authentik config from NGINX (NPM) for the `jellyseerr.domain.com`
If Authentik is managing the domain it works to sign in should you go there first but then OIDC refuses to sign in.
![image](https://github.com/Fallenbagel/jellyseerr/assets/49982433/5515e897-7840-4d9a-8bf3-2d375051a79f)
If the NPM settings are removed then it works no issue.

On another note, in all cases I cannot get it to work with any settings unless redirect URL is `.*` or it fails the redirect.
![image](https://github.com/Fallenbagel/jellyseerr/assets/49982433/8f3195cb-d54f-4326-9843-67cae98d50da)
If I leave the URL redirect blank Authentik fills in http://<IP>:5055/login/oidc/callback even when accessing from domain.
If I remove the Authentik configuration from the Jellyseerr domain and then let Authentik guess the redirect its correct: http://jellyseerr.domain.com/login/oidc/callback
Although somehow without HTTPS.

I can't have Jellyseerr exposed without Authentik in order to have OpenID, is this the current limitation or is it my setup.
Is anyone able to provide some assistance on this, it would be very appreciated.

2023-06-09 09:24 UTC, marcofaggian commented
I'm sorry but I think it's your network/docker setup that's somehow broken.
Maybe try to recreate the issue with a standalone docker-compose.yaml file
and then share it here, so that we could help you out.

My setup is Truenas's k3s with traefik, authentik and a local yarn dev
instance of jellyseerr. It works without any networking issue.

On Fri, Jun 9, 2023, 05:06 ados8 ***@***.***> wrote:

> Further progress but not working as intended.
> I moved the docker out into its own network instead of bridged it within
> Unraid which stopped the timing out.
>
> However I cannot get it to work without removing the Authentik config from
> NGINX (NPM) for the jellyseerr.domain.com
> If Authentik is managing the domain it works to sign in should you go
> there first but then OIDC refuses to sign in.
> [image: image]
> <https://user-images.githubusercontent.com/49982433/244578106-5515e897-7840-4d9a-8bf3-2d375051a79f.png>
> If the NPM settings are removed then it works no issue.
>
> On another note, in all cases I cannot get it to work with any settings
> unless redirect URL is .* or it fails the redirect.
> [image: image]
> <https://user-images.githubusercontent.com/49982433/244578332-8f3195cb-d54f-4326-9843-67cae98d50da.png>
> If I leave the URL redirect blank Authentik fills in http://:5055/login/oidc/callback
> even when accessing from domain.
> If I remove the Authentik configuration from the Jellyseerr domain and
> then let Authentik guess the redirect its correct:
> http://jellyseerr.domain.com/login/oidc/callback
> Although somehow without HTTPS.
>
> I can't have Jellyseerr exposed without Authentik in order to have OpenID,
> is this the current limitation or is it my setup.
> Is anyone able to provide some assistance on this, it would be very
> appreciated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Fallenbagel/jellyseerr/pull/184#issuecomment-1583890803>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AESUUCNT7WCSHZRHNW7LJJDXKKHLXANCNFSM53JEHS7Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-06-11 05:49 UTC, FirbyKirby commented
> 

Unfortunately, my stack is Traefik + Authentik + Jellyseerr + Jellyfin, so not identical to yours (different proxy.) But FWIW, here's my working config.

<img width="1109" alt="Screenshot 2023-06-11 at 12 42 53 AM" src="https://github.com/Fallenbagel/jellyseerr/assets/17125911/c0f4f77d-ae9f-48f3-a638-74af64a8b9a4">
<img width="1109" alt="Screenshot 2023-06-11 at 12 44 35 AM" src="https://github.com/Fallenbagel/jellyseerr/assets/17125911/ba410231-4f0b-4dd5-bcb8-559fa1c8bbe9">
<img width="1027" alt="Screenshot 2023-06-11 at 12 45 38 AM" src="https://github.com/Fallenbagel/jellyseerr/assets/17125911/1fd52642-575a-411b-b86e-68863eea8e62">

Just redacted my FQDN, ID and Secret. Note that I implemented a different Redirect URL for the launch URL so I could skip the Jellyseerr login for users who came to it via Authentik.

2023-06-11 09:56 UTC, BoBeR182 commented
While I love the open source community's support to troubleshoot in regards to getting this merge request accepted into `develop` is there anything missing outside Azure Active Directory?
I understand Authentik works minus some edge cases.

2023-06-11 17:10 UTC, curtainman commented
I've gotten Azure AD working in my local environment by removing the requirement for a verified email during the OIDC login flow. I think possibly having a "trust email verification" option in settings might help integration with other providers who don't provide this claim. 
Also, I was having troubles with mapping existing users to OIDC logins based on the preferred_username claim. My existing usernames are "Firstname Lastname" from Jellyfin LDAP and it doesn't work with what Azure AD is providing for preferred_username. Though it seems very edge case like, I've added an option in my local branch that allows an option to change what claim from OIDC maps to existing users, in case one can't change what the IDP provides through the current preferred_username claim. This sort of alleviates the issue I had while testing, where the user could change their email address and would force Jellyseerr to make a new user since it can't find one through the email or preferred_username.

2023-06-11 17:12 UTC, michaelhthomas commented
> I've gotten Azure AD working in my local environment by removing the requirement for a verified email during the OIDC login flow. I think possibly having a "trust email verification" option in settings might help integration with other providers who don't provide this claim. 
> Also, I was having troubles with mapping existing users to OIDC logins based on the preferred_username claim. My existing usernames are "Firstname Lastname" from Jellyfin LDAP and it doesn't work with what Azure AD is providing for preferred_username. Though it seems very edge case like, I've added an option in my local branch that allows an option to change what claim from OIDC maps to existing users, in case one can't change what the IDP provides through the current preferred_username claim. This sort of alleviates the issue I had while testing, where the user could change their email address and would force Jellyseerr to make a new user since it can't find one through the email or preferred_username. 

I'm currently working on this, I think I'm just going to add options for which claims to use for which fields to handle all the possible scenarios.

2023-06-12 02:07 UTC, FirbyKirby commented
@michaelhthomas  and @Fallenbagel, I can't thank either of you enough for your work on this PR. This thread is long (approaching it's anniversary in fact.) I spent quite a while (hours really) reviewing all the posts in y'all's journey to get here and the amount of collaboration is impressive. Really great work, and it's much appreciated by the whole community.

2023-07-14 04:44 UTC, eaglesemanation commented
I hate to be that guy, but maybe a reminder will help, if this PR was just forgotten. Are there any updates on this? I've been incorporating Authentik into my k8s setup, and I would really love to give users access to Jellyseerr. Will I help if I test this branch? Seems like my setup is quite similar to already mentioned ones, so I don't think I'll find any new errors.

2023-07-14 10:33 UTC, Fallenbagel commented
> I hate to be that guy, but maybe a reminder will help, if this PR was just forgotten.

No not forgotten. Just waiting for upstream oidc too

2023-07-14 14:09 UTC, BoBeR182 commented
To confirm we are waiting on Azure support bugfix for email username claims.

Outside of that I think the consensus is that all other providers work for many people. (Some users have esoteric configurations, but the bugs seem to be not jellyseerr related)

I guess the question is do we ship it by a certain date without azure support and merge it later? Shipping support for one/few OIDC providers at a time seems better than waiting for all of them to be implemented perfectly.

2023-07-31 01:51 UTC, brentmarquis commented
Also want to add how great this feature is! Would be great to see it in the main branch.
Working for me with Traefik+Authentik+Jellyseerr+Plex.

2023-08-02 22:21 UTC, Ruakij commented
This feature is working great once setup correctly.
I think its possible to remove all forms of authentication and be left stranded without any login-capabilities?
Cant 100% remember, but i think  i did that on accident on my first setup.

And i'd love to have an option to auto-redirect unauthenticated users to the auth-provider for the login. (which will either prompt them to login or just seamlessly send them back and no button had to be pressed by them)

I'd also like to select a default provider or select the sorting. If local auth and OIDC is enabled, local will be presented first and OIDC has to be clicked first to start the auth-process.

Terrific work!

2023-08-13 14:34 UTC, michaelhthomas commented
Finally had some time to work an a UI change that will allow for a lot more configurability without the settings page looking ridiculous. Wanted to get everyone's thoughts before I push to this branch since it is a bit of a break from tradition. @Fallenbagel any thoughts on this?

https://github.com/Fallenbagel/jellyseerr/assets/18223295/d4fddc9d-d59d-4e19-a445-4c6ae897a567

2023-08-13 14:36 UTC, kassarole commented
I think that looks great

2023-08-13 14:36 UTC, Uruknara commented
> Finally had some time to work an a UI change that will allow for a lot more configurability without the settings page looking ridiculous. Wanted to get everyone's thoughts before I push to this branch since it is a bit of a break from tradition. @Fallenbagel any thoughts on this?
> 
> 
> 
> https://github.com/Fallenbagel/jellyseerr/assets/18223295/d4fddc9d-d59d-4e19-a445-4c6ae897a567
> 
> 
> 
> 

Really clean pop-up transitions !

2023-08-13 21:43 UTC, ados8 commented
Nice design and a separation to make it easier for users configuring relating settings. Are we keeping the current login page? I currently have all logins disabled except OIDC which makes it really easy for users to know how to log in and if I have any issues I can modify the config file to allow local login.

2023-08-13 22:09 UTC, Fallenbagel commented
> Finally had some time to work an a UI change that will allow for a lot more configurability without the settings page looking ridiculous. Wanted to get everyone's thoughts before I push to this branch since it is a bit of a break from tradition. @Fallenbagel any thoughts on this?
> 
> https://github.com/Fallenbagel/jellyseerr/assets/18223295/d4fddc9d-d59d-4e19-a445-4c6ae897a567
> 
> 

I actually love that. Less clutter 🤌

2023-08-23 14:43 UTC, pando85 commented
This looks awesome! I have mine working in K8s with Nginx and Kanidm.

I would recommend a few improvements if possible:
- Callback schema behind the proxy is `http`, in other services that I have with the same setup this is `https` without any problems.
- PKCE is disabled. It would be great to have that implemented.
- When authenticating the pop up window is weird for me, I use to see just a redirect.

2023-09-08 06:19 UTC, caseyWebb requested changes
I'm doing this out of necessity at the moment because Casdoor doesn't support the `email_verified` claim, but I think it makes sense. If not this, perhaps configurable in the OIDC settings?

2023-09-08 06:19 UTC, caseyWebb commented on server/utils/oidc.ts
> +    email_verified: yup.boolean().required(),
```suggestion
    email_verified: yup.boolean(),
```

2023-09-08 06:19 UTC, caseyWebb commented on server/utils/oidc.ts
> +  Mandatory<OidcStandardClaims, 'name' | 'email' | 'email_verified'>;
```suggestion
  Mandatory<OidcStandardClaims, 'name' | 'email'>;
```

2023-09-08 06:19 UTC, caseyWebb commented on server/routes/auth.ts
> +    if (!fullUserInfo.email_verified) {
```suggestion
    if (
      settings.notifications.agents.email.options.userEmailRequired &&
      !fullUserInfo.email_verified
    ) {
```

2023-09-08 07:33 UTC, caseyWebb commented
Another edge case to handle: if the user being created is the initial user, permissions need to be set to admin. Alternatively, and possibly better, always return admin permissions when a user's id == 1.

2023-09-08 12:31 UTC, michaelhthomas commented
> I'm doing this out of necessity at the moment because Casdoor doesn't support the `email_verified` claim, but I think it makes sense. If not this, perhaps configurable in the OIDC settings?

My goal is to add this to the OIDC settings dialog, I just haven't gotten around to it yet. I'm planning to just allow providing a list of required claims (or none) so it's as configurable as possible

2023-09-12 12:38 UTC, michaelhthomas commented
> @michaelhthomas Will this also support something like Traefik ForwardAuth?

No, that would be a separate feature I'm afraid.

2023-09-25 15:52 UTC, chrisfu commented
Hey @michaelhthomas 

Great work on the OIDC feature thus far. However, I've come across a bug!

I feel that many will be using this functionality in conjunction with the SSO-Auth plugin of Jellyfin, as am I. When it's setup for the first time, everything works fantastically well: that is, until you go and change your account profile image within Jellyfin. Due to the way that Jellyseerr authenticates with Jellyfin, and Jellyfin interacts with the SSO-Auth plugin, what ends up happening within Jellyfin is that the password set *within Jellyfin itself* is reset to null as a result of changing the profile image. I believe this is some course-correction on Jellyfin's part, as it knows that authentication is handled externally via either LDAP or the SSO (OIDC) plugin.

Jellyseerr ends up in a state where it can't sync libraries and receives a 401 response from Jellyfin due to an expired token. Unfortunately, resetting the password back to what it was set to in Jellyfin's local database previously doesn't coax Jellyseerr into attempting to generate a new token, and Jellyseerr doesn't seem to provide any mechanism with which to re-authenticate with Jellyfin outside of initial setup.

The end result is a Jellyseerr instance that's detached from Jellyfin with no visible means of how to re-attach.

With this problem in mind, it feels as if it may well be useful to add a mechanism to enable the re-attachment of Jellyseerr to Jellyfin. When experimenting I did find some API methods that seemed promising, but one of them not only reset Jellyseerr to it's initial state: it also regressed Jellyseerr into an Overseerr-esque state where several pre-fork changes in the UI returned. I stopped dabbling with the API at that point and started with a clean slate.

2023-09-30 18:31 UTC, sunjam commented
In regards to the Jellyfin SSO plug, see [this roadmap for future app development](https://github.com/9p4/jellyfin-plugin-sso/issues/61) and [this Jellyfin meta issue for supporting Oauth and OIDC](https://github.com/jellyfin/jellyfin-meta/issues/28).  Might be of interest.  Cheers. :heart:

2023-10-01 04:05 UTC, ubrfkr commented
Authelia user here. (Traefik+Authelia+Jellyseerr+Plex)
I've read through this entire thread but I'm still having issues after I try to sign in using Authelia. It presents the Authelia consent request screen but after accepting it shows the Jellyseerr login screen with the following error:
`request.query should have required property 'code'`

![image](https://github.com/Fallenbagel/jellyseerr/assets/90567631/1a7b3eda-9b63-41e4-ab70-2fc22b6e6993)

```
Jellyseerr Settings:
Application URL:    https://jellyseerr.kodex.click
Enable Proxy Support: TRUE
Enable Local Sign-In: TRUE
Enable Plex Sign-In: TRUE
Enable OIDC Sign-In: TRUE
OIDC Issuer URL: https://auth.domain.tld
OIDC Provider Name: Authelia
OIDC Client ID: jellyseerr
OIDC Client Secret: supersecret

Authelia Settings:
- id: jellyseerr
      public: true
      authorization_policy: one_factor
      audience: []
      scopes:
        - openid
        - email
        - profile
      redirect_uris:
        - https://jellyseerr.dom.tld/login/oidc/callback
      userinfo_signing_algorithm: none
```

I have tried variously adding       

      response_types:
        - code
      response_modes:
        - form_post
        - query
        
to authelia without really knowing what I am doing.

Does anyone have any guidance on what's going wrong? Thanks. (Amazing work on this PR by the way!!)

2023-10-07 13:04 UTC, n1ght-hunter commented
just thought i would say really good PR.
was easy to setup and get working took me all of 5 mins to switch.

i have a few thoughts so far
- you cant set the User identifier
- you cant set the scopes
- select admin using groups | just something nice

- this doesnt work when using jellyseer as a PWA | i imagine this is an easy fix will have a look if i get time

2023-11-07 21:08 UTC, Fallenbagel commented
This PR has been updated with develop and the **_preview tag is now renamed_**:
`preview-pr184` -> **`preview-OIDC`**

2023-11-14 14:41 UTC, fredmorais commented
I followed the above Authelia configuration and am having the error "request.query should have required property 'code'". Is there any way you can help me, please?

2023-12-09 09:33 UTC, Gylesie commented
I do not mean to rush this at all, but why is this PR not getting merged? Is there something blocking it? Just wanted to know if there is something we can do to help make it move forward.

2023-12-09 11:17 UTC, swesner411 commented
I get emails from comments here every so often. I've been using this preview for over a year now with no issues with Authentik. The only problem right now is I'm not getting any updates because this preview hasn't gotten anywhere. Could I be security risk because of this? Maybe. The software's author(s) would know better than me. That being said, it's painful to watch all these comments while this continues to not make it into the main product. Like the other commenter said, what can we do to get this moving? Do we need some code? Do we need money? What's up?

2023-12-09 15:32 UTC, Killerherts commented
> I get emails from comments here every so often. I've been using this preview for over a year now with no issues with Authentik. It's painful to watch all these comments while this continues to not make it into the main product. Like the other commenter said, what can we do to get this moving? Do we need some code? Do we need money? What's up?

I believe they are working out some ux stuff on issue 183. Extra clicks to populate odic tokens and stuff like that. Odic-preview is more current than the old tag.

2023-12-09 22:18 UTC, michaelhthomas commented
Just pushed a bunch of changes to add the new dialog UI, support some more advanced configuration options, and optionally allow redirects for OIDC login and logout if it is the only configured authentication provider. @Fallenbagel if you could update the docker image whenever you get a chance, that would be great! I would love for anyone willing to test this new branch. You'll have to re-configure the settings if coming from the old tag, but the behavior should be about the same. Hopefully we can get this PR merged soon!

2023-12-10 03:50 UTC, Fallenbagel commented
> Just pushed a bunch of changes to add the new dialog UI, support some more advanced configuration options, and optionally allow redirects for OIDC login and logout if it is the only configured authentication provider. @Fallenbagel if you could update the docker image whenever you get a chance, that would be great! I would love for anyone willing to test this new branch. You'll have to re-configure the settings if coming from the old tag, but the behavior should be about the same. Hopefully we can get this PR merged soon!

Would be updating some time today

2023-12-12 10:55 UTC, swesner411 commented
@michaelhthomas @Fallenbagel Which docker image tag are we testing? "preview-OIDC" (which I updated to without issues) hasn't been updated in a month. The only thing recent I see is on the "develop" tag updated 9 days ago. Once I have my hands on an updated docker image I can immediately deploy and get a handful of people testing.

2023-12-12 12:12 UTC, Fallenbagel commented
> @michaelhthomas @Fallenbagel Which docker image tag are we testing? "preview-OIDC" (which I updated to without issues) hasn't been updated in a month. The only thing recent I see is on the "develop" tag updated 9 days ago. Once I have my hands on an updated docker image I can immediately deploy and get a handful of people testing.

I have not updated tag yet. Got busy with work sorry. I'll update the tag tonight. Its `preview-OIDC`

2023-12-16 21:32 UTC, Fallenbagel commented
Updated. Sorry for the wait everyone

2023-12-17 02:41 UTC, ados8 commented
Highly recommend not updating as it broke my installation.
![image](https://github.com/Fallenbagel/jellyseerr/assets/49982433/08b3db75-2dd6-49f8-bc61-0694c7accef4)
The images have gotten quite confusing as to which build to use.
I've tried all the previous preview-prXXX versions including preview-pr338 which I know I was running at one time.
None of them restore the OIDC functions in the web interface except for preview-OIDC.
However, when using that build the OIDC no longer works with Authentik and I had all but OIDC login enabled to reduce user confusion effectively locking me out of the portal.

I was able to use an older version to access the portal and then apply the preview-OIDC image again.
This got me into the portal but non of the settings could save, perhaps some bug caused by the version hopping.
The only solution was to restore from backups and modify the config to allow Emby logins as even enabling local logins didn't work for my superadmin account.
![image](https://github.com/Fallenbagel/jellyseerr/assets/49982433/2542ec54-a7ba-4f6e-837e-04ead5165f38)
Will report back once I have Authentik working again.

2023-12-17 02:53 UTC, Killerherts commented
> Updated. Sorry for the long wait, everyone



> Highly recommend not updating as it broke my installation. ![image](https://private-user-images.githubusercontent.com/49982433/291024043-08b3db75-2dd6-49f8-bc61-0694c7accef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODE3OTcsIm5iZiI6MTcwMjc4MTQ5NywicGF0aCI6Ii80OTk4MjQzMy8yOTEwMjQwNDMtMDhiM2RiNzUtMmRkNi00OWY4LWJjNjEtMDY5NGM3YWNjZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAyNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxY2M1NzQzZDBlZmQzYTU0ZjhiYzM5OTIxYTIwYzQ4YWI0YWQ1Nzk0OTNiNjA5YmJlODAzYmY1MWIzODgxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0QLI8DvwEZHvWLUvNXmAiAVh3f3tys5DTpd2HaDxdXw) The docker images have gotten quite confusing as to which build to use. I've tried all the previous preview-prXXX versions including preview-pr338 which I know I was running at one time. None of them restore the OIDC functions in the web interface except for preview-OIDC. However, when using that build the OIDC no longer works with Authentik and I had all but OIDC login enabled to reduce user confusion effectively locking me out of the portal.
> 
> I was able to use an older version to access the portal and then apply the preview-OIDC image again. This got me into the portal but non of the settings could save, perhaps some bug caused by the version hopping. The only solution was to restore from backups and modify the config to allow Emby logins as even enabling local logins didn't work for my superadmin account. ![image](https://private-user-images.githubusercontent.com/49982433/291024429-2542ec54-a7ba-4f6e-837e-04ead5165f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODE3OTcsIm5iZiI6MTcwMjc4MTQ5NywicGF0aCI6Ii80OTk4MjQzMy8yOTEwMjQ0MjktMjU0MmVjNTQtYTdiYS00ZjZlLTgzN2UtMDRlYWQ1MTY1ZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAyNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNzhlOTk2M2YxMGEyOTdlNjBmYzIxYWY4MWEwMTM0MWYyZWJlNGRmN2ZmMmE0NmJhOGEyMzRlOGUxNjE5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lodl47k7fqp7bBobgok9UPMswEq9j2F58EVqcxNu0Ck) Will report back once I have Authentik working again.

Is is something about your setting because I was able to update to this tag copy my PDF that a saved with my settings over and restart the container. Everything works as excepted. 

I am using latest authentic and no back up login method jellyseer is odic only

2023-12-17 03:09 UTC, ados8 commented
Everything is fixed 😊.
So, the problem is when you upgrade to the new build the current settings don't migrate.
This breaks the login if you have only OIDC set as it no longer has any setting values but the enabled flag is still set.
Workaround was to enable media logins (not sure why my local login is broken) and then reboot the container.
Login with Jellyfin/Emby and then set the OIDC settings as before using the new menu. I didn't need to tweak any settings.
OIDC will now work with Authentik providing your settings are ok.

One thing to note is the automatic login breaks the login page.
If I have only OIDC I can login as per normal with a single click.
But if I enable the automatic login it doesn't load the page anymore with domain.com refused to connect.
Disable that setting in the config and everything works.

2023-12-17 03:12 UTC, kassarole commented
For what it's worth reconfiguring OIDC was mentioned above when the changes were made to this branch
>  You'll have to re-configure the settings if coming from the old tag, but the behavior should be about the same. Hopefully we can get this PR merged soon!

2023-12-17 03:12 UTC, Killerherts commented
Ahh I kinda figured that was happened so I left a browser window open with a stored cookie updated settings then logged. 

My auto login also works as expect no domain issues

2023-12-17 03:18 UTC, ados8 commented
> For what it's worth reconfiguring OIDC was mentioned above when the changes were made to this branch
> 
> > You'll have to re-configure the settings if coming from the old tag, but the behavior should be about the same. Hopefully we can get this PR merged soon!

Yeah that's my fault, only 4 hours sleep today so apologies for the abrasiveness.
I was somehow already using the preview-OIDC tag so I just updated thinking it wasn't required.
I've had issues before getting Authentik URLs just right and jumped to that being the fault.
@Killerherts that's interesting, I will looking into Authentik then to see if I can get it working.

2023-12-17 03:55 UTC, michaelhthomas commented
@ados8 Would you mind sending a video or similar (with sensitive information blurred) to help diagnose the issue you were having with the automatic login setting? I'm not sure why that redirect would be broken, but the non-automatic login would work, so I'd love to make sure it's not some esoteric bug. Thanks!

2023-12-17 08:38 UTC, SadRobot11 commented
I am trying to set this up with Authelia, and I get this error

> The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.

What kind of redirect uris should I set up in Authelia config for jellyseerr?

2023-12-17 08:54 UTC, Ruakij commented
> What kind of redirect uris should I set up in Authelia config for jellyseerr?

Should be `<jellyseer-domain>/login/oidc/callback`

2023-12-17 11:54 UTC, swesner411 commented
I was on a PR-### build originally. I first moved to the Preview-OIDC tag before the update, so I didn't encounter any issues. I enabled Plex login rather than just OIDC and upgraded. This allowed me to still get in despite breaking my OIDC setup with the latest update. I re-entered my OIDC settings, turned Plex login off, and everything is working as expected. I have zero complaints or issues with the latest build at this time. So far my half-dozen users have not complained or noticed any changes. I also haven't noticed anything wild so far.

2023-12-17 21:47 UTC, Zegorax commented
I'm also getting `{"message":"Configuration error."}`. Is there any way to fix this without restoring ?

2023-12-17 21:49 UTC, michaelhthomas commented
You should just be able to edit your `settings.json` file iirc

2023-12-17 21:51 UTC, Zegorax commented
@michaelhthomas What needs to be edited in `settings.json`? I can see my OIDC config that was being used prior to the update

2023-12-17 22:34 UTC, michaelhthomas commented
> @michaelhthomas What needs to be edited in `settings.json`? I can see my OIDC config that was being used prior to the update

Either just re-enable local login temporarily, or you can move all the settings under the `oidc` object as specified in [`settings.ts`](https://github.com/Fallenbagel/jellyseerr/blob/oidc-login/server%2Flib%2Fsettings.ts)

2023-12-20 23:36 UTC, lucaam commented
I also tested it successfully with Authentik, many thanks for your work @michaelhthomas!

I had bad times setting this up because of a space at the end of the `Issuer URL`. 
Can a trim on the frontend or something similar on the backend help here?

2023-12-26 02:54 UTC, Alumni1506 commented
> You nail

Would you be able to share your redacted working authelia config please?

2023-12-27 18:58 UTC, SadRobot11 commented
> > What kind of redirect uris should I set up in Authelia config for jellyseerr?
> 
> Should be `<jellyseer-domain>/login/oidc/callback`

Thank you! This helped, but now I get login failed error after going through authelia login and accepting the profile info sharing. Perhaps something needs to be changed in the authelia config below?

> -id: jellyseerr
>         description: Jellyseerr OIDC
>         secret: 'secret' # provide secure secret
>         sector_identifier: ''
>         public: false
>         authorization_policy: one_factor # may use two_factor to enforce 2FA
>         consent_mode: explicit
>         pre_configured_consent_duration: 4w
>         audience: []
>         scopes:
>           - openid
>           - groups
>           - email
>           - profile
>         redirect_uris: # adjust to your domains
>           - https://jellyseerr.domain.com/login/oidc/callback
>         grant_types:
>           - refresh_token
>           - authorization_code
>         response_types:
>           - code
>         response_modes:
>           - form_post
>           - query
>           - fragment
>         userinfo_signing_algorithm: none

And this is what I have in jellyfin OIDC settings:
![image](https://github.com/Fallenbagel/jellyseerr/assets/145222276/88b95b8b-a48e-4df1-bc92-be0d9d43fc07)

2023-12-27 19:04 UTC, Alumni1506 commented
For those coming across this, the settings that worked for me are as follows

Authelia config.
```
identity_providers:
  oidc:
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - "*"
      allowed_origins_from_client_redirect_uris: false
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:  
    - id: '<random generated alphanumeric>' (instructions [here](https://www.authelia.com/reference/guides/generating-secure-values/#generating-a-random-password-hash))
      description: jellyseerr
      public: false
      secret: '<argon digest>'
      authorization_policy: two_factor
      audience: []
      redirect_uris:
        - https://<Jellyseerr domain>.com/login/oidc/callback
      scopes:
        - openid
        - profile
        - email
        - groups
      userinfo_signing_algorithm: none
```

Jellyseerr settings

Issuer URL: https://<authelia domain>.com
Provider Name: Authelia (or whatever you wish)
Client ID: <random generated alphanumeric> (id used in authelia config file, must match)
Client Secret: <Random Password> (Random Password used to generate digest in authelia config)

2023-12-28 23:28 UTC, SadRobot11 commented
> For those coming across this, the settings that worked for me are as follows
> 
> Authelia config.
> 
> ```
> identity_providers:
>   oidc:
>     access_token_lifespan: 1h
>     authorize_code_lifespan: 1m
>     id_token_lifespan: 1h
>     refresh_token_lifespan: 90m
>     enable_client_debug_messages: false
>     enforce_pkce: public_clients_only
>     cors:
>       endpoints:
>         - authorization
>         - token
>         - revocation
>         - introspection
>         - userinfo
>       allowed_origins:
>         - "*"
>       allowed_origins_from_client_redirect_uris: false
>     ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
>     ## See: https://www.authelia.com/c/oidc
>     clients:  
>     - id: '<random generated alphanumeric>' 
>       description: jellyseerr
>       public: false
>       secret: '<argon digest>'  #instructions https://www.authelia.com/reference/guides/generating-secure-values/#generating-a-random-password-hash
>       authorization_policy: two_factor
>       audience: []
>       redirect_uris:
>         - https://<Jellyseerr domain>.com/login/oidc/callback
>       scopes:
>         - openid
>         - profile
>         - email
>         - groups
>       userinfo_signing_algorithm: none
> ```
> 
> Jellyseerr settings
> 
> Issuer URL: https://.com Provider Name: Authelia (or whatever you wish) Client ID: #id used in authelia config file, must match Client Secret: #Random Password used to generate digest in authelia config

Thank you for the config details. I matched those, but still get the "Authorization failed" error after accepting the consent requirements in Authelia popup window.

What kind of settings could be used in Jellyseerr OIDC advanced settings for "Identification Claims" and "Required Claims"?
Is this supposed to work with Jellyfin users or only local users?

2023-12-29 18:19 UTC, Alumni1506 commented
> 
> What kind of settings could be used in Jellyseerr OIDC advanced settings for "Identification Claims" and "Required Claims"? Is this supposed to work with Jellyfin users or only local users?

See below. I may try changing Identification Claims to username
![image](https://github.com/Fallenbagel/jellyseerr/assets/112524737/fc8888a7-2e10-4d12-b830-328db7e288bb)

2023-12-29 20:44 UTC, SadRobot11 commented
> > Thank you for the config details. I matched those, but still get the "Authorization failed" error after accepting the consent requirements in Authelia popup window.
> 
> I would suggest to check if you have any space in the Issuer URL and check in any case, the url(s) you are trying to use from Jellyseerr (both from Jellyseerr adding some logger line and from Authelia logs).

I checked the urls, did not find any mistakes. I checked the jellyseerr logs, and there is the error message below when I get "Authorization error":

`Failed OIDC login attempt {"cause":"Invalid jwt or missing claims","ip":"_my.current.public.ip_","idToken":"_very_long_string_","errorMessage":"profile is a required field"}`

2023-12-29 22:57 UTC, lucaam commented
> I checked the urls, did not find any mistakes. I checked the jellyseerr logs, and there is the error message below when I get "Authorization error":
> 
> `Failed OIDC login attempt {"cause":"Invalid jwt or missing claims","ip":"my.current.public.ip","idToken":"very_long_string","errorMessage":"profile is a required field"}`
> 
> The "very_long_string" seems to be unique every error instance.

Not sure why this is missing in your provider config and if this is needed but I would remove `profile` from this list (to test if you get a different result)

<img width="485" alt="image" src="https://github.com/Fallenbagel/jellyseerr/assets/21973580/d8916483-950c-4dda-a639-5b5f340923c7">

2024-01-07 15:45 UTC, michaelhthomas commented
> I had bad times setting this up because of a space at the end of the `Issuer URL`. Can a trim on the frontend or something similar on the backend help here?

This should be fixed now, thanks for the feedback. I've considerably improved the URL validation to not use a handcrafted regex validator, so it should now catch things like spaces at the end of the URL.

2024-01-07 19:29 UTC, SadRobot11 commented
> Not sure why this is missing in your provider config and if this is needed but I would remove `profile` from this list (to test if you get a different result)

Thank you for the suggestion! This seems to have changed things albeit still no successful login. I get the same authorization error in jellyseerr, and looking at the logs there is now new error description:

`Failed OIDC login attempt {"cause":"Invalid jwt or missing claims","ip":"my.current.public.ip","idToken":"very_long_string","errorMessage":"The token iss value doesn't match the oidc_DOMAIN (https://auth.my-domain.com/)"}`

The https://auth.my-domain.com/ is correct for and matches the settings in jellyseerr as well, so not sure what is wrong and where,

2024-01-08 15:24 UTC, michaelhthomas commented
> The https://auth.my-domain.com/ is correct for and matches the settings in jellyseerr as well, so not sure what is wrong and where,

Try pasting the `idToken` (very long string) into https://jwt.io/ and compare the decoded iss value to the oidc domain you have set. If these don't match, then there's probably a configuration error of some sort.

2024-01-12 10:55 UTC, dan-online commented
Seems to work! Only issue is that it doesn't match the username to an existing jellyfin login, so it ends up with 2 accounts with the same username, with the "Match jellyfin username" enabled

2024-01-12 14:03 UTC, Scot-Survivor commented
It would be awesome if Roles and Groups could be synced by the OAuth provider. 

This in general shouldn't be too difficult. 

Secondly, state being hardcoded is a major security concern. The state parameter is designed to prevent Cross Site Request Forgery. It would be nice if this was handled prior to merge

2024-01-16 18:04 UTC, michaelhthomas commented
> hardcoded



> Secondly, state being hardcoded is a major security concern. The state parameter is designed to prevent Cross Site Request Forgery. It would be nice if this was handled prior to merge

What led you to believe that the state is hardcoded? It should be randomly generated for each request, see [here](https://github.com/Fallenbagel/jellyseerr/blob/f1d9ffa4d54cf35ed8249c928db77e2c94c86877/server/routes/auth.ts#L669).

2024-01-20 02:19 UTC, zeitue commented
I tested this with Authentik and Caddy reverse proxy.
My configurations are as such:
## Authentik
Name `JellySeerr Oauth`
Authorization flow `default-provider-authorization-implicit-consent (Authorize Application)`
Client type `Confidential`
Client ID `(generated)`
Client Secret `(generated)`
Redirect URIs/Origins (RegEx) `http://jellyseerr.domain.com/login/oidc/callback`
Signing Key `authentik Self-signed Certificate`
Scopes `email, openid, profile, groups`
Subject mode `Based on the User's username`

## Jellyseerr
Issuer URL `https://id.domain.com/application/o/jellyseerr/`
Provider Name `SSO`
Client ID `from before`
Client Secret `from before`
Scopes `email openid profile groups`
Identification Claims `email`
Required Claims ``
Allow Jellyfin Usernames `true`
Automatic Login `true`

## Questions
* One thing that is not good is the redirect URL won't work unless it uses HTTP only. Is there some hard-coded HTTP part of the URL or something?
* Is there a way to get the Required claims to check if the user is in a certain group? I have a `groups` scope that returns an array of groups.

2024-01-21 18:26 UTC, BartvanLaar commented
> appens when the build argument is not added during building

What build argument? can't seem to find it in the docs, but I keep getting the popup

2024-01-21 18:43 UTC, BartvanLaar commented
@michaelhthomas running 'yarn add url' would fix the build.

2024-01-21 20:58 UTC, Fallenbagel commented
> > > but when i run a pod with the above image I get
> > > ![image](https://user-images.githubusercontent.com/33070637/192103815-fde19d63-85fc-48d9-8240-000e3a410291.png)
> > > (pressing reload refreshes the page and this pop-up appears again)
> > > this is strange, I tried running on the normal develop branch to see if its something with your changes (which I doubted) but I get the same issue. Data seems to need to be reloaded but even if i start on fresh pvc i still get this. Is there some variable I am missing ?
> > 
> > 
> > This happens when the build argument is not added during building
> 
> What build argument? can't seem to find it in the docs, but I keep getting the popup

You need to pass the build argument `--build-arg COMMIT_TAG=xxxxxxxx` where `xxxxxxx` is the commit hash

2024-01-21 21:08 UTC, MiguelNdeCarvalho commented
Hey, is there any ETA when this is going to be merged? Thanks everyone!

2024-01-26 04:47 UTC, brenninger commented
When signing into Jellyseerr under my Authentik OIDC, I get stuck with at the "Authentication in progress" screen with the spinning wheel of death. Anyone know how to fix that?

2024-01-26 13:09 UTC, brenninger commented
I am getting stuck on the Redirect URI error. 

I am using Authentik and when I leave the redirect URI blank, it auto-populates to the internal IP for the redirect (https://INTERNAL-IP/login/oidc/callback) however this still does not log me into Jellyseerr, and I get stuck in a loading spinning wheel attempting to be redirected from Authentik.

I try to change the redirect to my domain (https://jellyseerr.MYDOMAIN.com/login/oidc/callback) and I get a Redirect URI error. No login attempt is being showed in Jellyseerr from what I can see in the logs. Anyone have any idea where to try next?

2024-02-03 10:56 UTC, lucaam commented
> > I had bad times setting this up because of a space at the end of the `Issuer URL`. Can a trim on the frontend or something similar on the backend help here?
> 
> This should be fixed now, thanks for the feedback @lucaam. I've considerably improved the URL validation to not use a handcrafted regex validator, so it should now catch things like spaces at the end of the URL.

I had to clone your branch and tried to build it, I was not able to build because of the improved URL validation (especially with URL.parse()) that should be the same reason why the build in CI is not passing. I had to revert that commit locally to build.

2024-02-03 11:16 UTC, BartvanLaar commented
> > > I had bad times setting this up because of a space at the end of the `Issuer URL`. Can a trim on the frontend or something similar on the backend help here?
> > 
> > 
> > This should be fixed now, thanks for the feedback @lucaam. I've considerably improved the URL validation to not use a handcrafted regex validator, so it should now catch things like spaces at the end of the URL.
> 
> I had to clone your branch and tried to build it, I was not able to build because of the improved URL validation (especially with URL.parse()) that should be the same reason why the build in CI is not passing. I had to revert that commit locally to build.

Adding the 'url' package with yarn add would fix that issue. Though i do not know what the projects' rules are regarding the adding of packages.

2024-02-03 11:18 UTC, lucaam commented
> > I had to clone your branch and tried to build it, I was not able to build because of the improved URL validation (especially with URL.parse()) that should be the same reason why the build in CI is not passing. I had to revert that commit locally to build.
> 
> 
> 
> Adding the 'url' package with yarn add would fix that issue. Though i do not know what the projects' rules are regarding the adding of packages.

Thanks for sharing, I was totally convinced this was already there. I didn't even though about this.

2024-02-03 11:32 UTC, BartvanLaar commented
Is the OP @michaelhthomas still actively working on this or should we work it? Cause i'd like these issues to be resolved, but don't want to bypass the OP.

2024-02-17 05:39 UTC, TheEmpty commented
> Thank you for the suggestion! This seems to have changed things albeit still no successful login. I get the same authorization error in jellyseerr, and looking at the logs there is now new error description:
>
> Failed OIDC login attempt {"cause":"Invalid jwt or missing claims","ip":"my.current.public.ip","idToken":"very_long_string","errorMessage":"The token iss value doesn't match the oidc_DOMAIN (https://auth.my-domain.com/)"}
>
> The https://auth.my-domain.com/ is correct for and matches the settings in jellyseerr as well, so not sure what is wrong and where,

I ran into this too, what I am seeing on the debugging site is `https://auth.mydomain.cloud` BUT Jellyseerr is saying it fails because it's looking for `https://auth.mydomain.cloud/` note the trailing slash. The trailing slash is also showing in the UI though I did not add it there. Removing it, hitting save, reloading, and clicking edit again shows the slash comes back. Is the trailing slash a red-herring or root cause?

2024-02-17 15:14 UTC, TheEmpty commented
Okay yeah manually editing `settings.json` to remove the slash and restarting the service worked fine.

2024-02-23 05:02 UTC, Fallenbagel commented
> Adding the 'url' package with yarn add would fix that issue. Though i do not know what the projects' rules are regarding the adding of 

No rules. If its required for the PR to work, go right ahead c:

2024-02-23 05:33 UTC, Fallenbagel commented
> Adding the 'url' package with yarn add would fix that issue. Though i do not know what the projects' rules are regarding the adding of packages.

I dont think so. `url.canParse()` is a method that was added recently to javascript see:
https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static
https://www.stefanjudis.com/blog/validate-urls-in-javascript/ (for more examples)

That method does not exist in the [url package](https://www.npmjs.com/package/url) either:

> The following methods are provided by the URL module:
> url.parse(urlStr, [parseQueryString], [slashesDenoteHost])
> url.format(urlObj)
> url.resolve(from, to)

2024-02-29 22:55 UTC, Forceu commented
OIDC support would be extremely useful for me! I tried the latest docker image with the OIDC preview, unfortunately the redirect_uri is always in http instead of https, and therefore a login is not possible. Is there any way to set the jellyseerr URL for that? I already tried changing my nginx configuration, but unfortunately nothing seemed to help...

```
server {
        listen 443 ssl;
        ssl_certificate /etc/letsencrypt/live/xxxxx/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxxxxx/privkey.pem;

	client_body_buffer_size 128k;


        server_name request.xxxxx;

    include snippets/authelia.conf;

	location / {

        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Forwarded-Proto https;

        proxy_pass http://127.0.0.1:5055;
        proxy_set_header X-Forwarded-Host $server_name;



       include snippets/auth.conf;
	}



        if ( $scheme = http ) {
		return 301 https://$server_name$request_uri;
        }

	

        location ~ /\.ht {
                deny all;
        }
}
```

2024-02-29 23:29 UTC, TheEmpty commented
Scheme should be part of the configuration. Might manually edit config.json and restart if the UI changes aren’t taking. My jellyseerr is on https as well so maybe part of that.Sent from my iPhoneOn Feb 29, 2024, at 5:55 PM, Marc Ole Bulling ***@***.***> wrote:﻿
OIDC support would be extremely useful for me! I tried the latest docker image with the OIDC preview, unfortunately the redirect_uri is always in http instead of https, and therefore a login is not possible. Is there any way to set the jellyseerr URL for that? I already tried changing my nginx configuration, but unfortunately nothing seemed to help...
server {
        listen 443 ssl;
        ssl_certificate /etc/letsencrypt/live/xxxxx/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxxxxx/privkey.pem;

	client_body_buffer_size 128k;


        server_name request.xxxxx;

    include snippets/authelia.conf;

	location / {

        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Forwarded-Proto https;

        proxy_pass http://127.0.0.1:5055;
        proxy_set_header X-Forwarded-Host $server_name;



       include snippets/auth.conf;
	}



        if ( $scheme = http ) {
		return 301 https://$server_name$request_uri;
        }

	

        location ~ /\.ht {
                deny all;
        }
}


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-03-17 12:05 UTC, BreakingBread0 commented
For anyone having problems with timeouts (/api/v1/* pages taking ages to load) like I had, make sure that your config directory which got created has the same permissions as the user the container runs as. My config files got created as root, so after changing the owner (`chown -R xxx:yyy jellyseer`) it started working again.

2024-03-24 16:08 UTC, keesfluitman commented
thanks for this! ill keep this running. couldnt get ombi header auth to work so ill stick to this dev tag :)

2024-03-26 17:12 UTC, michaelhthomas commented
@Fallenbagel I would love to get this merged soon. What is left to be done before this can be reviewed / merged?

2024-03-26 17:20 UTC, michaelhthomas commented
@zeitue 
> ## Questions
> 
> - One thing that is not good is the redirect URL won't work unless it uses HTTP only. Is there some hard-coded HTTP part of the URL or something?

The redirect URl should definitely work with `https`, so long as your Jellyseerr server is properly configured and has a valid cert. What are you attempting to redirect to that isn't working as expected?

>  - Is there a way to get the Required claims to check if the user is in a certain group? I have a `groups` scope that returns an array of groups.

I think this would be beyond the scope of this PR. As a workaround, I would recommend adding a boolean claim that represents a user's membership in the particular group you'd like to check. This should be pretty straightforward with Authentik

2024-03-26 20:18 UTC, Bretterteig commented
> @zeitue
> 
> > ## Questions
> > 
> > * One thing that is not good is the redirect URL won't work unless it uses HTTP only. Is there some hard-coded HTTP part of the URL or something?
> 
> The redirect URl should definitely work with `https`, so long as your Jellyseerr server is properly configured and has a valid cert. What are you attempting to redirect to that isn't working as expected?
> 
> > * Is there a way to get the Required claims to check if the user is in a certain group? I have a `groups` scope that returns an array of groups.
> 
> I think this would be beyond the scope of this PR. As a workaround, I would recommend adding a boolean claim that represents a user's membership in the particular group you'd like to check. This should be pretty straightforward with Authentik

Used this exect method to limit access. Works like a charm.

+1 for merge

2024-03-31 07:23 UTC, zeitue commented
> @zeitue
> 
> > ## Questions
> > 
> > * One thing that is not good is the redirect URL won't work unless it uses HTTP only. Is there some hard-coded HTTP part of the URL or something?
> 
> The redirect URl should definitely work with `https`, so long as your Jellyseerr server is properly configured and has a valid cert. What are you attempting to redirect to that isn't working as expected?
> 
> > * Is there a way to get the Required claims to check if the user is in a certain group? I have a `groups` scope that returns an array of groups.
> 
> I think this would be beyond the scope of this PR. As a workaround, I would recommend adding a boolean claim that represents a user's membership in the particular group you'd like to check. This should be pretty straightforward with Authentik

Yeah, I got it working with HTTPS after restarting the server; I don't know why it didn't take effect for me until then.

2024-04-05 11:53 UTC, sim-maz commented
Almost two years since this PR was opened. What are the reasons for not merging this yet? Really the only app missing in my setup that I can't have SSO setup yet.

2024-04-05 13:04 UTC, yeyeoke commented
Same here, been using it since 4 months I think, with 11 users from Authentic. Not one has complained (they would've if they'd experienced any issues).

2024-04-05 13:07 UTC, kassarole commented
Been using this PR pretty much since there was a docker image available for roughly 30 users without issue. Would love to see this merged

2024-04-17 11:59 UTC, MiguelNdeCarvalho commented
Hey, is there anything left to be done before this PR can be merged? Thanks!

2024-04-18 10:08 UTC, Fallenbagel commented
> Hey, is there anything left to be done before this PR can be merged? Thanks!

I just need to review this pr and we should be good. Targetting a future version of jellyseerr. 

Maybe after I finish refactoring jellyfin api to use apikeys instead of auth tokens

2024-04-18 12:50 UTC, thcrt commented
FWIW, I'd also _love_ to see this merged. I run Jellyseerr on a seedbox where my app installation is limited so I can't install and run the preview unfortunately.

2024-04-21 13:54 UTC, Scot-Survivor commented
Before this is merged I want to report a bug I've had with this branch:
```
2024-04-21T13:51:13.335Z [error]: Failed OIDC login attempt {"cause":"Unknown error","ip":"<REDACTED>","errorMessage":"SQLITE_CONSTRAINT: UNIQUE constraint failed: user.email"}
```

Sometimes when users sign in with OIDC it appears JellySeerr tries to create an account, rather than use the already existing account, the only fix I've found is to delete the user's account so that it can be recreated. 

I use Keycloak as my OIDC provider, feel free to ping me with more questions,

Cheers,
Scot

2024-04-21 17:17 UTC, BreakingBread0 commented
> Before this is merged I want to report a bug I've had with this branch:
> 
> ```
> 2024-04-21T13:51:36.899Z [info]: Creating user for <REDACTED> {"ip":"<REDACTED>","email":"<REDACTED>"}
> 2024-04-21T13:51:13.335Z [error]: Failed OIDC login attempt {"cause":"Unknown error","ip":"<REDACTED>","errorMessage":"SQLITE_CONSTRAINT: UNIQUE constraint failed: user.email"}
> ```
> 
> Sometimes when users sign in with OIDC it appears JellySeerr tries to create an account, rather than use the already existing account, the only fix I've found is to delete the user's account so that it can be recreated.
> 
> I use Keycloak as my OIDC provider, feel free to ping me with more questions,
> 
> Cheers, Scot

I also had that bug. Turns out that my emails were lowercase and uppercase, but jellyseerr saves them lowercase. When I added a custom property mapping in Authentik to make all emails lowercase in the reply, it started to work.

2024-04-21 18:35 UTC, Scot-Survivor commented
Ahh happy to hear there's a fix and more importantly why it happens, I'd like to see them apply the same modifier to the email from the OIDC provider (as in, make the email lower case) though, and believe this needs to be on the app side and not the provider side. 

Furthermore, I do not believe Keycloak has the ability to do what you did and I'd rather not write it in myself haha

Hopefully the contributors see this, 

- Emails are saved in lowercase 
- JellySeerr does not apply the same function to the email from the OIDC field
This should be corrected

2024-04-24 07:02 UTC, kartik2406 commented
I am facing one issue with the auth. It redirects from my provider (authetnik) back to jellyseerr but I get this error in the logs.
 
`[info]: Failed OIDC login attempt {"cause":"Invalid jwt or missing claims","ip":":redacted","idToken":"<redacted></redacted>","errorMessage":"email must be a `boolean` type, but the final value was: `\"redacted_string\"`."}
`

I verified that the jwt contins my email. For some reason the code expects it to be an boolean. Is this something to do with the email_verified field? Would appretiate any help on this.

2024-04-24 19:37 UTC, zeitue commented
Is there a more up to date docker image than the [preview-OIDC](https://hub.docker.com/layers/fallenbagel/jellyseerr/preview-OIDC/images/sha256-4d9c3c3bf1b9d962ab955f8bad492f9b1c2b7a0a1605a6c464815a78210876da?context=explore) image?

2024-04-24 19:39 UTC, Fallenbagel commented
> Is there a more up to date docker image than the [preview-OIDC](https://hub.docker.com/layers/fallenbagel/jellyseerr/preview-OIDC/images/sha256-4d9c3c3bf1b9d962ab955f8bad492f9b1c2b7a0a1605a6c464815a78210876da?context=explore) image?

I'll be updating the tag tonight

2024-04-26 14:50 UTC, kartik2406 commented
> > Is there a more up to date docker image than the [preview-OIDC](https://hub.docker.com/layers/fallenbagel/jellyseerr/preview-OIDC/images/sha256-4d9c3c3bf1b9d962ab955f8bad492f9b1c2b7a0a1605a6c464815a78210876da?context=explore) image?
> 
> I'll be updating the tag tonight

Could you please update the tag? Wanted to check if the issues I am facing are resolved in it.

2024-04-26 14:59 UTC, Fallenbagel commented
> Could you please update the tag? Wanted to check if the issues I am facing are resolved in it.

It's building. Might take 1-2 hrs depending

2024-04-27 16:51 UTC, zeitue commented
Thanks for updating the image.

I updated to the new preview-OIDC image, and it works well. However, I had to add an option to my environment for it to work behind a reverse proxy, I don't know if an update to the server did this, but I figured I'd put it here if anyone else has the issue.
```bash
NODE_OPTIONS='--dns-result-order=ipv4first'
```

2024-04-27 22:04 UTC, M0NsTeRRR commented
> Thanks for updating the image.
> 
> I updated to the new preview-OIDC image, and it works well. However, I had to add an option to my environment for it to work behind a reverse proxy, I don't know if an update to the server did this, but I figured I'd put it here if anyone else has the issue.
> 
> ```shell
> NODE_OPTIONS='--dns-result-order=ipv4first'
> ```

It doesn't come from this PR. Your IPv6 setup is broken. See my comment here : https://github.com/Fallenbagel/jellyseerr/issues/722#issuecomment-2067363186

If you use Jellyfin, you have to enable IPv6. For the others, you need to check if it's enabled too.

2024-04-27 22:53 UTC, Fallenbagel commented
> If you use Jellyfin, you have to enable IPv6 in the admin web interface. For the others, you need to check if it's enabled too.

Or if you don't use ipv6, you can also disable it on OS level

2024-04-27 23:38 UTC, M0NsTeRRR commented
> > If you use Jellyfin, you have to enable IPv6 in the admin web interface. For the others, you need to check if it's enabled too.
> 
> Or if you don't use ipv6, you can also disable it on OS level

IPv6 is disabled by default on docker, kubernetes etc... so I assume he use it :smile:

2024-04-28 02:38 UTC, Fallenbagel commented
> IPv6 is disabled by default on docker, kubernetes etc... so I assume he uses it :smile:
> Also disabling ipv6 on purpose with sysctl call it's never a good idea as it breaks things.

Yes I meant if they never use it. In my case, i can disable it. Our isp doesn't support it either 😔

2024-05-04 04:44 UTC, crltc commented
On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:

`"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`

2024-05-04 22:46 UTC, 4WaYDp commented
> On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:
> 
> `"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`

You should enable _'Enable Proxy Support'_ in jellyseeerr settings.

2024-05-05 05:11 UTC, crltc commented
> > On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:
> > `"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`
> 
> You should enable _'Enable Proxy Support'_ in jellyseeerr settings.

Thank you! That fixed my issue and everything is now working as expected with Authentik.

2024-05-05 21:34 UTC, chinyongcy commented
> > > On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:
> > > `"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`
> > 
> > 
> > You should enable _'Enable Proxy Support'_ in jellyseeerr settings.
> 
> Thank you! That fixed my issue and everything is now working as expected with Authentik.

How did you get it to work with Authentik?
1. I have created a custom property mapping 
`if ak_is_group_member(request.user, name="Jellyfin_Users"):
    return {"jellyfinuser": True} ‘
2. In my Application Provider, I added to scope 
![IMG_4448](https://github.com/Fallenbagel/jellyseerr/assets/55968202/e7360cdc-a30c-4adf-b09b-dc6c2dd68b23)
3. Then in jellyseer added the scope and required claims
![IMG_4450](https://github.com/Fallenbagel/jellyseerr/assets/55968202/7e394943-cc65-4de2-a713-76652721e5a7)

5. But in the docker logs when I try to log in I will get something like ‘jellyfinusers’ is a required field

7. I decoded the token and ‘jellyfinuser’ is not shown. But in my authentik Jellyfin provider I can see that the preview for user ‘jellyfinuser’ is there 

Try for the whole night as for now I’m just using ‘email_verified’ for the claims as a workaround. Am trying to set it up the right way

2024-05-07 02:57 UTC, crltc commented
> > > > On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:
> > > > `"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`
> > > 
> > > 
> > > You should enable _'Enable Proxy Support'_ in jellyseeerr settings.
> > 
> > 
> > Thank you! That fixed my issue and everything is now working as expected with Authentik.
> 
> How did you get it to work with Authentik?
> 
>     1. I have created a custom property mapping
>        `if ak_is_group_member(request.user, name="Jellyfin_Users"):
>        return {"jellyfinuser": True} ‘
> 
>     2. In my Application Provider, I added to scope
>        ![IMG_4448](https://private-user-images.githubusercontent.com/55968202/328050794-e7360cdc-a30c-4adf-b09b-dc6c2dd68b23.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDk0NDgsIm5iZiI6MTcxNTA0OTE0OCwicGF0aCI6Ii81NTk2ODIwMi8zMjgwNTA3OTQtZTczNjBjZGMtYTMwYy00YWRmLWIwOWItZGM2YzJkZDY4YjIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMjMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzAzYjM2YWZjNTUwMmY0YjIzN2NkNmM5MjA3OTUyMWVhNDhhZDE4YTM3YTVlM2FlZGVlOWFiMWI0OTEwZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxYdhWGKRJhKcxoNYMPwnYwcp3xpKviCbTFk2luaJ4s)
> 
>     3. Then in jellyseer added the scope and required claims
>        ![IMG_4450](https://private-user-images.githubusercontent.com/55968202/328051096-7e394943-cc65-4de2-a713-76652721e5a7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDk0NDgsIm5iZiI6MTcxNTA0OTE0OCwicGF0aCI6Ii81NTk2ODIwMi8zMjgwNTEwOTYtN2UzOTQ5NDMtY2M2NS00ZGUyLWE3MTMtNzY2NTI3MjFlNWE3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMjMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2ZhZmMzZmVkYjkwYTBkMjE0Njc0MGI4OGNiMmM2Njg4ZWJhYmFmNDMyNWVmZGFjNTZiMjAwYmE1ZDBhYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Dh9s0bKUbiN5ZfFVBA7PtLOcefA6cLLYz33Y_YFp34)
> 
>     4. But in the docker logs when I try to log in I will get something like ‘jellyfinusers’ is a required field
> 
>     5. I decoded the token and ‘jellyfinuser’ is not shown. But in my authentik Jellyfin provider I can see that the preview for user ‘jellyfinuser’ is there
> 
> 
> Try for the whole night as for now I’m just using ‘email_verified’ for the claims as a workaround. Am trying to set it up the right way

Below are the settings that worked for me. Don't forget to add your user to the group (it's obvious but easy to overlook).

**Jellyseerr OpenID Connect Configuration**
Scopes: email openid profile jellyfin
Identification Claims: preferred_username
Required Claims: jellyfin

**Authentik Custom Property Mapping**
Name: authentik OAuth Mapping: OpenID 'jellyfin'
Scope Name: jellyfin
Expression:
```
jellyfin_claims = {}
if request.user.ak_groups.filter(name="jellyfin").exists():
    jellyfin_claims["jellyfin"]= True
return jellyfin_claims
```

2024-05-07 03:27 UTC, chinyongcy commented
> > > > > On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:
> > > > > `"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`
> > > > 
> > > > 
> > > > You should enable _'Enable Proxy Support'_ in jellyseeerr settings.
> > > 
> > > 
> > > Thank you! That fixed my issue and everything is now working as expected with Authentik.
> > 
> > 
> > How did you get it to work with Authentik?
> > ```
> > 1. I have created a custom property mapping
> >    `if ak_is_group_member(request.user, name="Jellyfin_Users"):
> >    return {"jellyfinuser": True} ‘
> > 
> > 2. In my Application Provider, I added to scope
> >    ![IMG_4448](https://private-user-images.githubusercontent.com/55968202/328050794-e7360cdc-a30c-4adf-b09b-dc6c2dd68b23.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDk0NDgsIm5iZiI6MTcxNTA0OTE0OCwicGF0aCI6Ii81NTk2ODIwMi8zMjgwNTA3OTQtZTczNjBjZGMtYTMwYy00YWRmLWIwOWItZGM2YzJkZDY4YjIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMjMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzAzYjM2YWZjNTUwMmY0YjIzN2NkNmM5MjA3OTUyMWVhNDhhZDE4YTM3YTVlM2FlZGVlOWFiMWI0OTEwZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxYdhWGKRJhKcxoNYMPwnYwcp3xpKviCbTFk2luaJ4s)
> > 
> > 3. Then in jellyseer added the scope and required claims
> >    ![IMG_4450](https://private-user-images.githubusercontent.com/55968202/328051096-7e394943-cc65-4de2-a713-76652721e5a7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDk0NDgsIm5iZiI6MTcxNTA0OTE0OCwicGF0aCI6Ii81NTk2ODIwMi8zMjgwNTEwOTYtN2UzOTQ5NDMtY2M2NS00ZGUyLWE3MTMtNzY2NTI3MjFlNWE3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMjMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2ZhZmMzZmVkYjkwYTBkMjE0Njc0MGI4OGNiMmM2Njg4ZWJhYmFmNDMyNWVmZGFjNTZiMjAwYmE1ZDBhYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Dh9s0bKUbiN5ZfFVBA7PtLOcefA6cLLYz33Y_YFp34)
> > 
> > 4. But in the docker logs when I try to log in I will get something like ‘jellyfinusers’ is a required field
> > 
> > 5. I decoded the token and ‘jellyfinuser’ is not shown. But in my authentik Jellyfin provider I can see that the preview for user ‘jellyfinuser’ is there
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Try for the whole night as for now I’m just using ‘email_verified’ for the claims as a workaround. Am trying to set it up the right way
> 
> Below are the settings that worked for me. Don't forget to add your user to the group (it's obvious but easy to overlook).
> 
> **Jellyseerr OpenID Connect Configuration** Scopes: email openid profile jellyfin Identification Claims: preferred_username Required Claims: jellyfin
> 
> **Authentik Custom Property Mapping** Name: authentik OAuth Mapping: OpenID 'jellyfin' Scope Name: jellyfin Expression:
> 
> ```
> jellyfin_claims = {}
> if request.user.ak_groups.filter(name="jellyfin").exists():
>     jellyfin_claims["jellyfin"]= True
> return jellyfin_claims
> ```

Thank you for the settings. I did almost the same as well, but still not able to get it.
**In Authentik:**
Property Mappings:
![image](https://github.com/Fallenbagel/jellyseerr/assets/55968202/1a6f7bb0-597a-4950-9581-e9631d7e31a8)

Provider Scope:
![image](https://github.com/Fallenbagel/jellyseerr/assets/55968202/89013f7d-25ad-4cfd-b1a6-bad3e7b7ffdc)

JWT Preview Payload:
![image](https://github.com/Fallenbagel/jellyseerr/assets/55968202/e82093b6-88f9-4d93-886a-63089dd074dd)

Go to my Profile -> Consent -> Remove Jellyseer first. (To start fresh without consent, not sure if it matters)

**In Jellyseer:**
![image](https://github.com/Fallenbagel/jellyseerr/assets/55968202/1b293fe5-48ae-422c-9b8c-5b03ba60a9a7)


I am still getting auth error.
<img width="282" alt="image" src="https://github.com/Fallenbagel/jellyseerr/assets/55968202/dec3f3f2-4be4-43c6-9e1c-45e53692effe">

This is what I get in logs
Failed OIDC login attempt {"cause":"Invalid jwt or missing claims","ip":"10.0.0.70","idToken":"<Redacted>","errorMessage":"jellyfin is a required field"}
Decoded in jwt.io
![image](https://github.com/Fallenbagel/jellyseerr/assets/55968202/32affa85-b3c0-4fc1-aea6-672c0607f632)
 
Been trying the same since 2 days back, tried restarting both authentik and jellyseer container.
Seems like the scope is not getting updated, if not I think that my previous settings should have worked as well.

Just in case i use the wrong image tag. This is what I use "fallenbagel/jellyseerr:preview-OIDC" in my docker compose.

2024-05-07 04:10 UTC, crltc commented
> > > > > > On the latest preview (as of the date of this post) I am running into the http redirect uri issue that a few others mentioned. My Jellyseerr instance is configured with a valid cert and the URL in the settings is set to https. In my case restarting and reconfiguring did not resolve the issue. Below is what I see from authentik server logs:
> > > > > > `"redirect_uri_expected": ["https://jellyseerr.domain.com/login/oidc/callback"], "redirect_uri_given": "http://jellyseerr.domain.com/login/oidc/callback",`
> > > > > 
> > > > > 
> > > > > You should enable _'Enable Proxy Support'_ in jellyseeerr settings.
> > > > 
> > > > 
> > > > Thank you! That fixed my issue and everything is now working as expected with Authentik.
> > > 
> > > 
> > > How did you get it to work with Authentik?
> > > ```
> > > 1. I have created a custom property mapping
> > >    `if ak_is_group_member(request.user, name="Jellyfin_Users"):
> > >    return {"jellyfinuser": True} ‘
> > > 
> > > 2. In my Application Provider, I added to scope
> > >    ![IMG_4448](https://private-user-images.githubusercontent.com/55968202/328050794-e7360cdc-a30c-4adf-b09b-dc6c2dd68b23.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDk0NDgsIm5iZiI6MTcxNTA0OTE0OCwicGF0aCI6Ii81NTk2ODIwMi8zMjgwNTA3OTQtZTczNjBjZGMtYTMwYy00YWRmLWIwOWItZGM2YzJkZDY4YjIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMjMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzAzYjM2YWZjNTUwMmY0YjIzN2NkNmM5MjA3OTUyMWVhNDhhZDE4YTM3YTVlM2FlZGVlOWFiMWI0OTEwZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MxYdhWGKRJhKcxoNYMPwnYwcp3xpKviCbTFk2luaJ4s)
> > > 
> > > 3. Then in jellyseer added the scope and required claims
> > >    ![IMG_4450](https://private-user-images.githubusercontent.com/55968202/328051096-7e394943-cc65-4de2-a713-76652721e5a7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDk0NDgsIm5iZiI6MTcxNTA0OTE0OCwicGF0aCI6Ii81NTk2ODIwMi8zMjgwNTEwOTYtN2UzOTQ5NDMtY2M2NS00ZGUyLWE3MTMtNzY2NTI3MjFlNWE3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMjMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2ZhZmMzZmVkYjkwYTBkMjE0Njc0MGI4OGNiMmM2Njg4ZWJhYmFmNDMyNWVmZGFjNTZiMjAwYmE1ZDBhYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Dh9s0bKUbiN5ZfFVBA7PtLOcefA6cLLYz33Y_YFp34)
> > > 
> > > 4. But in the docker logs when I try to log in I will get something like ‘jellyfinusers’ is a required field
> > > 
> > > 5. I decoded the token and ‘jellyfinuser’ is not shown. But in my authentik Jellyfin provider I can see that the preview for user ‘jellyfinuser’ is there
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Try for the whole night as for now I’m just using ‘email_verified’ for the claims as a workaround. Am trying to set it up the right way
> > 
> > 
> > Below are the settings that worked for me. Don't forget to add your user to the group (it's obvious but easy to overlook).
> > **Jellyseerr OpenID Connect Configuration** Scopes: email openid profile jellyfin Identification Claims: preferred_username Required Claims: jellyfin
> > **Authentik Custom Property Mapping** Name: authentik OAuth Mapping: OpenID 'jellyfin' Scope Name: jellyfin Expression:
> > ```
> > jellyfin_claims = {}
> > if request.user.ak_groups.filter(name="jellyfin").exists():
> >     jellyfin_claims["jellyfin"]= True
> > return jellyfin_claims
> > ```
> 
> Thank you for the settings. I did almost the same as well, but still not able to get it. **In Authentik:** Property Mappings: ![image](https://private-user-images.githubusercontent.com/55968202/328375317-1a6f7bb0-597a-4950-9581-e9631d7e31a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ1NjQsIm5iZiI6MTcxNTA1NDI2NCwicGF0aCI6Ii81NTk2ODIwMi8zMjgzNzUzMTctMWE2ZjdiYjAtNTk3YS00OTUwLTk1ODEtZTk2MzFkN2UzMWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNWRhMWI1MTkwY2E5MmE3MjQxMzgwYjk1M2U2ZTYyNTY1NjE1YTEzMzZkMjk0NzAwODc4ZDMyOTlhNmUyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHX4Ojnr0LQGB1uapQeTs_IYBSZHIRBGfAPXDgbpuPU)
> 
> Provider Scope: ![image](https://private-user-images.githubusercontent.com/55968202/328375446-89013f7d-25ad-4cfd-b1a6-bad3e7b7ffdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ1NjQsIm5iZiI6MTcxNTA1NDI2NCwicGF0aCI6Ii81NTk2ODIwMi8zMjgzNzU0NDYtODkwMTNmN2QtMjVhZC00Y2ZkLWIxYTYtYmFkM2U3YjdmZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMTczMTM1ZjNjODhjMzEwZjgxNDkwNDMzNGVlOWQ5ZTM0ZmYwMzdmMTc3YTAyNjQxMjQ4MjFhOGY3YTYwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d_R-ALa84KREHrPUIzKTvH-oNXikII2gXTjsBuNgVHA)
> 
> JWT Preview Payload: ![image](https://private-user-images.githubusercontent.com/55968202/328375974-e82093b6-88f9-4d93-886a-63089dd074dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ1NjQsIm5iZiI6MTcxNTA1NDI2NCwicGF0aCI6Ii81NTk2ODIwMi8zMjgzNzU5NzQtZTgyMDkzYjYtODhmOS00ZDkzLTg4NmEtNjMwODlkZDA3NGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTJlY2IzMjcwYzYzNzgyYzkzZWI0Zjc5NWM1MWVhMDUxY2YzZGE2ZDU2NThhNTIwYjVkZGM4MTA3NTk1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wbycODiYW8JMNzlz7OafC_iTP5opLG66wXKNElZw5VE)
> 
> Go to my Profile -> Consent -> Remove Jellyseer first. (To start fresh without consent, not sure if it matters)
> 
> **In Jellyseer:** ![image](https://private-user-images.githubusercontent.com/55968202/328376155-1b293fe5-48ae-422c-9b8c-5b03ba60a9a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ1NjQsIm5iZiI6MTcxNTA1NDI2NCwicGF0aCI6Ii81NTk2ODIwMi8zMjgzNzYxNTUtMWIyOTNmZTUtNDhhZS00MjJjLTliOGMtNWIwM2JhNjBhOWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMjFiMGFlOTJlNThkMGNhYTViYmVkZmYwNWM0ZmM2MmE3ODQyNGMzMzY5YmQ5MTAzOWVkM2NlMTQ4MDUxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JiK3tu6E1FVK0Y435T3a5b_LSgzbRnUAdPwzmshykA4)
> 
> I am still getting auth error. <img alt="image" width="282" src="https://private-user-images.githubusercontent.com/55968202/328376682-dec3f3f2-4be4-43c6-9e1c-45e53692effe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ1NjQsIm5iZiI6MTcxNTA1NDI2NCwicGF0aCI6Ii81NTk2ODIwMi8zMjgzNzY2ODItZGVjM2YzZjItNGJlNC00M2M2LTllMWMtNDVlNTM2OTJlZmZl [...]

2024-05-07 04:27 UTC, chinyongcy commented
> It looks right to me and matches my setup, the only other thing I could say to check is the include_claims_in_id_token value in your oauth2 provider in Authentik for Jellyseerr. This is a snippet of what mine looks like (Terraform):
> 
> ```
>   client_type                = "confidential"
>   include_claims_in_id_token = true
>   issuer_mode                = "per_provider"
>   jwks_sources               = []
>   sub_mode                   = "hashed_user_id"
> ```
> 
> If not that then I'm not sure, hopefully someone else can take a look.
> 
> edit: I doubt the above is the issue but I'm out of ideas.
Ah that's cool, didn't know it can be configured with terraform. Love the idea, one more thing to my to do list!
Anyway I have the same setting in the UI
![image](https://github.com/Fallenbagel/jellyseerr/assets/55968202/5557345d-c8e5-432a-b783-93ef3f064ed1)

I guess the issue could be I upgrade "jellyseer:latest" directly to "preview-OIDC". Maybe over the weekend I will do a clean install and start over again.

Thank you so much!

2024-05-16 15:47 UTC, maarten-vdb commented
I've tried getting it to work with Authelia, but trying to set it up myself as well as using the configs mentioned above all result in a 401 error response. Does anyone have a working example config?

2024-05-20 07:29 UTC, gregismotion commented
It would work for me, but Jellyseer wants to redirect me to my local ip address+port combo, but it is under a reverse proxy.

(I ticked on the proxy support and set the App URL correctly)

2024-05-20 07:33 UTC, gregismotion commented
> It would work for me, but Jellyseer wants to redirect me to my local ip address+port combo, but it is under a reverse proxy.
> 
> (I ticked on the proxy support and set the App URL correctly)

Solved, had to add this to NGINX:
```
    proxy_set_header Referer $http_referer;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-Port $remote_port;
    proxy_set_header X-Forwarded-Host $host:$remote_port;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Port $remote_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Ssl on;
```

2024-05-20 10:07 UTC, NovaPreem commented
fwiw am on Authelia and it doesn't work due to the error above a lot of the time.
Gotten around it somewhat but requires DB intervention.

** WARNING: I recommend backing up your DB + config before attempting this if you do. **
1. Server is configured to `matchJellyfinAccounts=true`
2. Someone logs in, it creates a local user account.
3. Shut down server, copy the 3 db files to another folder.
4. Edit them using sqlite db editor: change their `users` entry to match the jellyfin accounts. Fill in dummy data in the other fields, and make sure the jellyfin mapping name is correct.
5. Write DB Changes, replace file. Start Jellyfin.
6. Fixed.

The unfortunate part is that you keep having to do this.  It wouldn't surprise me if the fix is related to https://github.com/Fallenbagel/jellyseerr/issues/183#issuecomment-1987550455 

But at this point I just needed it work.

2024-05-22 01:20 UTC, goodguybane commented
This works perfectly for me using Authentik and Plex including automatic login. I started from scratch and do not have any advanced config settings in NPM. 

Jellyseerr:
Issuer URL: https://auth.example.com/application/o/<application name>

Authentik Provider:
Redirect URI: https://jellyseerr.example.com/login/oidc/callback

![image](https://github.com/Fallenbagel/jellyseerr/assets/21113563/896f0d21-73c2-4071-8100-5aba0936b4c8)

2024-05-24 23:53 UTC, NetDude12 commented
> This works perfectly for me using Authentik and Plex including automatic login. I started from scratch and do not have any advanced config settings in NPM.
> 
> Jellyseerr: Issuer URL: https://auth.example.com/application/o/applicationname
> 
> Authentik Provider: Redirect URI: https://jellyseerr.example.com/login/oidc/callback
> 
> ![image](https://private-user-images.githubusercontent.com/21113563/332623929-896f0d21-73c2-4071-8100-5aba0936b4c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTQ4MjYsIm5iZiI6MTcxNjU5NDUyNiwicGF0aCI6Ii8yMTExMzU2My8zMzI2MjM5MjktODk2ZjBkMjEtNzNjMi00MDcxLTgxMDAtNWFiYTA5MzZiNGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDIzNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1OWRjODI5MjQ5NzIwMjhkOWEyYzc0N2YxNTZiNjUxNTNlODBiYWRjYTNmMWE0ODNiMDRiOTYyOWExZDNkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TxClNMYtyP5QemCX9QA3ObKqstGh6fMK9bdCBt2g4PY)

Just wanted to confirm that this working for me right out of the box.

2024-05-28 04:27 UTC, crltc commented
Interestingly enough, I have not touched my jellyseerr setup for a few weeks after getting it working using the parameters I included my previous posts. Now when I logged in I noticed that that my OIDC settings reset to default and among changing them back to what I originally had working - I get the same error that @chinyongcy has. Not sure where to start troubleshooting. Note that my volumes are static and haven't been reset.

2024-05-28 18:04 UTC, emielpopla commented
I have tried the implementation with Zitadel.
It seems to work well but there is just one little issue. 
The redirect_uri I get is a http:// url instead of https:// : http://jellyseer.example.om/login/oidc/callback/
If I add this one to my redirect URIs it works but I have to put my project in Development Mode, which I don't want to do.

2024-05-28 18:11 UTC, emielpopla commented
> I have tried the implementation with Zitadel. It seems to work well but there is just one little issue. The redirect_uri I get is a http:// url instead of https:// : http://jellyseer.example.om/login/oidc/callback If I add this one to my redirect URIs it works but I have to put my project in Development Mode, which I don't want to do.

EDIT: Nevermind I enabled 'Proxy Support' and 'CSRF Protection' and that seems to solve that issue. Can confirm that for Zitadel as OIDC provider it works nicely

2024-05-28 22:02 UTC, 4WaYDp commented
I have set up oidc with Authelia; everything works fine except that _Full Library Scan_ and _Recently Added Scan_ stopped working. There are no errors thrown, not on Jellyseeer nor with Emby server. The owner-user can login with oidc and is of type jellyfin user (3). Is anybody else having these problems?

2024-05-29 07:35 UTC, jorti commented
> I have set up oidc with Authelia; everything works fine except that _Full Library Scan_ and _Recently Added Scan_ stopped working. There are no errors thrown, not on Jellyseeerr and not Emby. The owner-user can login with oidc and is of type Emby user (3). Is anybody else having these problems?

I have the same problem. Jellyseerr fails to access the Jellyfin API, so things like the sync or scan of the Jellyfin libraries don't work.

2024-05-29 07:56 UTC, Fallenbagel commented
> > I have set up oidc with Authelia; everything works fine except that _Full Library Scan_ and _Recently Added Scan_ stopped working. There are no errors thrown, not on Jellyseeerr and not Emby. The owner-user can login with oidc and is of type Emby user (3). Is anybody else having these problems?
> 
> I have the same problem. Jellyseerr fails to access the Jellyfin API, so things like the sync or scan of the Jellyfin libraries don't work.

Can you share your logs. When you press sync or scan. Need more info.

2024-05-29 08:55 UTC, jorti commented
> > > I have set up oidc with Authelia; everything works fine except that _Full Library Scan_ and _Recently Added Scan_ stopped working. There are no errors thrown, not on Jellyseeerr and not Emby. The owner-user can login with oidc and is of type Emby user (3). Is anybody else having these problems?
> > 
> > 
> > I have the same problem. Jellyseerr fails to access the Jellyfin API, so things like the sync or scan of the Jellyfin libraries don't work.
> 
> Can you share your logs. When you press sync or scan. Need more info.

I'm using the latest container image `docker.io/fallenbagel/jellyseerr:preview-OIDC`.
The only message I get when I click on "Sync libraries" is:

```
2024-05-29T08:37:37.111Z [error][Jellyfin API]: Something went wrong while getting libraries from the Jellyfin server: Request failed with status code 404
```

If I configure the Jellyfin internal URL to be my reverse proxy, I can see that the failed request goes to the `/Users//Views` Jellyfin endpoint:

```
192.168.1.1 - - [29/May/2024:08:48:27 +0000] "GET /Users//Views HTTP/1.1" 404 988 "-" "-" 104003 "jellyfin@docker" "http://10.89.0.117:80" 1ms
```

It looks like the double slash is causing problems:

```
# curl -I https://jellyfin.example.com/Users//View
HTTP/2 404 
accept-ranges: bytes
alt-svc: h3=":443"; ma=2592000
content-type: text/html
date: Wed, 29 May 2024 08:51:52 GMT
etag: "65b785cb-3dc"
last-modified: Mon, 29 Jan 2024 11:02:35 GMT
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
content-length: 988

# curl -I https://jellyfin.example.com/Users/View
HTTP/2 405 
allow: DELETE, GET, POST
alt-svc: h3=":443"; ma=2592000
date: Wed, 29 May 2024 08:51:54 GMT
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-response-time-ms: 7.4041
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
```

The relevant parts of the `settings.json` file:

```
 "main": {
  "apiKey": "REDACTED",
  "applicationTitle": "Jellyseerr",
  "applicationUrl": "https://jellyseerr.example.com",
  "csrfProtection": true,
  "cacheImages": false,
  "defaultPermissions": 71303200,
  "defaultQuotas": {
   "movie": {
    "quotaLimit": 0,
    "quotaDays": 7
   },
   "tv": {
    "quotaLimit": 0,
    "quotaDays": 7
   }
  },
  "hideAvailable": false,
  "localLogin": false,
  "mediaServerLogin": true,
  "newPlexLogin": true,
  "oidcLogin": true,
  "oidc": {
   "providerName": "Authelia",
   "providerUrl": "https://auth.example.com",
   "clientId": "jellyseerr",
   "clientSecret": "REDACTED",
   "userIdentifier": "preferred_username",
   "requiredClaims": "email_verified",
   "scopes": "email openid profile groups",
   "matchJellyfinUsername": true,
   "automaticLogin": false
  },
  "region": "ES",
  "originalLanguage": "",
  "trustProxy": true,
  "mediaServerType": 2,
  "partialRequestsEnabled": true,
  "locale": "es"
 },
 "jellyfin": {
  "name": "",
  "hostname": "http://jellyfin:8096",
  "externalHostname": "https://jellyfin.example.com",
  "jellyfinForgotPasswordUrl": "https://auth.example.com/reset-password/step1",
  "libraries": [
   {
    "id": "ed2a25286c558a96e1424971742ca350",
    "name": "Movies",
    "enabled": true,
    "type": "movie"
   },
   {
    "id": "5ddaa59a73205234890fdcfc683e14ef",
    "name": "Shows",
    "enabled": true,
    "type": "show"
   }
  ],
  "serverId": "a0c6a6aff1ce4463c0a2eda775a310f9"
 },
```

In addition to that, I had to grant myself owner permissions by editing the database manually:

```
# sqlite3 /var/lib/containers/storage/volumes/jellyseerr/_data/db/db.sqlite3

sqlite> select id, email, username, permissions from user;
sqlite> update user set permissions = 3 where id = 1;
sqlite> .exit
```

2024-05-29 09:31 UTC, jorti commented
After a bit more digging I've found a workaround for the 404 errors when accessing the Jellyfin API. The problem is that Jellyseerr doesn't know my Jellyfin user id, so the call to `/Users/JELLYFIN_USER_ID/View` is incorrect.

I've discovered my user id and created an API key in Jellyfin, then added them to my user in Jellyseerr:

```
sqlite> select id, email, username, jellyfinUsername, jellyfinAuthToken, jellyfinUserId, jellyfinDeviceId from user;
1|username@example.com|username||||

sqlite> update user set jellyfinUsername = 'username', jellyfinUserId = 'JELLYFIN_USER_ID', jellyfinAuthToken = 'REDACTED'  where id = 1;
```

After that, the library scan works.

I think this Jellyfin API key setting should be a global option and not per-user.

2024-05-29 16:35 UTC, Fallenbagel commented
> > Just an fyi, the behavior of login, authtokens are already very different from this PR (I think this pr is about 2 versions old).
> 
> Yeah.... I'm thinking of just making a new PR based on the one upstream ([sct/overseerr#3746](https://github.com/sct/overseerr/pull/3746)) with some tweaks and additional features from this one. Since that might have a smaller scope, hopefully it could end up being merged more quickly. I could then make some smaller PRs with additional user interface and functionality improvements that aren't strictly necessary to get the feature released.

That would be great. Specifically the biggest change we're gonna get on auth is #773 and apikeys (we're gonna stop authtokensl

2024-05-31 20:20 UTC, Sapd commented
There is a bug at least in the latest build:

When a user has an email like **J**ohn.**Doe**@gmail.com in Authentik (watch at the upper-cases) and then trys to login, he will get an error and the log report:
```
SQLITE_CONSTRAINT: UNIQUE constraint failed: user.email"
```

Changing his email to lower case in Authentik fixes it.

2024-06-02 22:05 UTC, Scot-Survivor commented
> There is a bug at least in the latest build:
> 
> When a user has an email like **J**ohn.**Doe**@gmail.com in Authentik (watch at the upper-cases) and then trys to login, he will get an error and the log report:
> 
> ```
> SQLITE_CONSTRAINT: UNIQUE constraint failed: user.email"
> ```
> 
> Changing his email to lower case in Authentik fixes it.

Can confirm this bug still happens my side. And I am using Keycloak, so can't use this fix.

2024-06-07 15:06 UTC, maarten-vdb commented
I'm having problems (statuscode 401) getting the required claims working with "custom scopes". No matter what scopes I enter in the jellyseer oidc configuration, only "email openid profile" appear to be requested according to Authentik.

When the Required Claims value is something that is returned without needing a specific scope(email_verified), my problems with 401 errors are fixed. Have i messed up something or is this an actual bug?

2024-06-10 18:13 UTC, kartik2406 commented
> This works perfectly for me using Authentik and Plex including automatic login. I started from scratch and do not have any advanced config settings in NPM.
> 
> Jellyseerr: Issuer URL: https://auth.example.com/application/o/applicationname
> 
> Authentik Provider: Redirect URI: https://jellyseerr.example.com/login/oidc/callback
> 
> ![image](https://private-user-images.githubusercontent.com/21113563/332623929-896f0d21-73c2-4071-8100-5aba0936b4c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDIwODcsIm5iZiI6MTcxODA0MTc4NywicGF0aCI6Ii8yMTExMzU2My8zMzI2MjM5MjktODk2ZjBkMjEtNzNjMi00MDcxLTgxMDAtNWFiYTA5MzZiNGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE3NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYWNhNjRkMmY5YzNkMWM5MGY4OGRjNTIzMmZkZTE2NzBkNjQ4OWM5ODViMGE4NGY4YjFiNWYwN2Q3NWEzNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJGt0L-0JUJNnkTl_ZKdRnnvocbt2XUM5IpjaiX_OIk)



> This works perfectly for me using Authentik and Plex including automatic login. I started from scratch and do not have any advanced config settings in NPM.
> 
> Jellyseerr: Issuer URL: https://auth.example.com/application/o/applicationname
> 
> Authentik Provider: Redirect URI: https://jellyseerr.example.com/login/oidc/callback
> 
> ![image](https://private-user-images.githubusercontent.com/21113563/332623929-896f0d21-73c2-4071-8100-5aba0936b4c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDIwODcsIm5iZiI6MTcxODA0MTc4NywicGF0aCI6Ii8yMTExMzU2My8zMzI2MjM5MjktODk2ZjBkMjEtNzNjMi00MDcxLTgxMDAtNWFiYTA5MzZiNGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE3NDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYWNhNjRkMmY5YzNkMWM5MGY4OGRjNTIzMmZkZTE2NzBkNjQ4OWM5ODViMGE4NGY4YjFiNWYwN2Q3NWEzNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJGt0L-0JUJNnkTl_ZKdRnnvocbt2XUM5IpjaiX_OIk)

Thank you! 
This worked for me :D

2024-06-11 01:24 UTC, Doug411 commented
@chinyongcy or @crltc....Has anyone figured out the custom scopes issue with Authentik?  I've tried everthing, but cant pass through a custom property.   Its not showing in my payload in jellyseer.  I can only make this work with email/email_verified.   Thats a bummer.   I have a custom scope going though in jellyfin OIDC plugin, so it seems the issue is on the jellyseer side, not Authentik.

2024-06-15 00:58 UTC, Alumni1506 commented
> For people looking to use the latest version of authelia, using the previous working configuration will result in an error. You need to add `token_endpoint_auth_method: 'client_secret_post'` to the configuration file.

For those that have been running authelia and recently updated, this suggested change fixed my errors post update.

2024-06-24 16:20 UTC, nebb00 commented
Is there a rough idea on a timeline for this support?

2024-09-12 15:46 UTC, Glich440 commented
I have managed to set this up with authelia, but there is one small error, when signing out it redirects to: https://jellyseerr.example.com/api/v1/auth/undefined instead of the login page or whatever page it was trying to redirect to.
No relevant logs

2024-09-13 06:31 UTC, lucaam commented
> Any information of the status of this PR? Currently using the preview branch which seems to work nicely, would love to see it merged. 

Hello, you should have a look here https://github.com/Fallenbagel/jellyseerr/pull/883

2024-09-13 06:47 UTC, Ruakij commented
> > Any information of the status of this PR? Currently using the preview branch which seems to work nicely, would love to see it merged.
> 
> Hello, you should have a look here #883

I dont 100% understand why this cant be parallel? So this PR being integrated before Linking is introduced.
Linking needs to support multiple anyways and needs to migrate current states over, so this wouldnt be an exception. Ideally this would then only incur minimal changes there. (i.e. Enum + adding a Provider)

Just seems this feature will be pushed more and more because of more and more changes to the underlying system and parallel development state. :/

2024-09-13 06:51 UTC, 0dragosh commented
I agree with @Ruakij, it seems this has been pushed for over 2 years yet there’s a build with the feature fully operational.

Are there any downsides to merging what’s in `preview-OIDC` and adding linking later?

2024-09-13 08:09 UTC, Fallenbagel commented
This PR is way outdated. It's not even close to the state that `develop` is in. We cannot just simply merge this pr.

2024-09-13 08:41 UTC, 0dragosh commented
Alright @Fallenbagel, no worries. Thanks for the work!

2024-11-01 11:18 UTC, pando85 commented
If there are some rework here. We should change the callback schema to allow https even if you run it in http because you can deploy Jellyseer behind a reverse proxy which is quite common.

2025-01-08 16:24 UTC, Killerherts commented
Im still running a really old dev branch as i don't want to break all my user logins if anyone moves to a newer branch and it functions can you please @ me. I understand this branch is in a rework state

2025-01-09 21:22 UTC, samip5 commented
Hi @michaelhthomas!

Is this PR abandoned? It sure looks that way and someone else could continue the work?

2025-01-11 02:29 UTC, michaelhthomas commented
> Hi @michaelhthomas!
> 
> Is this PR abandoned? It sure looks that way and someone else could continue the work?

Hi! Please read the earlier discussion. This will be revisited and implemented, but not in this PR. For now, I'll probably close this.

2025-01-11 02:29 UTC, closed without merging

2025-01-11 08:00 UTC, samip5 commented
> > Hi @michaelhthomas!
> > 
> > Is this PR abandoned? It sure looks that way and someone else could continue the work?
> 
> Hi! Please read the earlier discussion. This will be revisited and implemented, but not in this PR. For now, I'll probably close this. 

Hi! I did read the previous messages in the thread but it wasn't apparent to me what's the actual state except that it needs to be remade.

2025-01-18 17:59 UTC, michaelhthomas commented
@samip5 I am still waiting for #883 to be merged. Once that is merged, a PR adding support for OpenID Connect should follow shortly thereafter.

2025-02-06 19:19 UTC, alleyu2 commented
> Really looking forward to this!! Thanks for the great work guys!. This would mean I can ditch this and stay updated ;-) ![Screenshot 2025-02-03 at 16 53 55](https://private-user-images.githubusercontent.com/52012485/409178165-b1b011ff-aa66-4999-8023-93cf96f21d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4Njk4MzgsIm5iZiI6MTczODg2OTUzOCwicGF0aCI6Ii81MjAxMjQ4NS80MDkxNzgxNjUtYjFiMDExZmYtYWE2Ni00OTk5LTgwMjMtOTNjZjk2ZjIxZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDE5MTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzAyNWY1N2NkMmNkOTkwZWM0OTBhMjMzN2Q2YzdhYWUwOThlMjNiNjgzM2Q0YjRiNWY5ZmJlNWNkZDYzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WYBDElWm9Wc-fmRgUoMiDSPXgjgkESq17tt3I2wCmXc)

Just curious what is this and hows does it help with SSO?

2025-02-07 05:21 UTC, samip5 commented
> > Really looking forward to this!! Thanks for the great work guys!. This would mean I can ditch this and stay updated ;-) ![Screenshot 2025-02-03 at 16 53 55](https://private-user-images.githubusercontent.com/52012485/409178165-b1b011ff-aa66-4999-8023-93cf96f21d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4Njk4MzgsIm5iZiI6MTczODg2OTUzOCwicGF0aCI6Ii81MjAxMjQ4NS80MDkxNzgxNjUtYjFiMDExZmYtYWE2Ni00OTk5LTgwMjMtOTNjZjk2ZjIxZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDE5MTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzAyNWY1N2NkMmNkOTkwZWM0OTBhMjMzN2Q2YzdhYWUwOThlMjNiNjgzM2Q0YjRiNWY5ZmJlNWNkZDYzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WYBDElWm9Wc-fmRgUoMiDSPXgjgkESq17tt3I2wCmXc)
> 
> 
> 
> Just curious what is this and hows does it help with SSO?

Basically means they're still running this PR's code instead of being up-to-date.

2025-02-21 00:32 UTC, jridz commented
> @samip5 I am still waiting for #883 to be merged. Once that is merged, a PR adding support for OpenID Connect should follow shortly thereafter.

#883 just merged! Excited to see where this goes.

2025-03-02 09:55 UTC, crazyelectron-io commented
Looking forward to OIDC support in the official release.

2025-03-03 12:40 UTC, edbourque0 commented
> @samip5 I am still waiting for #883 to be merged. Once that is merged, a PR adding support for OpenID Connect should follow shortly thereafter.

@michaelhthomas Is this still in your short-term plans ?

2025-03-03 14:38 UTC, gauthier-th commented
I'm locking this thread because nothing relevant is being said here.
Micheal will work on this when he has time, and we'll do our best to integrate this into Jellyseerr as quickly as possible. Keep in mind that we're all volunteers, and sometimes we have other obligations :wink:

2025-03-24 20:06 UTC, gauthier-th commented
The `preview-OIDC` tag now points to #1505 and not anymore to this PR.