feat(discord.ts): adds a link to the pending approval discord notific…
fallenbagel/jellyseerr pull request #436
Opened 2023-07-20 21:57 UTC by corentinnormand

#### Description
Adds a link to the requests page on the discord  notification for the `Pending Approval` status

2023-09-14 00:55 UTC, Fallenbagel requested changes

2025-03-04 01:51 UTC, fallenbagel approved these changes

2025-03-17 09:54 UTC, gauthier-th commented
@fallenbagel can we merge this?

2025-03-17 09:56 UTC, corentinnormand commented
this feature already exists, i'll close this one

2025-03-17 09:58 UTC, gauthier-th approved these changes

2025-04-04 17:41 UTC, merged

2025-04-04 17:42 UTC, fallenbagel commented
@all-contributors please add @corentinnormand for code

2025-06-09 23:31 UTC, fallenbagel commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on:
- `v2.6.0`
- [GitHub release](https://github.com/fallenbagel/jellyseerr/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: