Added Simplified Chinese
Fallenbagel/jellyseerr pull request #44
Opened 2022-04-10 17:42 UTC by seanzhang98

#### Description

#### Screenshot (if UI-related)

#### To-Dos

- [ ] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #XXXX

2022-04-11 07:27 UTC, Fallenbagel requested changes
Please replace the `overseerr` with `jellyseerr`

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.plexsettingsDescription": "关于 Plex 服务器的设置。Overseerr 将定时运行媒体库扫描。",
"components.Settings.SettingsJobsCache.jobsDescription": "Jellyseerr 将定时运行以下的維護任務。手动运行工作不会影響它正常的时间表。",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Setup.welcome": "欢迎來到 Overseerr",
"components.Setup.welcome": "欢迎來到 Jellyseerr",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.StatusChacker.reloadOverseerr": "重新启动 Overseerr",
"components.StatusChacker.reloadOverseerr": "重新启动 Jellyseerr",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.SettingsAbout.overseerrinformation": "Overseerr 信息",
"components.Settings.SettingsAbout.overseerrinformation": "Jellyseerr 信息",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.SettingsAbout.supportoverseerr": "支持 Overseerr",
"components.Settings.SettingsAbout.supportoverseerr": "支持 Jellyseerr",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.menuAbout": "关于 Overseerr",
"components.Settings.menuAbout": "关于 Jellyseerr",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.SettingsAbout.Releases.runningDevelop": "您正在使用 Overseerr 的开发版本！",
"components.Settings.SettingsAbout.Releases.runningDevelop": "您正在使用 Jellyseerr 的开发版本！",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.SettingsAbout.clickheretojoindiscord": "加入 Overseerr 的 Discord 服务器！",
"components.Settings.SettingsAbout.clickheretojoindiscord": "加入 Jellyseerr 的 Discord 服务器！",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.StatusChacker.newversionDescription": "Overseerr 软件可更新。请点击以下的按钮重新启动。",
"components.StatusChacker.newversionDescription": "Jellyseerr 软件可更新。请点击以下的按钮重新启动。",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.AppDataWarning.dockerVolumeMissingDescription": "必须使用目录（bind mount）指定某个宿主机器的资料夹跟容器內的 <code>{appDataPath}</code> 资料夹連通，才能保存 Overseerr 的配置和数据。",
"components.AppDataWarning.dockerVolumeMissingDescription": "必须使用目录（bind mount）指定某个宿主机器的资料夹跟容器內的 <code>{appDataPath}</code> 资料夹連通，才能保存 Jellyseerr 的配置和数据。",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.PermissionEdit.settingsDescription": "授予管理所有 Overseerr 设置的权限。",
"components.PermissionEdit.settingsDescription": "授予管理所有 Jellyseerr 设置的权限。",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.Notifications.NotificationsPushover.settinguppushoverDescription": "要设置 Pushover 通知，必须先<RegisterApplicationLink>生成一个应用程序</RegisterApplicationLink>，然后在以下输入生成的 API 令牌和您的用户密钥。（添加應
"components.Settings.Notifications.NotificationsPushover.settinguppushoverDescription": "要设置 Pushover 通知，必须先<RegisterApplicationLink>生成一个应用程序</RegisterApplicationLink>，然后在以下输入生成的 API 令牌和您的用户密钥。（添加應用时可以使用 <IconLink>Jellyseerr 的官方圖标</IconLink>。）",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.trustProxyTip": "使用代理服务器时，允许 Overseerr 搜索客戶端 IP 位址（Overseerr 必须重新启动）",
"components.Settings.trustProxyTip": "使用代理服务器时，允许 Jellyseerr 搜索客戶端 IP 位址（Jellyseerr 必须重新启动）",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.csrfProtectionTip": "设置外部访问权限为只讀（Overseerr 必须重新启动）",
"components.Settings.csrfProtectionTip": "设置外部访问权限为只讀（Jellyseerr 必须重新启动）",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.generalsettingsDescription": "Overseerr 的全局和默认设置。",
"components.Settings.generalsettingsDescription": "Jellyseerr 的全局和默认设置。",

2022-04-11 07:27 UTC, Fallenbagel commented on src/i18n/locale/zh_Hans.json
> +  "components.Settings.SettingsJobsCache.jobsDescription": "Overseerr 将定时运行以下的維護任務。手动运行工作不会影響它正常的时间表。",
"components.Settings.SettingsJobsCache.jobsDescription": "Jellyseerr 将定时运行以下的維護任務。手动运行工作不会影響它正常的时间表。",

2022-04-11 07:38 UTC, seanzhang98 commented
updated

2022-04-13 01:23 UTC, merged

2023-11-07 21:22 UTC, Fallenbagel commented
@all-contributors please add @seanzhang98  for translation and code

2023-11-07 21:29 UTC, Fallenbagel commented
@all-contributors please add @seanzhang98 for translation and code

2023-11-07 21:52 UTC, Fallenbagel commented
@all-contributors please add @seanzhang98 for translation and code

2023-11-07 21:58 UTC, Fallenbagel commented
@all-contributors please add @seanzhang98 for translation and code

2023-11-07 22:06 UTC, Fallenbagel commented
@all-contributors please add @seanzhang98 for translation and code

2023-11-07 22:07 UTC, Fallenbagel commented
@all-contributors please add @seanzhang98 for translation and code