feat: support for forwardAuth
fallenbagel/jellyseerr pull request #580
Opened 2023-11-28 22:53 UTC by Janhouse

#### Description
Add support for forwardAuth available with nginx, caddy, traefik, etc. which allows use of SSO without exposing any jellyseerr services to unauthenticated users.

Inspired by similar [PR in overseer](https://github.com/sct/overseerr/pull/3105) but slightly simplified, requiring existing user to authenticate.

#### Screenshot (if UI-related)

#### To-Dos

Still have to add settings to enable this, possibly allow renaming forward auth header, add tests and other minor things.

- [ ] Successful build `yarn build`
- [ ] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

2024-11-20 21:18 UTC, gauthier-th requested changes
Could you please add a bit of documentation for this?

2024-11-21 18:57 UTC, gauthier-th commented on docs/extending-jellyseerr/forward-auth.md
> +> The user has to exist, it will not be created automatically.
Probably better to use a warning instead of a citation.
```suggestion
:::warning
The user has to exist, it will not be created automatically.
:::
```

2024-11-21 19:03 UTC, gauthier-th commented on server/middleware/auth.ts
> +      : settings.main.locale;
This is not necessary, it's a duplicate from below.

2024-11-21 19:08 UTC, gauthier-th commented on overseerr-api.yml
> +          example: true
You wrote the setting here, but it is not available anywhere.

You should add this as a general setting, by adding a new properties in the `MainSettings` type in `server/lib/settings.ts` and adding a new input in the settings page in `src/components/Settings/SettingsMain/index.tsx`. You should also check that this setting is enabled before allowing login with forwardAuth.

Or did you intend to not make a setting and set it enabled by default?

2024-11-21 19:13 UTC, gauthier-th commented on overseerr-api.yml
> +  - forwardAuth: []
This is not in the OpenAPI spec?
https://spec.openapis.org/oas/latest.html#security-scheme-object-0

2024-11-21 19:21 UTC, gauthier-th commented on src/utils/localRequestHelper.ts
> +export const getRequestHeaders = (
Shouldn't this function be called something like `getAuthHeaders` instead of `getRequestHeaders`?

2024-11-21 19:22 UTC, gauthier-th commented on src/utils/localRequestHelper.ts
Wdyt about renaming this file to something like `serverSidePropsHelpers`?

2025-01-04 16:34 UTC, hiasr commented
LMK if any help is needed here, would love to get this through!

2025-01-15 16:17 UTC, Janhouse commented
@hiasr @gauthier-th, feel free to make the necessary changes. I made them when I had some free time but that is currently not the case.

2025-02-11 22:48 UTC, gauthier-th commented
Closed in favor of #1341

2025-02-11 22:48 UTC, closed without merging