fix(api): save user email on the first try
Fallenbagel/jellyseerr pull request #760
Opened 2024-05-22 16:24 UTC by gauthier-th

#### Description

Fix email field in profile settings where it requires you to enter the email once, press save, and then to enter it again and re-save.

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #227

2024-05-23 10:46 UTC, Fallenbagel requested changes

2024-05-23 10:46 UTC, Fallenbagel commented on server/routes/user/usersettings.ts
> +    // TODO: check if the email of the user has been modified after save (if the email already exists in the db)
Remove this todo

2024-05-23 18:11 UTC, Gauvino approved these changes
Tested successfully, trying multiple account different manipulation everything I could and now work like a charm thanks you!

2024-05-23 18:56 UTC, merged

2024-05-24 16:17 UTC, Fallenbagel commented
@all-contributors please add @gauthier-th  for code

2024-05-29 14:00 UTC, Fallenbagel commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- `v1.9.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: