feat: Option on item's page to add/remove from watchlist
Fallenbagel/jellyseerr pull request #781
Opened 2024-05-30 03:26 UTC by JoaquinOlivero

re #730

#### Description
Adds a button on the individual media item's page to add or remove it from the user's watchlist.

#### Screenshot (if UI-related)
![output](https://github.com/Fallenbagel/jellyseerr/assets/66050823/0e90f1ec-076c-461a-82b3-2e6e46142659)

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #730

2024-05-30 15:27 UTC, Fallenbagel requested changes

2024-05-30 15:27 UTC, Fallenbagel commented on src/i18n/locale/en.json
> -  "components.Settings.plexsettingsDescription": "Configure the settings for your Plex server. Jellyseerr scans your Plex libraries to determine content availability.",
This should not be changed

2024-05-30 15:27 UTC, Fallenbagel commented on src/components/MovieDetails/index.tsx
> +    '<strong>{title}</strong> added to watchlist  successfully!',
Little nitpick but remove the extra whitespace after `watchlist`

2024-05-30 15:27 UTC, Fallenbagel commented on src/components/MovieDetails/index.tsx
> +    '<strong>{title}</strong> Removed from watchlist  successfully!',
Here as well

2024-05-30 15:27 UTC, Fallenbagel commented on src/components/TvDetails/index.tsx
> +    '<strong>{title}</strong> added to watchlist  successfully!',
Refer to my previous comment

2024-05-30 15:27 UTC, Fallenbagel commented on src/components/TvDetails/index.tsx
> +    '<strong>{title}</strong> Removed from watchlist  successfully!',
Refer to my previous comment

2024-05-30 15:27 UTC, Fallenbagel commented on src/i18n/locale/en.json
> +  "components.MovieDetails.watchlistDeleted": "<strong>{title}</strong> Removed from watchlist  successfully!",
Refer to my previous comment (extraction after fixing my previous comment should fix this)

2024-05-30 15:27 UTC, Fallenbagel commented on src/i18n/locale/en.json
> +  "components.MovieDetails.watchlistSuccess": "<strong>{title}</strong> added to watchlist  successfully!",
Refer to my previous comment

2024-05-30 15:27 UTC, fallenbagel commented on src/i18n/locale/en.json
> +  "components.TvDetails.watchlistDeleted": "<strong>{title}</strong> Removed from watchlist  successfully!",
Refer to my previous comment

2024-05-30 15:27 UTC, fallenbagel commented on src/i18n/locale/en.json
> +  "components.TvDetails.watchlistSuccess": "<strong>{title}</strong> added to watchlist  successfully!",
Refer to my previous comment

2024-05-31 12:21 UTC, gauthier-th approved these changes
LGTM!
Thanks for this nice feature :)

2024-05-31 12:26 UTC, Fallenbagel approved these changes

2024-05-31 12:27 UTC, Gauvino commented
Could I just run the PR myself to see if everything ok before merging?

2024-05-31 12:28 UTC, gauthier-th commented
> Could I just run the PR myself to see if everything ok before merging?

Go ahead

2024-07-22 08:58 UTC, gauthier-th approved these changes

2024-08-07 11:46 UTC, merged

2024-10-15 18:21 UTC, Fallenbagel commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `v2.0.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: