Add environment variable for API key
Fallenbagel/jellyseerr pull request #831
Opened 2024-06-23 04:14 UTC by AidanHilt

#### Description
Adds an environment variable, API_KEY, that can be used to set the API key. If the environment variable is not set, the previous method is used.

#### Screenshot (if UI-related)

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`
- [x] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #XXXX

2024-06-23 09:34 UTC, gauthier-th commented
For what use cases do you need this?

2024-06-23 16:58 UTC, AidanHilt commented
The main advantage of this setup is for people who use tools like: https://github.com/buildarr/buildarr-jellyseerr. Buildarr is a configuration management tool for the Jellyseerr and the -arr stack, and it can completely initialize Jellyseerr automatically, if provided with the API key. This makes it possible to generate that key externally, and then provide it to both Jellyseerr and a configuration management tool like Buildarr.

2024-07-22 08:52 UTC, gauthier-th commented on src/i18n/locale/en.json
> +  "components.Settings.plexsettingsDescription": "Configure the settings for your Plex server. Overseerr scans your Plex libraries to determine content availability.",
This shouldn't be changed

2024-08-03 18:59 UTC, AidanHilt commented
I removed the change, pulled the latest changes from develop, and added documentation

2024-08-05 08:26 UTC, gauthier-th requested changes
What you've done won't work if the API_KEY environment variable is changed after the 1st restart of Jellyseerr, unless you click on "regenerate" after setting it.

It seems odd to have to regenerate a key you've just defined manually, so you should add a check each time you start Jellyseerr to check whether there's an API_KEY environment variable, and if so change the main settings with this key.

2024-09-09 13:43 UTC, AidanHilt commented
Alright, I went ahead and added a check when the settings load, if the environment variable is set it will read that and use that at startup. I made sure to pull in the latest changes on develop. Documentation is still updated as well. Anything else I should adjust or any changes to be made?

2024-09-14 22:36 UTC, gauthier-th approved these changes
LGTM

2024-09-16 17:05 UTC, Fallenbagel approved these changes

2024-09-16 17:05 UTC, merged

2024-10-15 18:20 UTC, Fallenbagel commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `v2.0.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: