feat(translation): added full Hebrew translation
Fallenbagel/jellyseerr pull request #871
Opened 2024-07-11 20:45 UTC by mobihen

#### Description
Added Hebrew translation to the project. 
I ran it and translated everything live.

2024-07-18 04:52 UTC, mobihen commented
@Fallenbagel 
Hi :) 
Can you please review?

2024-07-18 13:00 UTC, Fallenbagel approved these changes
LGTM!

2024-07-18 13:10 UTC, gauthier-th requested changes
There is still a few missing translations. Could you please translate them?
I didn't go into details, I just highlighted the ones i saw.

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.Discover.FilterSlideover.voteCount": "Number of votes between {minValue} and {maxValue}",
here

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.Discover.PlexWatchlistSlider.emptywatchlist": "Media added to your <PlexWatchlistSupportLink>Plex Watchlist</PlexWatchlistSupportLink> will appear here.",
here

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.Discover.emptywatchlist": "Media added to your <PlexWatchlistSupportLink>Plex Watchlist</PlexWatchlistSupportLink> will appear here.",
here

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.Discover.resetwarning": "Reset all sliders to default. This will also delete any custom sliders!",
here too

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.IssueDetails.IssueComment.postedbyedited": "Posted {relativeTime} by {username} (Edited)",
here too

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.Layout.Sidebar.dashboard": "Discover",
This one too, it is always visible in the sidebar

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.UserList.newplexsigninenabled": "The <strong>Enable New Plex Sign-In</strong> setting is currently enabled. Plex users with library access do not need to be imported in order to sign in
Here too

2024-07-18 13:10 UTC, gauthier-th commented on src/i18n/locale/he.json
> +  "components.Settings.tautulliSettingsDescription": "Optionally configure the settings for your Tautulli server. Jellyseerr fetches watch history data for your Plex media from Tautulli.",
Here

2024-07-18 13:35 UTC, Fallenbagel commented
> There is still a few missing translations. Could you please translate them? I didn't go into details, I just highlighted the ones i saw.

Oh yeah. I just went over it too quickly and didn't notice

2024-07-18 13:35 UTC, Fallenbagel requested changes
@mobihen please translate the missing ones

2024-07-23 10:42 UTC, mobihen commented
@gauthier-th 
I've fixed missing translations as requested :)

Thanks

2024-07-23 12:21 UTC, gauthier-th approved these changes
LGTM

2024-07-24 18:46 UTC, Fallenbagel approved these changes

2024-07-24 18:49 UTC, mobihen commented
@Fallenbagel 
Please merge while no conflicts :)
I do not have write access permissions to the repo.

2024-07-24 18:51 UTC, merged

2024-08-05 12:04 UTC, Fallenbagel commented
@all-contributors please add @mobihen for translation

2024-10-15 18:22 UTC, Fallenbagel commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `v2.0.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-07-07 16:24 UTC, controlfix87 commented
@fallenbagel 
Hi, Just wnated to know the reason that i'm not in the contributors sections.. 
Thanks :)

2025-07-07 18:02 UTC, gauthier-th commented
@all-contributors please add @mobihen for translation

2025-07-07 18:04 UTC, gauthier-th commented
> Hi, Just wnated to know the reason that i'm not in the contributors sections..

~We simply forgot :)~
~Oh sorry, yeah a merge issue happened in the readme, i'll make a PR to fix it~

2025-07-07 18:13 UTC, mobihen commented
Thank you very much!

2025-07-07 18:21 UTC, gauthier-th commented
![image](https://github.com/user-attachments/assets/37b4f805-4024-4841-8b7d-65b41f4f836c)

My bad I looked at it too fast - you're correctly listed as a contributor.

2025-07-07 18:58 UTC, mobihen commented
I did check before bud didnt see it.. well. all is OK. THANKS!