feat: override rules
Fallenbagel/jellyseerr pull request #945
Opened 2024-08-26 10:24 UTC by gauthier-th

#### Description

This PR introduces override rules in Jellyseerr.
Override rules are used to define conditions for each service (i.e. for each Radarr/Sonarr server) on which parameters will be modified.
For example, it's possible to define a different quality profile for certain users, or change the root path according to the genre of a film or series, etc.

#### Screenshot (if UI-related)

![image](https://github.com/user-attachments/assets/2b552fe8-a387-4532-ace6-5d3277493553)
![image](https://github.com/user-attachments/assets/9783e284-0776-4297-a378-03d57a0558d0)

#### To-Dos

- [x] Successful build `pnpm build`
- [x] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #171
- Fixes #419
- Fixes #909
- Fixes #921

2024-10-24 18:04 UTC, juancarlosromerogarcia commented
lint & Test Build, Post Setup pnpm cache,
`/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /__w/jellyseerr/jellyseerr --files-from manifest.txt -z`
/bin/tar: unrecognized option: posix

2024-10-24 19:30 UTC, gauthier-th commented
> lint & Test Build, Post Setup pnpm cache,
> `/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /__w/jellyseerr/jellyseerr --files-from manifest.txt -z`
> /bin/tar: unrecognized option: posix

What is this supposed to mean?

2024-11-14 16:15 UTC, gauthier-th commented
For anyone willing to test this, it's available with the preview tag: `preview-override-rules`
PS: remember to do backups :wink:

2024-11-15 21:36 UTC, feerlessleadr commented
@gauthier-th I just pulled this image and am doing some testing. For some reason when I try to add an override rule to either sonarr or radarr, I'm not able to create the rule. When I click on 'Creat Rule' nothing happens, and I don't see anything (either errors or anything at all) either the jellyseer log or the docker logs. Here is the rule I'm trying to create for sonarr:

![image](https://github.com/user-attachments/assets/e92a363c-c8da-4ef5-a4a7-339bafa9405d)

2024-11-17 19:35 UTC, gauthier-th commented
> @gauthier-th I just pulled this image and am doing some testing. For some reason when I try to add an override rule to either sonarr or radarr, I'm not able to create the rule. When I click on 'Creat Rule' nothing happens, and I don't see anything (either errors or anything at all) either the jellyseer log or the docker logs. Here is the rule I'm trying to create for sonarr:
> 
> ![image](https://private-user-images.githubusercontent.com/288895/386766128-e92a363c-c8da-4ef5-a4a7-339bafa9405d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NTgzNzksIm5iZiI6MTczMTg1ODA3OSwicGF0aCI6Ii8yODg4OTUvMzg2NzY2MTI4LWU5MmEzNjNjLWM4ZGEtNGVmNS1hNGE3LTMzOWJhZmE5NDA1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNTQxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmZjMDVmYWVlYjAyZjBhOTVjZjMwNDY4MWFlYzk0M2MwMGE4ZmRjYWRjNGI1ODJkMzZmOTJjMGVjYjFjYWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jDudbSJU4E5WbRA9gO7e9wJHS9Hxg4lV7nF2qXOhk14)

I just rebased the PR to the latest commit of develop, can you please test again with this version? (you'll need to update the Docker image)

If it's still not working, could you check Jellyseerr logs as well as your browser logs and see if there is anything there? (F12 -> Console)

2024-11-18 07:57 UTC, Fallenbagel commented
> I have tried it but nothing happens when I press the `create rule` button. In my browser console, every so often, it shows a 404 error: message "`SQLITE_ERROR: no such table: override_rule`"

That means your migrations didn't apply. Can you test with a fresh config first?

2024-11-18 18:18 UTC, starlingfire commented
I just tried testing this as well, and can't get the override screen to appear. Here's how I set it up, in case I did something wrong:

1. Cloned this repo
2. Changed to develop branch: `git branch develop`
3. Build/run with docker compose: `docker compose up -d`
4. Connect to local Radarr and Jellyfin instances

My Radarr edit screen looks like this:

![image](https://github.com/user-attachments/assets/dc96ac38-4712-40c3-8f11-054ab84d004f)

The About page shows I'm on develop:

![image](https://github.com/user-attachments/assets/aa1b0161-dbb1-4091-ab70-b577d0fc4b99)

Ran the following to confirm my working environment:
```
root@playground:~/jellyseerr# git switch develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
```

2024-11-18 18:29 UTC, Fallenbagel commented
> I just tried testing this as well, and can't get the override screen to appear. Here's how I set it up, in case I did something wrong:
> 
> 1. Cloned this repo
> 2. Changed to develop branch: `git branch develop`
> 3. Build/run with docker compose: `docker compose up -d`
> 4. Connect to local Radarr and Jellyfin instances
> 
> My Radarr edit screen looks like this:
> 
> ![image](https://github.com/user-attachments/assets/dc96ac38-4712-40c3-8f11-054ab84d004f)
> 
> The About page shows I'm on develop:
> 
> ![image](https://github.com/user-attachments/assets/aa1b0161-dbb1-4091-ab70-b577d0fc4b99)
> 
> Ran the following to confirm my working environment:
> ```
> root@playground:~/jellyseerr# git switch develop
> Already on 'develop'
> Your branch is up to date with 'origin/develop'.
> ```

It's not in develop branch. It's in `override rules`. Also you don't need to build the image we already have `preview-override-rules` as an image...

2024-11-18 18:40 UTC, starlingfire commented
> It's not in develop branch. It's in `override rules`. Also you don't need to build the image we already have `preview-override-rules` as an image...

Thank you!

Got the preview image running, and I get 404 errors in the browser log trying to save the override rule (and on a recurring basis simply while on that screen).
```
XHRGET
http://192.168.1.205:5055/api/v1/overrideRule
[HTTP/1.1 404 Not Found 8ms]

	
GET
	http://192.168.1.205:5055/api/v1/overrideRule
Status
404
Not Found
VersionHTTP/1.1
Transferred298 B (56 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem

    	
    Connection
    	keep-alive
    Content-Length
    	56
    Content-Type
    	application/json; charset=utf-8
    Date
    	Mon, 18 Nov 2024 18:38:16 GMT
    ETag
    	W/"38-[redacted]"
    Keep-Alive
    	timeout=5
    X-Powered-By
    	Express
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	connect.sid=[redacted]
    DNT
    	1
    Host
    	192.168.1.205:5055
    Priority
    	u=4
    Referer
    	http://192.168.1.205:5055/settings/services
    Sec-GPC
    	1
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
```

2024-11-18 19:51 UTC, gauthier-th commented
Oops, I may have forgotten to write the migration. I'll write them and it should work better 😅

2024-11-18 21:37 UTC, gauthier-th commented
@starlingfire the migration script has been added. Can you please test again? (you'll need to update the Docker image)

2024-11-18 22:31 UTC, starlingfire commented
@gauthier-th so far, so good. I added an override rule to put a user's downloads in a different root folder, and it appears to be working. I'll mess around with it more tomorrow when I get a bit more time. I'm so excited to have this feature!

2024-11-18 23:13 UTC, feerlessleadr commented
Just tested on my system and it seems to be working as well. Thanks for this!

2024-11-19 08:07 UTC, juancarlosromerogarcia commented
I have tested both sonarr and radarr with various rules that assign root folders depending on the user. It works without problems.
[gauthier-th](https://github.com/gauthier-th) thanks a lot for your work.

2024-12-02 02:50 UTC, Yankees4life commented
@Fallenbagel 

I hope this gets merged. It will certainly help me set up Radarr Anime instances easily

2024-12-16 15:45 UTC, Fallenbagel requested changes

2024-12-16 15:45 UTC, fallenbagel commented on server/migration/1731963944025-AddOverrideRules.ts
This needs to be moved into sqlite folder and a postgres migration needs to be generated right?

2024-12-16 15:54 UTC, gauthier-th commented on server/migration/1731963944025-AddOverrideRules.ts
Yep

2024-12-16 23:26 UTC, actuallyevan commented
Would this allow routing to multiple *arr instances simultaneously? Really looking forward to this being merged!

2024-12-17 09:39 UTC, gauthier-th commented
> Would this allow routing to multiple *arr instances simultaneously?

No, this will not change the behavior of the *arr instances, just change which parameters are passed to the instance when a media is requested.

2024-12-17 12:34 UTC, starlingfire commented
> Would this allow routing to multiple *arr instances simultaneously? Really looking forward to this being merged!

This _will_ let you route media to different root folders based on who made the request, so each user can add to their own individual library. But you can do that within the same instance of the arr stack, you don't need multiple.

2024-12-19 10:36 UTC, actuallyevan commented
> > Would this allow routing to multiple *arr instances simultaneously? Really looking forward to this being merged!
> 
> This _will_ let you route media to different root folders based on who made the request, so each user can add to their own individual library. But you can do that within the same instance of the arr stack, you don't need multiple.

Yeah, I figured. Eventually hoping for something like [this](https://github.com/varthe/Redirecterr) to become native functionality in a *seerr

2024-12-23 12:23 UTC, Dental1347 commented
> > Would this allow routing to multiple *arr instances simultaneously?
> 
> No, this will not change the behavior of the *arr instances, just change which parameters are passed to the instance when a media is requested.

I've got a question with a usecase.
Currently, it's near impossible to setup a sonarr instance for series and a sonarr instance for anime. Because, the series tab is require to be filled in.

I guess that as a workaround, it could be possible to setup the sonarr series, and not configure anime, and set this as default. But, for the sonarr anime, you configure series as a dummy, and setup anime as you would normally.

With this pull, is it then possible to setup a condition that:
1. if it's anime, send it to the sonarr anime instance, instead of the sonarr series?

2024-12-23 13:28 UTC, gauthier-th commented
>  Currently, it's near impossible to setup a sonarr instance for series and a sonarr instance for anime. Because, the series tab is require to be filled in.

This is something #232 should solve, and it's on our roadmap.

2024-12-27 21:25 UTC, Fallenbagel commented on src/components/Discover/DiscoverTvUpcoming.tsx
> +  upcomingtv: 'Upcoming Series',
Is this relevant for this PR?

2024-12-27 21:25 UTC, Fallenbagel commented on src/components/Settings/SonarrModal/index.tsx
> +  const [testResponse, setTestResponse] = useState<SonarrTestResponse>({
Why is there a difference in consistency for test response in sonarr modal compared to radarr modal

2024-12-27 21:25 UTC, Fallenbagel commented on src/utils/defineMessages.ts
Is this change relevant to this PR?

2024-12-27 23:57 UTC, actuallyevan commented
> > > Would this allow routing to multiple *arr instances simultaneously?
> > 
> > 
> > No, this will not change the behavior of the *arr instances, just change which parameters are passed to the instance when a media is requested.
> 
> I've got a question with a usecase. Currently, it's near impossible to setup a sonarr instance for series and a sonarr instance for anime. Because, the series tab is require to be filled in.
> 
> I guess that as a workaround, it could be possible to setup the sonarr series, and not configure anime, and set this as default. But, for the sonarr anime, you configure series as a dummy, and setup anime as you would normally.
> 
> With this pull, is it then possible to setup a condition that:
> 
> 1. if it's anime, send it to the sonarr anime instance, instead of the sonarr series?

I would use [Redirecterr](https://github.com/varthe/Redirecterr). There is also a custom Overseerr (not jelly) anime instance floating around. This is how I do it, and I think achieves the functionality you're looking for.

2024-12-28 21:13 UTC, Fallenbagel approved these changes

2024-12-28 21:20 UTC, merged

2024-12-29 22:55 UTC, Fallenbagel commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- `v2.2.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-06-07 15:43 UTC, jerry00020001 commented
Would it be possible to add an override rule based on date released?

2025-06-16 13:29 UTC, gauthier-th commented
> Would it be possible to add an override rule based on date released?

Please open an issue for a feature request. This is not the right place to ask.