feat: add separate setting for streaming region
Fallenbagel/jellyseerr pull request #993
Opened 2024-10-02 23:53 UTC by gauthier-th

#### Description

Currently, the "Currently Streaming On" information is based on the Discover Region setting. This PR adds a new setting to specify which region should be used to display the streaming region.

#### Screenshot (if UI-related)

New setting in general settings as well as in user settings:
![image](https://github.com/user-attachments/assets/9ef0850a-bc15-4a10-8a49-9113cd472f4c)

#### To-Dos

- [x] Successful build `pnpm build`
- [x] Translation keys `pnpm i18n:extract`
- [x] Database migration (if required)

#### Issues Fixed or Closed

- Re #890

2024-12-07 16:55 UTC, Fallenbagel requested changes

2024-12-07 16:55 UTC, Fallenbagel commented on server/lib/settings/migrations/0004_migrate_region_setting.ts
> +const migrateHostname = (settings: any): AllSettings => {
Why is this called `migrateHostname`?

2024-12-08 13:43 UTC, gauthier-th commented on server/lib/settings/migrations/0004_migrate_region_setting.ts
> +const migrateHostname = (settings: any): AllSettings => {
Copy/paste error, let me fix it

2024-12-08 16:13 UTC, Fallenbagel approved these changes
LGTM

2024-12-08 16:19 UTC, merged

2024-12-29 22:56 UTC, Fallenbagel commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- `v2.2.0`
- [GitHub release](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: